#!/usr/bin/env python3
"""Generate remotion/src/data/miranda_animatic.ts from the approved script + scene plan.

Drives the $0 animatic (no narration audio). Re-run if the script or scene plan change:
    py remotion/scripts/gen_animatic_data.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "episodes/PD-2026-001-miranda/03_script/script.annotated.v001.json"
SCENES = ROOT / "episodes/PD-2026-001-miranda/04_scenes/scene_plan.v001.json"
OUT = ROOT / "remotion/src/data/miranda_animatic.ts"


def esc_tpl(s: str) -> str:
    # for a TS template literal: escape backslash, backtick, ${
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def esc_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    sc = json.loads(SCRIPT.read_text(encoding="utf-8"))
    sp = json.loads(SCENES.read_text(encoding="utf-8"))
    spans = {s["span_id"]: s for s in sc["spans"]}

    rows = []
    for s in sp["scenes"]:
        sid = s["scene_id"]
        span = spans[s["script_span_ids"][0]]
        pid = s.get("primary_claim_id")
        assets = s.get("required_assets", [])
        motif = next((a for a in assets if a.startswith(("MJ-EP:", "MOT:"))), assets[0] if assets else "")
        citation = (
            '{source: "Miranda v. Arizona, 384 U.S. 436 (1966)", claimIds: ["%s"]}' % pid
            if pid
            else "null"
        )
        ost = ", ".join('"%s"' % esc_str(t) for t in s.get("on_screen_text", []))
        rows.append(
            '  {sceneId: "%s", visualMode: "%s", durationSec: %s, emotion: "%s", '
            'review: %s, motifHint: "%s", onScreenText: [%s], citation: %s, caption: `%s`}'
            % (
                sid,
                s["visual_mode"],
                s["duration_seconds"],
                s["emotional_function"],
                "true" if s["human_review_required"] else "false",
                esc_str(motif),
                ost,
                citation,
                esc_tpl(span["text"]),
            )
        )

    ts = (
        "// AUTO-GENERATED by remotion/scripts/gen_animatic_data.py from\n"
        "// 03_script/script.annotated.v001.json + 04_scenes/scene_plan.v001.json. Do not hand-edit.\n\n"
        "export type AnimaticScene = {\n"
        "  sceneId: string;\n"
        "  visualMode: string;\n"
        "  durationSec: number;\n"
        "  emotion: string;\n"
        "  review: boolean;\n"
        "  motifHint: string;\n"
        "  onScreenText: string[];\n"
        "  citation: {source: string; claimIds: string[]} | null;\n"
        "  caption: string;\n"
        "};\n\n"
        "export const MIRANDA_ANIMATIC: AnimaticScene[] = [\n"
        + ",\n".join(rows)
        + ",\n];\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(ts, encoding="utf-8")
    total = sum(s["duration_seconds"] for s in sp["scenes"])
    print(f"wrote {OUT} | {len(sp['scenes'])} scenes | {total}s")


if __name__ == "__main__":
    main()
