#!/usr/bin/env python3
"""Generate remotion/src/data/gideon_animatic.ts from gideon scene_plan + the real TTS timing.

Unlike EP1's generator (script-derived durations, no audio), gideon already has narration, so
durations come from 08_edit/timing.v001.json: each scene runs from its narration-chunk start to
the next chunk's start (last scene to the master end). That makes the animatic length == the
narration master (694.411s) and keeps the burned SRT (narration-timed) aligned to each scene.

Emits GIDEON_ANIMATIC (AnimaticScene[]) + GIDEON_SCENE_IMG (scene -> remotion/public still).
    py -3.11 remotion/scripts/gen_gideon_animatic.py
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCENES = ROOT / "episodes/PD-2026-002-gideon/04_scenes/scene_plan.v001.json"
TIMING = ROOT / "episodes/PD-2026-002-gideon/08_edit/timing.v001.json"
OUT = ROOT / "remotion/src/data/gideon_animatic.ts"

# scene -> routed still in remotion/public (Ken-Burns bg). Omitted scenes render coded art
# (KineticType / DiagramFlow / SceneArt) from onScreenText, exactly like EP1's coded scenes.
SCENE_IMG = {
    "S001": "mj/s008_pencil_closeup.png",
    "S002": "mj/s002_prison_cell.png",
    "S003": "mj/s003_lone_defendant.png",
    "S004": "mj/s004_courtroom_1961.png",
    "S005": "mj/s005_empty_chair.png",
    "S007": "mj/s007_gideon_defending.png",
    "S008": "mj/s008_pencil_closeup.png",
    "S009": "mj/s009_hand_writing.png",
    "S010": "mj/s010_petition_document.png",
    "S011": "mj/s011_1942_court.png",
    "S013": "mj/s013_fortas_symbolic.png",
    "S014": "mj/s014_crowd_silhouettes.png",
    "S015": "mj/s015_scotus_chamber.png",
    "S019": "mj/s010_petition_document.png",
    "S020": "mj/s020_retrial_filled_chair.png",
    "S021": "mj/s021_defense_attorney.png",
    "S023": "mj/s023_public_defender_office.png",
    "S024": "mj/s024_overloaded_desk.png",
    "S026": "mj/s026_letter_mailbox.png",
    "S027": "mj/s003_lone_defendant.png",
}


def esc_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    sp = json.loads(SCENES.read_text(encoding="utf-8"))
    tm = json.loads(TIMING.read_text(encoding="utf-8"))
    total = tm["total_seconds"]
    starts = {s["scene_id"]: s["start"] for s in tm["scenes"]}
    order = [s["scene_id"] for s in tm["scenes"]]

    def duration(sid: str) -> float:
        i = order.index(sid)
        nxt = starts[order[i + 1]] if i + 1 < len(order) else total
        return round(nxt - starts[sid], 3)

    rows = []
    for s in sp["scenes"]:
        sid = s["scene_id"]
        pid = s.get("primary_claim_id")
        citation = ('{source: "Gideon v. Wainwright, 372 U.S. 335 (1963)", claimIds: ["%s"]}' % pid
                    if pid else "null")
        ost = ", ".join('"%s"' % esc_str(t) for t in s.get("on_screen_text", []))
        assets = s.get("required_assets", [])
        motif = next((a for a in assets if a.startswith(("MJ", "REM", "MOT", "PD", "RUNWAY"))),
                     assets[0] if assets else "")
        rows.append(
            '  {sceneId: "%s", visualMode: "%s", durationSec: %s, emotion: "%s", '
            'review: %s, motifHint: "%s", onScreenText: [%s], citation: %s, caption: ``}'
            % (sid, s["visual_mode"], duration(sid), s["emotional_function"],
               "true" if s.get("human_review_required") else "false", esc_str(motif), ost, citation)
        )

    img_rows = ",\n".join('  %s: "%s"' % (k, v) for k, v in SCENE_IMG.items())
    ts = (
        "// AUTO-GENERATED by remotion/scripts/gen_gideon_animatic.py from\n"
        "// 04_scenes/scene_plan.v001.json + 08_edit/timing.v001.json. Do not hand-edit.\n"
        "// Durations come from the real TTS timeline so the animatic == narration master.\n\n"
        'import type {AnimaticScene} from "./miranda_animatic";\n\n'
        "export const GIDEON_ANIMATIC: AnimaticScene[] = [\n" + ",\n".join(rows) + ",\n];\n\n"
        "export const GIDEON_SCENE_IMG: Partial<Record<string, string>> = {\n" + img_rows + ",\n};\n"
    )
    OUT.write_text(ts, encoding="utf-8")
    dur_sum = sum(duration(s["scene_id"]) for s in sp["scenes"])
    print(f"wrote {OUT.relative_to(ROOT)} | {len(sp['scenes'])} scenes | sum={dur_sum:.1f}s | master={total}s")


if __name__ == "__main__":
    main()
