import React from 'react';
import {AbsoluteFill, Audio, Sequence, staticFile} from 'remotion';
import {BRAND} from '../brand';
import {Opening} from './Opening';
import {KineticType} from '../components/KineticType';
import {SymbolicScene} from '../components/Parallax';
import {CitationLowerThird} from '../components/CitationLowerThird';
import {DiagramFlow} from '../components/DiagramFlow';
import {OpenCaption} from '../components/OpenCaption';
import {WipeTransition} from '../components/Transition';
import {Grain} from '../components/Grain';
import {Horizon, PdMonogram} from '../components/Brand';

export type StyleTestProps = {
  /** Placeholder BGM in remotion/public/ (generated by scripts/make_placeholder_bgm.py). */
  bgmSrc?: string | null;
};

const MiniEnding: React.FC = () => (
  <AbsoluteFill
    style={{
      background: `radial-gradient(120% 100% at 50% 40%, ${BRAND.color.navy} 0%, ${BRAND.color.ink} 80%)`,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 18,
    }}
  >
    <Horizon y={0.72} />
    <PdMonogram size={150} />
    <div
      style={{
        color: BRAND.color.white,
        fontFamily: BRAND.font.display,
        fontSize: 44,
        letterSpacing: 8,
        textTransform: 'uppercase',
      }}
    >
      Prime Documentary
    </div>
    <div style={{color: BRAND.color.gold, fontFamily: BRAND.font.body, fontSize: 26}}>
      Subscribe
    </div>
  </AbsoluteFill>
);

/**
 * 1-minute style test (1080p / 30fps / 60s). $0, pure code, no paid assets.
 * Showcases the reusable component library on the Miranda theme (decisions/0002 §4/§5/§B).
 */
export const StyleTest: React.FC<StyleTestProps> = ({bgmSrc = 'bgm_placeholder.wav'}) => {
  return (
    <AbsoluteFill style={{backgroundColor: BRAND.color.ink}}>
      {/* 0–5s opening */}
      <Sequence from={0} durationInFrames={150} name="Opening">
        <Opening channelName="Prime Documentary" />
      </Sequence>

      {/* 5–18s hook (kinetic typography) */}
      <Sequence from={150} durationInFrames={390} name="Hook">
        <KineticType
          lines={[
            {text: 'Why Do Police Have to', at: 0},
            {text: 'Read You Your Rights?', at: 12},
            {text: 'One confession in 1963 rewrote every arrest in America.', at: 150, emphasis: true},
          ]}
        />
      </Sequence>

      {/* 18–30s parallax + citation lower-third */}
      <Sequence from={540} durationInFrames={360} name="Parallax">
        <SymbolicScene />
        <CitationLowerThird label="Phoenix, Arizona — 1963" />
      </Sequence>

      {/* 30–45s animated diagram + source citation (CLM-0003/0004) */}
      <Sequence from={900} durationInFrames={450} name="Diagram">
        <DiagramFlow steps={['Custodial interrogation', '5th Amendment', 'Required warnings']} />
        <CitationLowerThird
          label="The system"
          source="Miranda v. Arizona, 384 U.S. 436 (1966)"
          claimIds={['CLM-0003', 'CLM-0004']}
        />
      </Sequence>

      {/* 45–55s open-caption sample */}
      <Sequence from={1350} durationInFrames={300} name="OpenCaption">
        <AbsoluteFill
          style={{background: `radial-gradient(120% 100% at 50% 40%, ${BRAND.color.navy} 0%, ${BRAND.color.ink} 85%)`}}
        />
        <OpenCaption
          text="The warning is not a courtesy — it is a repair the Court bolted onto the Fifth Amendment."
          revealFrames={210}
        />
      </Sequence>

      {/* 55–60s mini ending */}
      <Sequence from={1650} durationInFrames={150} name="Ending">
        <MiniEnding />
      </Sequence>

      {/* wipe transitions at segment boundaries */}
      {[150, 540, 900, 1350, 1650].map((f) => (
        <Sequence key={f} from={f - 9} durationInFrames={18} name="Wipe">
          <WipeTransition />
        </Sequence>
      ))}

      {/* grain over everything */}
      <Grain />

      {/* placeholder BGM */}
      {bgmSrc ? <Audio src={staticFile(bgmSrc)} volume={0.45} /> : null}
    </AbsoluteFill>
  );
};
