// AUTO-GENERATED by scripts/import_to_remotion.py from PD-2026-010-kelo/04_scenes/shotlist.v001.json
// + 05_stock/usable_assets.v001.json. Do NOT edit by hand; re-run the importer.
import type {RoughCutData} from '../compositions/RoughCut';

export const KELO_ROUGHCUT: RoughCutData = {
  "episodeId": "PD-2026-010-kelo",
  "title": "The Government Took Their Homes for a Developer — Then the Plan Collapsed",
  "fps": 30,
  "narrationSrc": null,
  "bgmSrc": null,
  "shots": [
    {
      "spanId": "SPN-0001",
      "chapterId": "hook",
      "seconds": 28.0,
      "assetType": "ai_image",
      "motion": "parallax",
      "src": "kelo/pexels_i_15263342.jpg",
      "telop": [
        "Your home — for a private developer?"
      ],
      "priority": "A",
      "images": [
        "kelo/pexels_i_15263342.jpg",
        "kelo/pexels_i_19378121.jpg",
        "kelo/pexels_i_37900459.jpg",
        "kelo/pixabay_i_7783664.jpg",
        "kelo/pixabay_i_2666433.jpg"
      ]
    },
    {
      "spanId": "SPN-0002",
      "chapterId": "opening",
      "seconds": 40.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_house_for_sale.jpg",
      "telop": [
        "5th Amendment: takings only \"for public use\""
      ],
      "priority": "A",
      "images": [
        "kelo/pexels_house_for_sale.jpg",
        "kelo/pexels_i_15263342.jpg",
        "kelo/pexels_i_19378121.jpg",
        "kelo/pexels_i_37900459.jpg",
        "kelo/pixabay_i_7783664.jpg",
        "kelo/pixabay_i_2666433.jpg",
        "kelo/pixabay_i_1869914.jpg"
      ]
    },
    {
      "spanId": "SPN-0003",
      "chapterId": "act1",
      "seconds": 13.6,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pexels_v_17362431.mp4",
      "telop": [
        "Fort Trumbull, New London, CT"
      ],
      "priority": "B",
      "clips": [
        {
          "src": "kelo/pexels_v_17362431.mp4",
          "clipSeconds": 20.12
        },
        {
          "src": "kelo/pexels_v_3858852.mp4",
          "clipSeconds": 35.18
        },
        {
          "src": "kelo/pexels_v_3859473.mp4",
          "clipSeconds": 28.01
        },
        {
          "src": "kelo/pexels_v_37978559.mp4",
          "clipSeconds": 31.24
        },
        {
          "src": "kelo/pixabay_v_166289.mp4",
          "clipSeconds": 20.07
        }
      ]
    },
    {
      "spanId": "SPN-0004",
      "chapterId": "act1",
      "seconds": 19.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_4389714.jpg",
      "telop": [
        "Not blighted. Owner did nothing wrong."
      ],
      "priority": "B",
      "images": [
        "kelo/pexels_i_4389714.jpg",
        "kelo/pexels_i_3961748.jpg",
        "kelo/pexels_i_16553771.jpg",
        "kelo/pixabay_i_2047596.jpg"
      ]
    },
    {
      "spanId": "SPN-0005",
      "chapterId": "act1",
      "seconds": 18.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_20270908.jpg",
      "telop": [
        "The plan: offices, hotel, jobs, taxes"
      ],
      "priority": "C",
      "images": [
        "kelo/pexels_i_20270908.jpg",
        "kelo/pexels_i_37097738.jpg",
        "kelo/pexels_i_3845102.jpg",
        "kelo/pexels_i_4389714.jpg"
      ]
    },
    {
      "spanId": "SPN-0006",
      "chapterId": "act1",
      "seconds": 21.6,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pexels_v_31008269.mp4",
      "telop": [],
      "priority": "A",
      "clips": [
        {
          "src": "kelo/pexels_v_31008269.mp4",
          "clipSeconds": 9.68
        },
        {
          "src": "kelo/pexels_v_2801656.mp4",
          "clipSeconds": 47.32
        }
      ]
    },
    {
      "spanId": "SPN-0007",
      "chapterId": "act1",
      "seconds": 24.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_3961748.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "kelo/pexels_i_3961748.jpg",
        "kelo/pexels_i_16553771.jpg",
        "kelo/pixabay_i_2047596.jpg",
        "kelo/pixabay_i_1839623.jpg",
        "kelo/pixabay_i_6706970.jpg"
      ]
    },
    {
      "spanId": "SPN-0008",
      "chapterId": "act1",
      "seconds": 20.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_37738120.jpg",
      "telop": [
        "Is that \"public use\"?"
      ],
      "priority": "C",
      "images": [
        "kelo/pexels_i_37738120.jpg",
        "kelo/pexels_i_17602526.jpg",
        "kelo/pexels_i_33043393.jpg",
        "kelo/pixabay_i_6538926.jpg"
      ]
    },
    {
      "spanId": "SPN-0009",
      "chapterId": "act2",
      "seconds": 28.0,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pexels_v_5362813.mp4",
      "telop": [
        "Narrow: the public actually uses it"
      ],
      "priority": "C",
      "clips": [
        {
          "src": "kelo/pexels_v_5362813.mp4",
          "clipSeconds": 6.72
        },
        {
          "src": "kelo/pixabay_v_78804.mp4",
          "clipSeconds": 20.0
        }
      ]
    },
    {
      "spanId": "SPN-0010",
      "chapterId": "act2",
      "seconds": 21.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pixabay_i_1834446.jpg",
      "telop": [
        "Broad: any \"public purpose\""
      ],
      "priority": "C",
      "images": [
        "kelo/pixabay_i_1834446.jpg",
        "kelo/pixabay_i_565914.jpg",
        "kelo/scotus_gavel.jpg",
        "kelo/us_constitution_p1.jpg"
      ]
    },
    {
      "spanId": "SPN-0011",
      "chapterId": "act2",
      "seconds": 16.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_3890028.jpg",
      "telop": [
        "City: economic development = public use"
      ],
      "priority": "C",
      "images": [
        "kelo/pexels_i_3890028.jpg",
        "kelo/pexels_i_19841146.jpg",
        "kelo/pixabay_i_4132144.jpg"
      ]
    },
    {
      "spanId": "SPN-0012",
      "chapterId": "act2",
      "seconds": 26.0,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pixabay_v_85109.mp4",
      "telop": [],
      "priority": "C",
      "clips": [
        {
          "src": "kelo/pixabay_v_85109.mp4",
          "clipSeconds": 20.89
        },
        {
          "src": "kelo/pixabay_v_16166.mp4",
          "clipSeconds": 8.17
        }
      ]
    },
    {
      "spanId": "SPN-0013",
      "chapterId": "act2",
      "seconds": 13.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/bill_of_rights.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "kelo/bill_of_rights.jpg",
        "kelo/us_dollar_bill.jpg",
        "kelo/rbg_scotus_portrait.jpg"
      ]
    },
    {
      "spanId": "SPN-0014",
      "chapterId": "act3",
      "seconds": 15.2,
      "assetType": "motion_graphic",
      "motion": "graphic_anim",
      "src": "kelo/oyez_kelo_2005.mp3",
      "telop": [
        "2005 — 5–4",
        "Kelo v. New London, 545 U.S. 469"
      ],
      "priority": "A",
      "images": [
        "kelo/oyez_kelo_2005.mp3",
        "kelo/roberts_scotus_portrait.jpg",
        "kelo/pexels_smartphone_hand.jpg"
      ]
    },
    {
      "spanId": "SPN-0015",
      "chapterId": "act3",
      "seconds": 27.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_money_handover.jpg",
      "telop": [
        "\"Public use\" = \"public purpose\""
      ],
      "priority": "A",
      "images": [
        "kelo/pexels_money_handover.jpg",
        "kelo/pexels_tow_truck.jpg",
        "kelo/pexels_house_for_sale.jpg",
        "kelo/pexels_signing_contract.jpg",
        "kelo/pexels_police_car.jpg"
      ]
    },
    {
      "spanId": "SPN-0016",
      "chapterId": "act3",
      "seconds": 39.6,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pexels_v_17362431.mp4",
      "telop": [
        "Dissent (O'Connor): \"for public use\" — erased?"
      ],
      "priority": "A",
      "clips": [
        {
          "src": "kelo/pexels_v_17362431.mp4",
          "clipSeconds": 20.12
        },
        {
          "src": "kelo/pexels_v_3858852.mp4",
          "clipSeconds": 35.18
        }
      ]
    },
    {
      "spanId": "SPN-0017",
      "chapterId": "act3",
      "seconds": 19.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_14766052.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "kelo/pexels_i_14766052.jpg",
        "kelo/pexels_i_37730973.jpg",
        "kelo/pixabay_i_3194994.jpg",
        "kelo/pexels_i_6077447.jpg"
      ]
    },
    {
      "spanId": "SPN-0018",
      "chapterId": "act4",
      "seconds": 18.4,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_37732186.jpg",
      "telop": [
        "Backlash: bipartisan"
      ],
      "priority": "C",
      "images": [
        "kelo/pexels_i_37732186.jpg",
        "kelo/pixabay_i_2492011.jpg",
        "kelo/pixabay_i_6808677.jpg",
        "kelo/pexels_i_36984943.jpg"
      ]
    },
    {
      "spanId": "SPN-0019",
      "chapterId": "act4",
      "seconds": 29.2,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pexels_v_3859473.mp4",
      "telop": [
        "~40+ states reformed (many criticized as weak)"
      ],
      "priority": "C",
      "clips": [
        {
          "src": "kelo/pexels_v_3859473.mp4",
          "clipSeconds": 28.01
        },
        {
          "src": "kelo/pexels_v_8206441.mp4",
          "clipSeconds": 28.32
        }
      ]
    },
    {
      "spanId": "SPN-0020",
      "chapterId": "act4",
      "seconds": 19.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pexels_i_37738120.jpg",
      "telop": [
        "The development was never built."
      ],
      "priority": "B",
      "images": [
        "kelo/pexels_i_37738120.jpg",
        "kelo/pexels_i_17602526.jpg",
        "kelo/pexels_i_33043393.jpg",
        "kelo/pixabay_i_6538926.jpg"
      ]
    },
    {
      "spanId": "SPN-0021",
      "chapterId": "act4",
      "seconds": 24.8,
      "assetType": "motion_graphic",
      "motion": "graphic_anim",
      "src": "kelo/pexels_i_36984938.jpg",
      "telop": [
        "2009: Pfizer leaves New London"
      ],
      "priority": "C",
      "images": [
        "kelo/pexels_i_36984938.jpg",
        "kelo/pixabay_i_2225765.jpg",
        "kelo/pixabay_i_2225766.jpg",
        "kelo/pexels_i_159720.jpg",
        "kelo/pexels_i_37726703.jpg"
      ]
    },
    {
      "spanId": "SPN-0022",
      "chapterId": "act4",
      "seconds": 18.4,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pixabay_i_1839623.jpg",
      "telop": [
        "The pink house was moved, not destroyed"
      ],
      "priority": "C",
      "images": [
        "kelo/pixabay_i_1839623.jpg",
        "kelo/pixabay_i_6706970.jpg",
        "kelo/pixabay_i_1869914.jpg",
        "kelo/pexels_i_164558.jpg"
      ]
    },
    {
      "spanId": "SPN-0023",
      "chapterId": "ending",
      "seconds": 16.4,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pexels_v_36212672.mp4",
      "telop": [],
      "priority": "C",
      "clips": [
        {
          "src": "kelo/pexels_v_36212672.mp4",
          "clipSeconds": 6.34
        },
        {
          "src": "kelo/pexels_v_8206435.mp4",
          "clipSeconds": 66.0
        }
      ]
    },
    {
      "spanId": "SPN-0024",
      "chapterId": "ending",
      "seconds": 17.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pixabay_i_923898.jpg",
      "telop": [],
      "priority": "A",
      "images": [
        "kelo/pixabay_i_923898.jpg",
        "kelo/pixabay_i_3324024.jpg",
        "kelo/pexels_i_6077797.jpg"
      ]
    },
    {
      "spanId": "SPN-0025",
      "chapterId": "ending",
      "seconds": 36.4,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pixabay_i_1834446.jpg",
      "telop": [
        "Next: where does free speech end?"
      ],
      "priority": "A",
      "images": [
        "kelo/pixabay_i_1834446.jpg",
        "kelo/pixabay_i_565914.jpg",
        "kelo/pexels_i_30483132.jpg",
        "kelo/pixabay_i_677940.jpg",
        "kelo/pixabay_i_677945.jpg",
        "kelo/pexels_i_7483195.jpg",
        "kelo/pexels_i_7649100.jpg"
      ]
    },
    {
      "spanId": "SPN-0026",
      "chapterId": "ending",
      "seconds": 1.6,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "kelo/pixabay_v_230060.mp4",
      "telop": [
        "Subscribe"
      ],
      "priority": "C",
      "clips": [
        {
          "src": "kelo/pixabay_v_230060.mp4",
          "clipSeconds": 45.12
        },
        {
          "src": "kelo/pixabay_v_34573.mp4",
          "clipSeconds": 9.01
        }
      ]
    },
    {
      "spanId": "SPN-0027",
      "chapterId": "act3",
      "seconds": 19.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pixabay_i_2636065.jpg",
      "telop": [
        "Kennedy: pretextual takings still barred"
      ],
      "priority": "A",
      "images": [
        "kelo/pixabay_i_2636065.jpg",
        "kelo/pixabay_i_2578873.jpg",
        "kelo/pexels_i_20417783.jpg",
        "kelo/pexels_i_19574309.jpg"
      ]
    },
    {
      "spanId": "SPN-0028",
      "chapterId": "act4",
      "seconds": 31.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "kelo/pixabay_i_826993.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "kelo/pixabay_i_826993.jpg",
        "kelo/pixabay_i_477987.jpg",
        "kelo/pexels_i_8850753.jpg",
        "kelo/pexels_i_51343.jpg",
        "kelo/pixabay_i_3212015.jpg",
        "kelo/pixabay_i_623167.jpg"
      ]
    }
  ]
};
