// AUTO-GENERATED by scripts/import_to_remotion.py from PD-2026-011-mahanoy/04_scenes/shotlist.v001.json
// + 05_stock/usable_assets.v001.json. Do NOT edit by hand; re-run the importer.
import type {RoughCutData} from '../compositions/RoughCut';

export const MAHANOY_ROUGHCUT: RoughCutData = {
  "episodeId": "PD-2026-011-mahanoy",
  "title": "Can Your School Punish You for a Post You Made Off Campus?",
  "fps": 30,
  "narrationSrc": null,
  "bgmSrc": null,
  "shots": [
    {
      "spanId": "SPN-0001",
      "chapterId": "hook",
      "seconds": 29.2,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "mahanoy/pixabay_v_202987.mp4",
      "telop": [
        "Can your school punish your weekend post?"
      ],
      "priority": "A",
      "clips": [
        {
          "src": "mahanoy/pixabay_v_202987.mp4",
          "clipSeconds": 15.06
        },
        {
          "src": "mahanoy/pixabay_v_47743.mp4",
          "clipSeconds": 6.97
        }
      ]
    },
    {
      "spanId": "SPN-0002",
      "chapterId": "opening",
      "seconds": 41.6,
      "assetType": "motion_graphic",
      "motion": "graphic_anim",
      "src": "mahanoy/pexels_i_694424.jpg",
      "telop": [
        "\"...at the schoolhouse gate\" — Tinker, 1969"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pexels_i_694424.jpg",
        "mahanoy/pexels_i_7821755.jpg",
        "mahanoy/pixabay_i_1869510.jpg",
        "mahanoy/pixabay_i_1851218.jpg",
        "mahanoy/pexels_i_13872497.jpg",
        "mahanoy/pexels_i_34612562.jpg",
        "mahanoy/pixabay_i_7335258.jpg"
      ]
    },
    {
      "spanId": "SPN-0003",
      "chapterId": "act1",
      "seconds": 10.4,
      "assetType": "motion_graphic",
      "motion": "graphic_anim",
      "src": "mahanoy/pixabay_i_3387324.jpg",
      "telop": [
        "Mahanoy, PA — 2017"
      ],
      "priority": "B",
      "images": [
        "mahanoy/pixabay_i_3387324.jpg",
        "mahanoy/pixabay_i_824419.jpg"
      ]
    },
    {
      "spanId": "SPN-0004",
      "chapterId": "act1",
      "seconds": 14.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_29659894.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_29659894.jpg",
        "mahanoy/pexels_i_8419261.jpg",
        "mahanoy/pixabay_i_993886.jpg"
      ]
    },
    {
      "spanId": "SPN-0005",
      "chapterId": "act1",
      "seconds": 30.0,
      "assetType": "stock_video",
      "motion": "video_native",
      "src": "mahanoy/pexels_v_37627304.mp4",
      "telop": [
        "[caption censored]"
      ],
      "priority": "B",
      "clips": [
        {
          "src": "mahanoy/pexels_v_37627304.mp4",
          "clipSeconds": 6.3
        },
        {
          "src": "mahanoy/pexels_v_9465320.mp4",
          "clipSeconds": 6.0
        },
        {
          "src": "mahanoy/pixabay_v_171085.mp4",
          "clipSeconds": 44.04
        },
        {
          "src": "mahanoy/pixabay_v_73847.mp4",
          "clipSeconds": 14.48
        }
      ]
    },
    {
      "spanId": "SPN-0006",
      "chapterId": "act1",
      "seconds": 22.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pixabay_i_7718642.jpg",
      "telop": [
        "Snaps \"disappear\" — screenshots don't"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pixabay_i_7718642.jpg",
        "mahanoy/pexels_i_6958629.jpg",
        "mahanoy/pexels_i_6255934.jpg",
        "mahanoy/pixabay_i_1822438.jpg"
      ]
    },
    {
      "spanId": "SPN-0007",
      "chapterId": "act1",
      "seconds": 12.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pixabay_i_1687949.jpg",
      "telop": [
        "Suspended from JV cheer — 1 year"
      ],
      "priority": "C",
      "images": [
        "mahanoy/pixabay_i_1687949.jpg",
        "mahanoy/pexels_i_16229745.jpg",
        "mahanoy/pexels_i_7634159.jpg"
      ]
    },
    {
      "spanId": "SPN-0008",
      "chapterId": "act1",
      "seconds": 25.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_29659894.jpg",
      "telop": [
        "School's order vs. a student's voice"
      ],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_29659894.jpg",
        "mahanoy/pexels_i_8419261.jpg",
        "mahanoy/pixabay_i_993886.jpg",
        "mahanoy/pixabay_i_7718642.jpg",
        "mahanoy/pexels_i_8456146.jpg"
      ]
    },
    {
      "spanId": "SPN-0009",
      "chapterId": "act2",
      "seconds": 15.6,
      "assetType": "motion_graphic",
      "motion": "graphic_anim",
      "src": "mahanoy/pixabay_i_763731.jpg",
      "telop": [
        "Tinker v. Des Moines (1969)"
      ],
      "priority": "C",
      "images": [
        "mahanoy/pixabay_i_763731.jpg",
        "mahanoy/pixabay_i_3113279.jpg",
        "mahanoy/pexels_i_15452110.jpg"
      ]
    },
    {
      "spanId": "SPN-0010",
      "chapterId": "act2",
      "seconds": 19.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_15452106.jpg",
      "telop": [
        "Test: \"substantial disruption\""
      ],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_15452106.jpg",
        "mahanoy/pixabay_i_6367607.jpg",
        "mahanoy/pixabay_i_4257401.jpg",
        "mahanoy/pexels_i_8456146.jpg"
      ]
    },
    {
      "spanId": "SPN-0011",
      "chapterId": "act2",
      "seconds": 12.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_32292156.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_32292156.jpg",
        "mahanoy/pixabay_i_94959.jpg",
        "mahanoy/pixabay_i_728344.jpg"
      ]
    },
    {
      "spanId": "SPN-0012",
      "chapterId": "act2",
      "seconds": 27.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_694424.jpg",
      "telop": [
        "The phone erased the gate"
      ],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_694424.jpg",
        "mahanoy/pexels_i_7821755.jpg",
        "mahanoy/pixabay_i_1869510.jpg",
        "mahanoy/pixabay_i_1851218.jpg",
        "mahanoy/pexels_i_16229745.jpg"
      ]
    },
    {
      "spanId": "SPN-0013",
      "chapterId": "act2",
      "seconds": 25.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_9654894.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_9654894.jpg",
        "mahanoy/pexels_i_10127242.jpg",
        "mahanoy/pixabay_i_5458722.jpg",
        "mahanoy/pixabay_i_3354784.jpg",
        "mahanoy/pexels_i_694424.jpg"
      ]
    },
    {
      "spanId": "SPN-0014",
      "chapterId": "act3",
      "seconds": 14.0,
      "assetType": "motion_graphic",
      "motion": "graphic_anim",
      "src": "mahanoy/pexels_i_7821755.jpg",
      "telop": [
        "2021 — 8–1",
        "Mahanoy v. B.L., 594 U.S. 180"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pexels_i_7821755.jpg",
        "mahanoy/pixabay_i_1869510.jpg",
        "mahanoy/pixabay_i_1851218.jpg"
      ]
    },
    {
      "spanId": "SPN-0015",
      "chapterId": "act3",
      "seconds": 27.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_13872497.jpg",
      "telop": [],
      "priority": "A",
      "images": [
        "mahanoy/pexels_i_13872497.jpg",
        "mahanoy/pexels_i_34612562.jpg",
        "mahanoy/pixabay_i_7335258.jpg",
        "mahanoy/pixabay_i_3387324.jpg",
        "mahanoy/pixabay_i_824419.jpg"
      ]
    },
    {
      "spanId": "SPN-0016",
      "chapterId": "act3",
      "seconds": 16.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_29659894.jpg",
      "telop": [
        "Disruption: a few minutes of class chatter"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pexels_i_29659894.jpg",
        "mahanoy/pexels_i_8419261.jpg",
        "mahanoy/pixabay_i_993886.jpg"
      ]
    },
    {
      "spanId": "SPN-0017",
      "chapterId": "act3",
      "seconds": 29.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pixabay_i_7718642.jpg",
      "telop": [
        "Still reachable: bullying · threats · cheating"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pixabay_i_7718642.jpg",
        "mahanoy/pexels_i_6958629.jpg",
        "mahanoy/pexels_i_6255934.jpg",
        "mahanoy/pixabay_i_1822438.jpg",
        "mahanoy/pixabay_i_1687949.jpg"
      ]
    },
    {
      "spanId": "SPN-0018",
      "chapterId": "act3",
      "seconds": 27.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_16229745.jpg",
      "telop": [
        "Dissent: Thomas, J. (alone)"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pexels_i_16229745.jpg",
        "mahanoy/pexels_i_7634159.jpg",
        "mahanoy/pixabay_i_763731.jpg",
        "mahanoy/pixabay_i_3113279.jpg",
        "mahanoy/pexels_i_15452110.jpg"
      ]
    },
    {
      "spanId": "SPN-0019",
      "chapterId": "act4",
      "seconds": 20.0,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_15452106.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_15452106.jpg",
        "mahanoy/pixabay_i_6367607.jpg",
        "mahanoy/pixabay_i_4257401.jpg",
        "mahanoy/pexels_i_8456146.jpg"
      ]
    },
    {
      "spanId": "SPN-0020",
      "chapterId": "act4",
      "seconds": 20.4,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_32292156.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_32292156.jpg",
        "mahanoy/pixabay_i_94959.jpg",
        "mahanoy/pixabay_i_728344.jpg",
        "mahanoy/pexels_i_9654894.jpg"
      ]
    },
    {
      "spanId": "SPN-0021",
      "chapterId": "act4",
      "seconds": 24.8,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_10127242.jpg",
      "telop": [
        "Free speech is tested by speech we dislike"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pexels_i_10127242.jpg",
        "mahanoy/pixabay_i_5458722.jpg",
        "mahanoy/pixabay_i_3354784.jpg",
        "mahanoy/pexels_i_694424.jpg",
        "mahanoy/pexels_i_7821755.jpg"
      ]
    },
    {
      "spanId": "SPN-0022",
      "chapterId": "ending",
      "seconds": 19.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pixabay_i_1869510.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "mahanoy/pixabay_i_1869510.jpg",
        "mahanoy/pixabay_i_1851218.jpg",
        "mahanoy/pexels_i_13872497.jpg",
        "mahanoy/pexels_i_34612562.jpg"
      ]
    },
    {
      "spanId": "SPN-0023",
      "chapterId": "ending",
      "seconds": 32.0,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pixabay_i_7335258.jpg",
      "telop": [],
      "priority": "A",
      "images": [
        "mahanoy/pixabay_i_7335258.jpg",
        "mahanoy/pixabay_i_3387324.jpg",
        "mahanoy/pixabay_i_824419.jpg",
        "mahanoy/pexels_i_29659894.jpg",
        "mahanoy/pexels_i_8419261.jpg",
        "mahanoy/pixabay_i_993886.jpg"
      ]
    },
    {
      "spanId": "SPN-0024",
      "chapterId": "ending",
      "seconds": 23.2,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pixabay_i_7718642.jpg",
      "telop": [
        "Next: the right you sign away"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pixabay_i_7718642.jpg",
        "mahanoy/pexels_i_6958629.jpg",
        "mahanoy/pexels_i_6255934.jpg",
        "mahanoy/pixabay_i_1822438.jpg"
      ]
    },
    {
      "spanId": "SPN-0025",
      "chapterId": "ending",
      "seconds": 1.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pixabay_i_1687949.jpg",
      "telop": [
        "Subscribe"
      ],
      "priority": "C",
      "images": [
        "mahanoy/pixabay_i_1687949.jpg"
      ]
    },
    {
      "spanId": "SPN-0026",
      "chapterId": "act2",
      "seconds": 21.6,
      "assetType": "motion_graphic",
      "motion": "graphic_anim",
      "src": "mahanoy/pexels_i_16229745.jpg",
      "telop": [
        "1965: armbands to mourn the war dead"
      ],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_16229745.jpg",
        "mahanoy/pexels_i_7634159.jpg",
        "mahanoy/pixabay_i_763731.jpg",
        "mahanoy/pixabay_i_3113279.jpg"
      ]
    },
    {
      "spanId": "SPN-0027",
      "chapterId": "act3",
      "seconds": 22.4,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_15452110.jpg",
      "telop": [
        "\"nurseries of democracy\" — Breyer"
      ],
      "priority": "A",
      "images": [
        "mahanoy/pexels_i_15452110.jpg",
        "mahanoy/pexels_i_15452106.jpg",
        "mahanoy/pixabay_i_6367607.jpg",
        "mahanoy/pixabay_i_4257401.jpg"
      ]
    },
    {
      "spanId": "SPN-0028",
      "chapterId": "act1",
      "seconds": 17.6,
      "assetType": "ai_image",
      "motion": "ken_burns",
      "src": "mahanoy/pexels_i_8456146.jpg",
      "telop": [],
      "priority": "C",
      "images": [
        "mahanoy/pexels_i_8456146.jpg",
        "mahanoy/pexels_i_32292156.jpg",
        "mahanoy/pixabay_i_94959.jpg"
      ]
    }
  ]
};
