// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #66.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT66_TOTAL_SEC = 52.061;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 7.796
  },
  {
    "id": "L2",
    "start": 8.516,
    "end": 20.587
  },
  {
    "id": "L3",
    "start": 21.307,
    "end": 32.26
  },
  {
    "id": "L4",
    "start": 32.98,
    "end": 42.678
  },
  {
    "id": "L5",
    "start": 43.398,
    "end": 51.061
  }
];

export const SHORT66_CAPTIONS: ShortCaption[] = [
  {
    "word": "In February of 1982",
    "startSec": 0.0,
    "endSec": 1.245
  },
  {
    "word": "a doctor at the Cook County Jail",
    "startSec": 1.245,
    "endSec": 3.341
  },
  {
    "word": "examined a new prisoner and found injuries",
    "startSec": 3.341,
    "endSec": 6.093
  },
  {
    "word": "he could not explain away.",
    "startSec": 6.093,
    "endSec": 7.796
  },
  {
    "word": "So the doctor did what doctors are",
    "startSec": 8.516,
    "endSec": 10.699
  },
  {
    "word": "supposed to do.",
    "startSec": 10.699,
    "endSec": 11.662
  },
  {
    "word": "He wrote a letter to the superintendent",
    "startSec": 11.662,
    "endSec": 14.166
  },
  {
    "word": "of the Chicago Police Department",
    "startSec": 14.166,
    "endSec": 16.221
  },
  {
    "word": "describing the injuries demanding his words",
    "startSec": 16.221,
    "endSec": 18.982
  },
  {
    "word": "a thorough investigation.",
    "startSec": 18.982,
    "endSec": 20.587
  },
  {
    "word": "That letter went up the chain of command",
    "startSec": 21.307,
    "endSec": 24.152
  },
  {
    "word": "landed on the desk of one of",
    "startSec": 24.152,
    "endSec": 26.143
  },
  {
    "word": "the most powerful men in Illinois",
    "startSec": 26.143,
    "endSec": 28.49
  },
  {
    "word": "and died there. No answer. No investigation. Nothing.",
    "startSec": 28.49,
    "endSec": 32.26
  },
  {
    "word": "For five weeks",
    "startSec": 32.98,
    "endSec": 33.993
  },
  {
    "word": "a federal courtroom heard everything the statute",
    "startSec": 33.993,
    "endSec": 37.467
  },
  {
    "word": "of limitations had buried. Melvin Jones.",
    "startSec": 37.467,
    "endSec": 40.362
  },
  {
    "word": "The medical records. The letter.",
    "startSec": 40.362,
    "endSec": 42.678
  },
  {
    "word": "He was never charged with torture",
    "startSec": 43.398,
    "endSec": 45.314
  },
  {
    "word": "only with lying about it.",
    "startSec": 45.314,
    "endSec": 46.765
  },
  {
    "word": "The full case is on the channel.",
    "startSec": 46.765,
    "endSec": 48.623
  },
  {
    "word": "Follow for the cases they don't teach you.",
    "startSec": 48.623,
    "endSec": 51.061
  }
];
