// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #114.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT114_TOTAL_SEC = 41.168;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 4.923
  },
  {
    "id": "L2",
    "start": 5.143,
    "end": 16.149
  },
  {
    "id": "L3",
    "start": 16.369,
    "end": 25.146
  },
  {
    "id": "L4",
    "start": 25.366,
    "end": 33.957
  },
  {
    "id": "L5",
    "start": 34.177,
    "end": 40.168
  }
];

export const SHORT114_CAPTIONS: ShortCaption[] = [
  {
    "word": "Carpenter won five to four.",
    "startSec": 0.0,
    "endSec": 1.429
  },
  {
    "word": "The four who lost thought the",
    "startSec": 1.429,
    "endSec": 2.964
  },
  {
    "word": "Court had just made everything worse.",
    "startSec": 2.964,
    "endSec": 4.923
  },
  {
    "word": "The majority did not throw",
    "startSec": 5.143,
    "endSec": 6.797
  },
  {
    "word": "out the old rule.",
    "startSec": 6.797,
    "endSec": 7.879
  },
  {
    "word": "It refused to extend it.",
    "startSec": 7.879,
    "endSec": 9.405
  },
  {
    "word": "Location records were different Roberts wrote.",
    "startSec": 9.405,
    "endSec": 12.332
  },
  {
    "word": "A comprehensive",
    "startSec": 12.332,
    "endSec": 13.286
  },
  {
    "word": "effortless chronicle of a person's movements.",
    "startSec": 13.286,
    "endSec": 16.149
  },
  {
    "word": "The dissenters warned the Court had opened",
    "startSec": 16.369,
    "endSec": 18.894
  },
  {
    "word": "a door it could not close.",
    "startSec": 18.894,
    "endSec": 20.457
  },
  {
    "word": "How much data is too much?",
    "startSec": 20.457,
    "endSec": 22.02
  },
  {
    "word": "They said it had traded a",
    "startSec": 22.02,
    "endSec": 23.523
  },
  {
    "word": "clear rule for a vague one.",
    "startSec": 23.523,
    "endSec": 25.146
  },
  {
    "word": "And they had a point.",
    "startSec": 25.366,
    "endSec": 26.664
  },
  {
    "word": "A clear rule tells police",
    "startSec": 26.664,
    "endSec": 28.209
  },
  {
    "word": "exactly what they may do.",
    "startSec": 28.209,
    "endSec": 29.754
  },
  {
    "word": "A blurry line invites years of new",
    "startSec": 29.754,
    "endSec": 31.856
  },
  {
    "word": "cases just to find where it falls.",
    "startSec": 31.856,
    "endSec": 33.957
  },
  {
    "word": "Nobody on that Court thought",
    "startSec": 34.177,
    "endSec": 35.79
  },
  {
    "word": "the answer was easy.",
    "startSec": 35.79,
    "endSec": 36.942
  },
  {
    "word": "The margin says so",
    "startSec": 36.942,
    "endSec": 37.979
  },
  {
    "word": "and so does what the dissenters wrote.",
    "startSec": 37.979,
    "endSec": 40.168
  }
];
