// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #139.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT139_TOTAL_SEC = 59.753;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.548
  },
  {
    "id": "L2",
    "start": 6.768,
    "end": 15.545
  },
  {
    "id": "L3",
    "start": 15.765,
    "end": 21.431
  },
  {
    "id": "L4",
    "start": 21.651,
    "end": 30.846
  },
  {
    "id": "L5",
    "start": 31.066,
    "end": 37.196
  },
  {
    "id": "L6",
    "start": 37.416,
    "end": 44.614
  },
  {
    "id": "L7",
    "start": 44.834,
    "end": 52.589
  },
  {
    "id": "L8",
    "start": 52.809,
    "end": 58.753
  }
];

export const SHORT139_CAPTIONS: ShortCaption[] = [
  {
    "word": "A federal court let officers press a",
    "startSec": 0.0,
    "endSec": 2.05
  },
  {
    "word": "man's own thumb to his phone.",
    "startSec": 2.05,
    "endSec": 3.701
  },
  {
    "word": "Then it added a line",
    "startSec": 3.701,
    "endSec": 4.84
  },
  {
    "word": "that undoes almost everything.",
    "startSec": 4.84,
    "endSec": 6.548
  },
  {
    "word": "In 2024 the Ninth Circuit said pressing",
    "startSec": 6.768,
    "endSec": 8.976
  },
  {
    "word": "a thumb takes no thought at all.",
    "startSec": 8.976,
    "endSec": 10.788
  },
  {
    "word": "His body opened the door against him",
    "startSec": 10.788,
    "endSec": 12.827
  },
  {
    "word": "and the Constitution had nothing",
    "startSec": 12.827,
    "endSec": 14.639
  },
  {
    "word": "to say about it.",
    "startSec": 14.639,
    "endSec": 15.545
  },
  {
    "word": "But the court hinted the answer",
    "startSec": 15.765,
    "endSec": 17.292
  },
  {
    "word": "might have been different if the",
    "startSec": 17.292,
    "endSec": 18.869
  },
  {
    "word": "officers had made the man choose",
    "startSec": 18.869,
    "endSec": 20.446
  },
  {
    "word": "which finger to use.",
    "startSec": 20.446,
    "endSec": 21.431
  },
  {
    "word": "Because choosing is a decision",
    "startSec": 21.651,
    "endSec": 23.65
  },
  {
    "word": "and a decision happens in your mind.",
    "startSec": 23.65,
    "endSec": 26.049
  },
  {
    "word": "Same thumb.",
    "startSec": 26.049,
    "endSec": 26.782
  },
  {
    "word": "No protection if they press it.",
    "startSec": 26.782,
    "endSec": 28.847
  },
  {
    "word": "Maybe protected if you decide.",
    "startSec": 28.847,
    "endSec": 30.846
  },
  {
    "word": "The courts' picture is a safe.",
    "startSec": 31.066,
    "endSec": 32.817
  },
  {
    "word": "They can force you to",
    "startSec": 32.817,
    "endSec": 34.043
  },
  {
    "word": "hand over the key",
    "startSec": 34.043,
    "endSec": 35.036
  },
  {
    "word": "but not to tell them the combination.",
    "startSec": 35.036,
    "endSec": 37.196
  },
  {
    "word": "A passcode is a combination",
    "startSec": 37.416,
    "endSec": 39.285
  },
  {
    "word": "a string of numbers that exists",
    "startSec": 39.285,
    "endSec": 41.43
  },
  {
    "word": "nowhere but inside your memory.",
    "startSec": 41.43,
    "endSec": 43.576
  },
  {
    "word": "A thumb is not.",
    "startSec": 43.576,
    "endSec": 44.614
  },
  {
    "word": "In 2025 the D.C.",
    "startSec": 44.834,
    "endSec": 45.868
  },
  {
    "word": "Circuit ruled the opposite:",
    "startSec": 45.868,
    "endSec": 47.613
  },
  {
    "word": "obeying that command admits",
    "startSec": 47.613,
    "endSec": 49.358
  },
  {
    "word": "the phone is yours",
    "startSec": 49.358,
    "endSec": 50.521
  },
  {
    "word": "and that you know",
    "startSec": 50.521,
    "endSec": 51.62
  },
  {
    "word": "how to open it.",
    "startSec": 51.62,
    "endSec": 52.589
  },
  {
    "word": "So what protects you is not",
    "startSec": 52.809,
    "endSec": 54.43
  },
  {
    "word": "the lock on the phone.",
    "startSec": 54.43,
    "endSec": 55.751
  },
  {
    "word": "It is whether the choice to",
    "startSec": 55.751,
    "endSec": 57.372
  },
  {
    "word": "open it was ever yours.",
    "startSec": 57.372,
    "endSec": 58.753
  }
];
