// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #107.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT107_TOTAL_SEC = 30.905;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.641
  },
  {
    "id": "L2",
    "start": 6.861,
    "end": 12.248
  },
  {
    "id": "L3",
    "start": 12.468,
    "end": 16.137
  },
  {
    "id": "L4",
    "start": 16.357,
    "end": 23.091
  },
  {
    "id": "L5",
    "start": 23.311,
    "end": 29.905
  }
];

export const SHORT107_CAPTIONS: ShortCaption[] = [
  {
    "word": "She forced herself to memorise",
    "startSec": 0.0,
    "endSec": 1.845
  },
  {
    "word": "his face during the attack",
    "startSec": 1.845,
    "endSec": 3.443
  },
  {
    "word": "so she could be sure.",
    "startSec": 3.443,
    "endSec": 4.735
  },
  {
    "word": "It is the reason she was wrong.",
    "startSec": 4.735,
    "endSec": 6.641
  },
  {
    "word": "None of this was a trick",
    "startSec": 6.861,
    "endSec": 8.208
  },
  {
    "word": "played on a foolish woman.",
    "startSec": 8.208,
    "endSec": 9.667
  },
  {
    "word": "She did everything a witness",
    "startSec": 9.667,
    "endSec": 11.238
  },
  {
    "word": "is supposed to do.",
    "startSec": 11.238,
    "endSec": 12.248
  },
  {
    "word": "The problem was never that Jennifer",
    "startSec": 12.468,
    "endSec": 14.385
  },
  {
    "word": "Thompson was not certain enough.",
    "startSec": 14.385,
    "endSec": 16.137
  },
  {
    "word": "She has spent years now saying it",
    "startSec": 16.357,
    "endSec": 18.256
  },
  {
    "word": "out loud so nobody can miss it.",
    "startSec": 18.256,
    "endSec": 20.041
  },
  {
    "word": "Memory can be honest and confident",
    "startSec": 20.041,
    "endSec": 21.997
  },
  {
    "word": "and still be wrong.",
    "startSec": 21.997,
    "endSec": 23.091
  },
  {
    "word": "So ask how an honest",
    "startSec": 23.311,
    "endSec": 24.468
  },
  {
    "word": "witness ends up wrong.",
    "startSec": 24.468,
    "endSec": 25.74
  },
  {
    "word": "The answer starts with the",
    "startSec": 25.74,
    "endSec": 27.244
  },
  {
    "word": "one thing she did to",
    "startSec": 27.244,
    "endSec": 28.401
  },
  {
    "word": "make sure she never would.",
    "startSec": 28.401,
    "endSec": 29.905
  }
];
