import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT87_CAPTIONS, SHORT87_TOTAL_SEC} from './short87_timing';

/**
 * short87 — It happened in the seam between everyone's rules and no one's.
 * Episode PD-2026-016-titan.  Type A — the gap that applies to you too.
 *
 * AVOIDS: short16's beats are the countdown, the warnings and the controller. Jurisdiction is untouched there.
 * LEAVES FOR THE LONG-FORM: If no regulator had authority, who was ever supposed to say no?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-016-titan.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short87/short87_01.png', kind: 'image', motion: 'parallax', fast: true},   // a certification stamp that was never brought down
  {line: 'L1', id: 'p02', src: 'shorts/short87/short87_02.png', kind: 'image', motion: 'kenburns', fast: true},   // an inspector's chair left empty beside a bare hull
  {line: 'L1', id: 'p03', src: 'shorts/short87/fx/fx_03.mp4', kind: 'video', motion: 'video', fast: true},   // a stamp coming down on paper
  {line: 'L1', id: 'p04', src: 'shorts/short87/fx/fx_04.mp4', kind: 'video', motion: 'video'},   // a ship's rail with nothing but black water beyond
  {line: 'L2', id: 'p05', src: 'shorts/short87/short87_05.png', kind: 'image', motion: 'kenburns'},   // maritime boundaries ending in open blue water
  {line: 'L2', id: 'p06', src: 'shorts/short87/short87_06.png', kind: 'image', motion: 'pushin'},   // the stern of the support ship at night
  {line: 'L2', id: 'p07', src: 'shorts/short87/fx/fx_07.mp4', kind: 'video', motion: 'video'},   // open ocean wake running away astern
  {line: 'L2', id: 'p08', src: 'shorts/short87/short87_08.png', kind: 'image', motion: 'kenburns'},   // the floating launch platform alongside
  {line: 'L2', id: 'p09', src: 'shorts/short87/short87_09.png', kind: 'image', motion: 'pushin'},   // the chart table with a blank chart
  {line: 'L2', id: 'p10', src: 'shorts/short87/fx/fx_10.mp4', kind: 'video', motion: 'video'},   // dividers walked across a chart
  {line: 'L2', id: 'p11', src: 'shorts/short87/short87_11.png', kind: 'image', motion: 'kenburns'},   // the horizon with nothing in any direction
  {line: 'L3', id: 'p12', src: 'shorts/short87/short87_12.png', kind: 'image', motion: 'pushin'},   // the carbon-fibre hull section in the hangar
  {line: 'L3', id: 'p13', src: 'shorts/short87/fx/fx_13.mp4', kind: 'video', motion: 'video'},   // carbon-fibre weave, extreme macro
  {line: 'L3', id: 'p14', src: 'shorts/short87/short87_14.png', kind: 'image', motion: 'kenburns'},   // the test chamber door standing closed
  {line: 'L3', id: 'p15', src: 'shorts/short87/short87_15.png', kind: 'image', motion: 'pushin'},   // the certificate that was never written
  {line: 'L3', id: 'p16', src: 'shorts/short87/short87_16.png', kind: 'image', motion: 'parallax'},   // the inspection gantry standing unused
  {line: 'L4', id: 'p17', src: 'shorts/short87/short87_17.png', kind: 'image', motion: 'kenburns'},   // the company's own workshop at night
  {line: 'L4', id: 'p18', src: 'shorts/short87/fx/fx_18.mp4', kind: 'video', motion: 'video'},   // a dark workshop under one work lamp
  {line: 'L4', id: 'p19', src: 'shorts/short87/short87_19.png', kind: 'image', motion: 'parallax'},   // the hatch sealed from the outside
  {line: 'L4', id: 'p20', src: 'shorts/short87/fx/fx_20.mp4', kind: 'video', motion: 'video'},   // hands running the bolts down
  {line: 'L4', id: 'p21', src: 'shorts/short87/short87_21.png', kind: 'image', motion: 'pushin'},   // the submersible hanging over black water
  {line: 'L4', id: 'p22', src: 'shorts/short87/short87_22.png', kind: 'image', motion: 'parallax'},   // the sea closing over, ripples fading
  {line: 'L8', id: 'p23', src: 'shorts/short87/short87_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short87/short87_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short87/short87_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the unused certification stamp
  {line: 'L5', id: 'p26', src: 'shorts/short87/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // the several nationalities aboard
  {line: 'L5', id: 'p27', src: 'shorts/short87/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // the passengers going aboard
  {line: 'L5', id: 'p28', src: 'shorts/short87/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // the shore falling away behind
  {line: 'L5', id: 'p29', src: 'shorts/short87/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // the regulator's office nobody was standing in
  {line: 'L6', id: 'p31', src: 'shorts/short87/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // the waiver signed before boarding
  {line: 'L6', id: 'p32', src: 'shorts/short87/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // the forms handed round the deck
  {line: 'L7', id: 'p36', src: 'shorts/short87/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // the gap in the system, standing open
  {line: 'L7', id: 'p37', src: 'shorts/short87/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // the hole in the net
  {line: 'L7', id: 'p39', src: 'shorts/short87/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // the rules sitting on a shelf
  {line: 'L7', id: 'p40', src: 'shorts/short87/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // years of it in plain view
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT87_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT87: ShortData = {
  shortId: 'short87',
  episodeId: 'PD-2026-016-titan',
  durationSec: SHORT87_TOTAL_SEC,
  narrationSrc: 'shorts/short87/audio/short87_final_mix_v002_en_us.mp3',
  captions: SHORT87_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short87/short87_ctathumb.jpg',
  ctaLongTitle: "He called safety pure waste and dove",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
