// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #86.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT86_TOTAL_SEC = 57.014;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 7.709
  },
  {
    "id": "L2",
    "start": 7.929,
    "end": 15.034
  },
  {
    "id": "L3",
    "start": 15.254,
    "end": 24.403
  },
  {
    "id": "L4",
    "start": 24.623,
    "end": 31.31
  },
  {
    "id": "L5",
    "start": 31.53,
    "end": 38.496
  },
  {
    "id": "L6",
    "start": 38.716,
    "end": 43.314
  },
  {
    "id": "L7",
    "start": 43.534,
    "end": 48.735
  },
  {
    "id": "L8",
    "start": 48.955,
    "end": 56.014
  }
];

export const SHORT86_CAPTIONS: ShortCaption[] = [
  {
    "word": "More than three dozen submersible engineers",
    "startSec": 0.0,
    "endSec": 2.74
  },
  {
    "word": "scientists and explorers signed one letter.",
    "startSec": 2.74,
    "endSec": 5.479
  },
  {
    "word": "They sent it to",
    "startSec": 5.479,
    "endSec": 6.435
  },
  {
    "word": "the company in 2018.",
    "startSec": 6.435,
    "endSec": 7.709
  },
  {
    "word": "The company wanted to take paying",
    "startSec": 7.929,
    "endSec": 9.616
  },
  {
    "word": "passengers down to the Titanic.",
    "startSec": 9.616,
    "endSec": 11.2
  },
  {
    "word": "And no one had ever certified a",
    "startSec": 11.2,
    "endSec": 12.785
  },
  {
    "word": "carbon-fibre hull to carry people that deep.",
    "startSec": 12.785,
    "endSec": 15.034
  },
  {
    "word": "Carbon fibre does not fail",
    "startSec": 15.254,
    "endSec": 16.978
  },
  {
    "word": "the way steel fails.",
    "startSec": 16.978,
    "endSec": 18.304
  },
  {
    "word": "It was hidden damage accumulating",
    "startSec": 18.304,
    "endSec": 20.491
  },
  {
    "word": "one cycle closer to a threshold",
    "startSec": 20.491,
    "endSec": 22.547
  },
  {
    "word": "no one had truly calculated.",
    "startSec": 22.547,
    "endSec": 24.403
  },
  {
    "word": "The people who do this for",
    "startSec": 24.623,
    "endSec": 26.122
  },
  {
    "word": "a living wrote to say so.",
    "startSec": 26.122,
    "endSec": 27.563
  },
  {
    "word": "The letter went out in 2018.",
    "startSec": 27.563,
    "endSec": 29.177
  },
  {
    "word": "The dives went on",
    "startSec": 29.177,
    "endSec": 30.157
  },
  {
    "word": "for five more years.",
    "startSec": 30.157,
    "endSec": 31.31
  },
  {
    "word": "The letter used one word",
    "startSec": 31.53,
    "endSec": 33.185
  },
  {
    "word": "for what could happen. Catastrophic.",
    "startSec": 33.185,
    "endSec": 35.668
  },
  {
    "word": "It was written five",
    "startSec": 35.668,
    "endSec": 36.979
  },
  {
    "word": "years before the dive.",
    "startSec": 36.979,
    "endSec": 38.496
  },
  {
    "word": "The company declined the check that",
    "startSec": 38.716,
    "endSec": 40.504
  },
  {
    "word": "exists so no one is the",
    "startSec": 40.504,
    "endSec": 41.679
  },
  {
    "word": "sole judge of their own machine.",
    "startSec": 41.679,
    "endSec": 43.314
  },
  {
    "word": "The company's answer was a system",
    "startSec": 43.534,
    "endSec": 45.268
  },
  {
    "word": "listening for the hull to break.",
    "startSec": 45.268,
    "endSec": 46.949
  },
  {
    "word": "A smoke detector for an explosion.",
    "startSec": 46.949,
    "endSec": 48.735
  },
  {
    "word": "Physics has never once been",
    "startSec": 48.955,
    "endSec": 50.421
  },
  {
    "word": "talked out of anything.",
    "startSec": 50.421,
    "endSec": 51.67
  },
  {
    "word": "So when the people who knew that",
    "startSec": 51.67,
    "endSec": 53.408
  },
  {
    "word": "tried to say it out loud",
    "startSec": 53.408,
    "endSec": 54.711
  },
  {
    "word": "how many of them signed?",
    "startSec": 54.711,
    "endSec": 56.014
  }
];
