// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #142.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT142_TOTAL_SEC = 41.029;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.526
  },
  {
    "id": "L2",
    "start": 5.746,
    "end": 13.827
  },
  {
    "id": "L3",
    "start": 14.047,
    "end": 20.409
  },
  {
    "id": "L4",
    "start": 20.629,
    "end": 30.939
  },
  {
    "id": "L5",
    "start": 31.159,
    "end": 40.029
  }
];

export const SHORT142_CAPTIONS: ShortCaption[] = [
  {
    "word": "One justice voted against letting police stop",
    "startSec": 0.0,
    "endSec": 2.537
  },
  {
    "word": "a truck because of who owns it.",
    "startSec": 2.537,
    "endSec": 4.285
  },
  {
    "word": "Her warning was blunt.",
    "startSec": 4.285,
    "endSec": 5.526
  },
  {
    "word": "Justice Sonia Sotomayor was the lone dissenter.",
    "startSec": 5.746,
    "endSec": 8.33
  },
  {
    "word": "In dissent she wrote that",
    "startSec": 8.33,
    "endSec": 9.704
  },
  {
    "word": "the Court ignores key foundations",
    "startSec": 9.704,
    "endSec": 11.518
  },
  {
    "word": "of our reasonable suspicion jurisprudence.",
    "startSec": 11.518,
    "endSec": 13.827
  },
  {
    "word": "And impermissibly and unnecessarily reduces",
    "startSec": 14.047,
    "endSec": 16.652
  },
  {
    "word": "the State's burden of proof.",
    "startSec": 16.652,
    "endSec": 18.349
  },
  {
    "word": "Her deeper worry was about effort.",
    "startSec": 18.349,
    "endSec": 20.409
  },
  {
    "word": "The consequence she wrote",
    "startSec": 20.629,
    "endSec": 22.154
  },
  {
    "word": "is to absolve officers from any",
    "startSec": 22.154,
    "endSec": 24.045
  },
  {
    "word": "responsibility to investigate the identity of",
    "startSec": 24.045,
    "endSec": 26.791
  },
  {
    "word": "a driver where feasible.",
    "startSec": 26.791,
    "endSec": 28.255
  },
  {
    "word": "In her view the deputy",
    "startSec": 28.255,
    "endSec": 29.597
  },
  {
    "word": "could often just look.",
    "startSec": 29.597,
    "endSec": 30.939
  },
  {
    "word": "In dissent she warned the majority",
    "startSec": 31.159,
    "endSec": 33.105
  },
  {
    "word": "had paved the road to finding",
    "startSec": 33.105,
    "endSec": 34.764
  },
  {
    "word": "reasonable suspicion based on nothing more",
    "startSec": 34.764,
    "endSec": 37.168
  },
  {
    "word": "than a demographic profile.",
    "startSec": 37.168,
    "endSec": 38.713
  },
  {
    "word": "One vote against eight.",
    "startSec": 38.713,
    "endSec": 40.029
  }
];
