// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #325.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT325_TOTAL_SEC = 56.736;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.759
  },
  {
    "id": "L2",
    "start": 5.979,
    "end": 10.809
  },
  {
    "id": "L3",
    "start": 11.029,
    "end": 14.605
  },
  {
    "id": "L4",
    "start": 14.825,
    "end": 24.995
  },
  {
    "id": "L5",
    "start": 25.215,
    "end": 35.618
  },
  {
    "id": "L6",
    "start": 35.838,
    "end": 44.011
  },
  {
    "id": "L7",
    "start": 44.231,
    "end": 52.219
  },
  {
    "id": "L8",
    "start": 52.439,
    "end": 55.736
  }
];

export const SHORT325_CAPTIONS: ShortCaption[] = [
  {
    "word": "There is a number on a piece",
    "startSec": 0.0,
    "endSec": 1.414
  },
  {
    "word": "of paper for every ship at sea.",
    "startSec": 1.414,
    "endSec": 2.981
  },
  {
    "word": "The smallest number",
    "startSec": 2.981,
    "endSec": 3.94
  },
  {
    "word": "of people it is allowed to sail",
    "startSec": 3.94,
    "endSec": 5.506
  },
  {
    "word": "with.",
    "startSec": 5.506,
    "endSec": 5.759
  },
  {
    "word": "It is set once",
    "startSec": 5.979,
    "endSec": 6.846
  },
  {
    "word": "against how the ship is expected",
    "startSec": 6.846,
    "endSec": 8.827
  },
  {
    "word": "to be used.",
    "startSec": 8.827,
    "endSec": 9.527
  },
  {
    "word": "A document in a file.",
    "startSec": 9.527,
    "endSec": 10.809
  },
  {
    "word": "It does not follow",
    "startSec": 11.029,
    "endSec": 12.019
  },
  {
    "word": "the ship around asking",
    "startSec": 12.019,
    "endSec": 13.23
  },
  {
    "word": "whether anything changed.",
    "startSec": 13.23,
    "endSec": 14.605
  },
  {
    "word": "When the minimum crew requirements were set",
    "startSec": 14.825,
    "endSec": 17.475
  },
  {
    "word": "the vessel had been scheduled",
    "startSec": 17.475,
    "endSec": 19.263
  },
  {
    "word": "for the Valdez-to-Panama trade.",
    "startSec": 19.263,
    "endSec": 21.174
  },
  {
    "word": "Weeks at sea.",
    "startSec": 21.174,
    "endSec": 21.975
  },
  {
    "word": "Time for the watch system to settle",
    "startSec": 21.975,
    "endSec": 24.132
  },
  {
    "word": "time to sleep.",
    "startSec": 24.132,
    "endSec": 24.995
  },
  {
    "word": "That trade was discontinued after December 1988.",
    "startSec": 25.215,
    "endSec": 28.356
  },
  {
    "word": "The ship began running regularly",
    "startSec": 28.356,
    "endSec": 30.449
  },
  {
    "word": "between Valdez and California.",
    "startSec": 30.449,
    "endSec": 32.412
  },
  {
    "word": "A much shorter passage.",
    "startSec": 32.412,
    "endSec": 33.917
  },
  {
    "word": "The same number of people.",
    "startSec": 33.917,
    "endSec": 35.618
  },
  {
    "word": "Union officials testified",
    "startSec": 35.838,
    "endSec": 37.267
  },
  {
    "word": "that the passages between Alaska",
    "startSec": 37.267,
    "endSec": 39.096
  },
  {
    "word": "and California were not long enough",
    "startSec": 39.096,
    "endSec": 41.096
  },
  {
    "word": "for necessary maintenance",
    "startSec": 41.096,
    "endSec": 42.525
  },
  {
    "word": "or for thorough crew rest.",
    "startSec": 42.525,
    "endSec": 44.011
  },
  {
    "word": "The mates",
    "startSec": 44.231,
    "endSec": 44.931
  },
  {
    "word": "on the EXXON VALDEZ were usually fatigued",
    "startSec": 44.931,
    "endSec": 47.19
  },
  {
    "word": "after cargo handling operations in Valdez",
    "startSec": 47.19,
    "endSec": 49.448
  },
  {
    "word": "and the vessel usually put to sea",
    "startSec": 49.448,
    "endSec": 51.266
  },
  {
    "word": "with a fatigued crew.",
    "startSec": 51.266,
    "endSec": 52.219
  },
  {
    "word": "Usually. Both times. The number",
    "startSec": 52.439,
    "endSec": 54.201
  },
  {
    "word": "on the paper had not moved.",
    "startSec": 54.201,
    "endSec": 55.736
  }
];
