import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT121_CAPTIONS, SHORT121_TOTAL_SEC} from './short121_timing';

/**
 * short121 — Both rulings were five to four, and the dissents said what the majorities would not: for a claim worth a few dollars, taking away the class action does not change the forum, it ends the case.
 * Episode PD-2026-012-arbitration.  Type C — the dissents, one of them read aloud from the bench.
 *
 * AVOIDS: The existing Short lists the clause, the thirty dollars and both decisions. It never says either ruling was contested, what the dissenting justices argued the waiver actually does, or that one dissent was read from the bench.
 * LEAVES FOR THE LONG-FORM: The 1925 law that made all of this possible, and why it sat quiet for most of a century before companies found it.
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-012-arbitration.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short121/short121_01.png', kind: 'image', motion: 'parallax', fast: true},   // a bench microphone standing before one empty high backed c
  {line: 'L1', id: 'p02', src: 'shorts/short121/short121_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a sheaf of blank pages held open in two hands at a bench
  {line: 'L1', id: 'p03', src: 'shorts/short121/fx/fx_03.mp4', kind: 'video', motion: 'video', fast: true},   // a microphone head in macro on a dark desk
  {line: 'L1', id: 'p04', src: 'shorts/short121/short121_04.png', kind: 'image', motion: 'parallax'},   // a dark empty chamber seen from behind the bench
  {line: 'L2', id: 'p05', src: 'shorts/short121/short121_05.png', kind: 'image', motion: 'kenburns'},   // a handset lying in its open box on a kitchen counter
  {line: 'L2', id: 'p06', src: 'shorts/short121/short121_06.png', kind: 'image', motion: 'pushin'},   // a printed bill on a kitchen table with every figure blank
  {line: 'L2', id: 'p07', src: 'shorts/short121/fx/fx_07.mp4', kind: 'video', motion: 'video'},   // a paper statement lying on a table
  {line: 'L2', id: 'p08', src: 'shorts/short121/short121_08.png', kind: 'image', motion: 'kenburns'},   // a contract booklet whose type has become fine grey lines
  {line: 'L2', id: 'p09', src: 'shorts/short121/fx/fx_09.mp4', kind: 'video', motion: 'video'},   // macro of dense fine print with no readable characters
  {line: 'L2', id: 'p10', src: 'shorts/short121/short121_10.png', kind: 'image', motion: 'parallax'},   // a chambers desk with a typewriter and a blank sheet
  {line: 'L2', id: 'p11', src: 'shorts/short121/short121_11.png', kind: 'image', motion: 'kenburns'},   // one chair facing a long row of chairs across a dark table
  {line: 'L3', id: 'p12', src: 'shorts/short121/short121_12.png', kind: 'image', motion: 'pushin'},   // a handful of loose coins on a bare dark table
  {line: 'L3', id: 'p13', src: 'shorts/short121/fx/fx_13.mp4', kind: 'video', motion: 'video'},   // coins in macro on a dark surface
  {line: 'L3', id: 'p14', src: 'shorts/short121/short121_14.png', kind: 'image', motion: 'kenburns'},   // hundreds of blank envelopes spread across a dark floor
  {line: 'L3', id: 'p15', src: 'shorts/short121/short121_15.png', kind: 'image', motion: 'pushin'},   // a courtroom door closing on a narrowing blade of light
  {line: 'L3', id: 'p16', src: 'shorts/short121/fx/fx_16.mp4', kind: 'video', motion: 'video'},   // a heavy door swinging closed in the dark
  {line: 'L4', id: 'p17', src: 'shorts/short121/short121_17.png', kind: 'image', motion: 'kenburns'},   // an onboarding folder squared on a desk beside a blank lany
  {line: 'L4', id: 'p18', src: 'shorts/short121/short121_18.png', kind: 'image', motion: 'pushin'},   // a dark factory floor at shift change
  {line: 'L4', id: 'p19', src: 'shorts/short121/fx/fx_19.mp4', kind: 'video', motion: 'video'},   // silhouettes walking away down an office corridor
  {line: 'L4', id: 'p20', src: 'shorts/short121/short121_20.png', kind: 'image', motion: 'kenburns'},   // folded reading glasses resting on a stack of blank pages
  {line: 'L4', id: 'p21', src: 'shorts/short121/fx/fx_21.mp4', kind: 'video', motion: 'video'},   // reading glasses lying on documents
  {line: 'L4', id: 'p22', src: 'shorts/short121/short121_22.png', kind: 'image', motion: 'parallax'},   // a closed chamber door with rows of empty press seats befor
  {line: 'L8', id: 'p23', src: 'shorts/short121/short121_04.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short121/short121_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short121/short121_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to plate 01: a bench microphone standing before one
  {line: 'L5', id: 'p26', src: 'shorts/short121/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // a pair of hands resting on a metal workbench
  {line: 'L5', id: 'p27', src: 'shorts/short121/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // a single empty chair standing in a large room
  {line: 'L5', id: 'p28', src: 'shorts/short121/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // rows of empty desks across an open plan office
  {line: 'L5', id: 'p29', src: 'shorts/short121/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // a long row of identical closed office doors
  {line: 'L5', id: 'p30', src: 'shorts/short121/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // a group of workers walking together outdoors
  {line: 'L6', id: 'p31', src: 'shorts/short121/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // two chairs turned to face each other in a bare room
  {line: 'L6', id: 'p32', src: 'shorts/short121/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // a round wall clock above a doorway
  {line: 'L6', id: 'p34', src: 'shorts/short121/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // a padlock and chain holding a metal gate shut
  {line: 'L6', id: 'p35', src: 'shorts/short121/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // one person waiting alone on an empty station platform
  {line: 'L7', id: 'p36', src: 'shorts/short121/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // a smartphone lying face up on a cafe table
  {line: 'L7', id: 'p37', src: 'shorts/short121/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // a hand pressing the keys of a cash machine
  {line: 'L7', id: 'p38', src: 'shorts/short121/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a worker in a hi vis vest moving boxes in a warehouse
  {line: 'L7', id: 'p39', src: 'shorts/short121/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // two hands clasping in a firm handshake
  {line: 'L7', id: 'p40', src: 'shorts/short121/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a jacket left hanging over an office chair
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT121_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT121: ShortData = {
  shortId: 'short121',
  episodeId: 'PD-2026-012-arbitration',
  durationSec: SHORT121_TOTAL_SEC,
  narrationSrc: 'shorts/short121/audio/short121_final_mix_v002_en_us.mp3',
  captions: SHORT121_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short121/short121_ctathumb.jpg',
  ctaLongTitle: "The Fine Print That Quietly Took Your",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
