// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #87.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT87_TOTAL_SEC = 59.011;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.548
  },
  {
    "id": "L2",
    "start": 6.768,
    "end": 12.898
  },
  {
    "id": "L3",
    "start": 13.118,
    "end": 19.666
  },
  {
    "id": "L4",
    "start": 19.886,
    "end": 26.48
  },
  {
    "id": "L5",
    "start": 26.7,
    "end": 35.431
  },
  {
    "id": "L6",
    "start": 35.651,
    "end": 42.896
  },
  {
    "id": "L7",
    "start": 43.116,
    "end": 49.432
  },
  {
    "id": "L8",
    "start": 49.652,
    "end": 58.011
  }
];

export const SHORT87_CAPTIONS: ShortCaption[] = [
  {
    "word": "The submersible carried no certification.",
    "startSec": 0.0,
    "endSec": 2.314
  },
  {
    "word": "It did not need one.",
    "startSec": 2.314,
    "endSec": 3.443
  },
  {
    "word": "The dive happened where no",
    "startSec": 3.443,
    "endSec": 4.911
  },
  {
    "word": "country's safety rules reach.",
    "startSec": 4.911,
    "endSec": 6.548
  },
  {
    "word": "Far out in the North Atlantic",
    "startSec": 6.768,
    "endSec": 8.564
  },
  {
    "word": "launched from a ship.",
    "startSec": 8.564,
    "endSec": 9.864
  },
  {
    "word": "In the seam between everyone's",
    "startSec": 9.864,
    "endSec": 11.722
  },
  {
    "word": "rules and no one's.",
    "startSec": 11.722,
    "endSec": 12.898
  },
  {
    "word": "No one had ever certified a carbon-fibre",
    "startSec": 13.118,
    "endSec": 15.416
  },
  {
    "word": "hull to carry passengers to that depth.",
    "startSec": 15.416,
    "endSec": 17.656
  },
  {
    "word": "On paper",
    "startSec": 17.656,
    "endSec": 18.356
  },
  {
    "word": "nothing required anyone to.",
    "startSec": 18.356,
    "endSec": 19.666
  },
  {
    "word": "So the only check on the vessel",
    "startSec": 19.886,
    "endSec": 21.695
  },
  {
    "word": "was the company that built it.",
    "startSec": 21.695,
    "endSec": 23.446
  },
  {
    "word": "Five people went down on",
    "startSec": 23.446,
    "endSec": 24.846
  },
  {
    "word": "the eighteenth of June 2023.",
    "startSec": 24.846,
    "endSec": 26.48
  },
  {
    "word": "It was an American company",
    "startSec": 26.7,
    "endSec": 28.276
  },
  {
    "word": "working beyond American shores",
    "startSec": 28.276,
    "endSec": 30.095
  },
  {
    "word": "carrying citizens of several countries to a",
    "startSec": 30.095,
    "endSec": 32.703
  },
  {
    "word": "place no national regulator clearly governed.",
    "startSec": 32.703,
    "endSec": 35.431
  },
  {
    "word": "Each passenger signed a",
    "startSec": 35.651,
    "endSec": 37.088
  },
  {
    "word": "waiver before the dive.",
    "startSec": 37.088,
    "endSec": 38.524
  },
  {
    "word": "It said the vessel was experimental.",
    "startSec": 38.524,
    "endSec": 40.772
  },
  {
    "word": "It named in writing",
    "startSec": 40.772,
    "endSec": 41.959
  },
  {
    "word": "the word death.",
    "startSec": 41.959,
    "endSec": 42.896
  },
  {
    "word": "The system meant to catch a thing",
    "startSec": 43.116,
    "endSec": 44.944
  },
  {
    "word": "like this had a hole in it.",
    "startSec": 44.944,
    "endSec": 46.44
  },
  {
    "word": "Stockton Rush sailed through it",
    "startSec": 46.44,
    "endSec": 48.158
  },
  {
    "word": "in full view for years.",
    "startSec": 48.158,
    "endSec": 49.432
  },
  {
    "word": "The most dangerous moments in human",
    "startSec": 49.652,
    "endSec": 51.835
  },
  {
    "word": "history almost never look dangerous.",
    "startSec": 51.835,
    "endSec": 54.081
  },
  {
    "word": "So out there",
    "startSec": 54.081,
    "endSec": 54.83
  },
  {
    "word": "that far from shore",
    "startSec": 54.83,
    "endSec": 56.015
  },
  {
    "word": "who was ever supposed to say no?",
    "startSec": 56.015,
    "endSec": 58.011
  }
];
