// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #303.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT303_TOTAL_SEC = 57.293;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.573
  },
  {
    "id": "L2",
    "start": 5.793,
    "end": 11.877
  },
  {
    "id": "L3",
    "start": 12.097,
    "end": 20.317
  },
  {
    "id": "L4",
    "start": 20.537,
    "end": 27.364
  },
  {
    "id": "L5",
    "start": 27.584,
    "end": 33.157
  },
  {
    "id": "L6",
    "start": 33.377,
    "end": 39.739
  },
  {
    "id": "L7",
    "start": 39.959,
    "end": 45.485
  },
  {
    "id": "L8",
    "start": 45.705,
    "end": 56.293
  }
];

export const SHORT303_CAPTIONS: ShortCaption[] = [
  {
    "word": "The commission asked the company",
    "startSec": 0.0,
    "endSec": 1.564
  },
  {
    "word": "for everything it had spent",
    "startSec": 1.564,
    "endSec": 2.884
  },
  {
    "word": "on structural work on the whole viaduct",
    "startSec": 2.884,
    "endSec": 4.791
  },
  {
    "word": "and totalled it.",
    "startSec": 4.791,
    "endSec": 5.573
  },
  {
    "word": "From 1982 to 2018: twenty-four million",
    "startSec": 5.793,
    "endSec": 8.513
  },
  {
    "word": "six hundred and ten thousand",
    "startSec": 8.513,
    "endSec": 10.517
  },
  {
    "word": "five hundred euros.",
    "startSec": 10.517,
    "endSec": 11.877
  },
  {
    "word": "Ninety-eight per cent of that was spent",
    "startSec": 12.097,
    "endSec": 14.814
  },
  {
    "word": "before 1999",
    "startSec": 14.814,
    "endSec": 15.58
  },
  {
    "word": "the year the motorway company was privatised.",
    "startSec": 15.58,
    "endSec": 18.715
  },
  {
    "word": "After 1999",
    "startSec": 18.715,
    "endSec": 19.415
  },
  {
    "word": "two per cent.",
    "startSec": 19.415,
    "endSec": 20.317
  },
  {
    "word": "In the seventeen years to 1999",
    "startSec": 20.537,
    "endSec": 22.451
  },
  {
    "word": "it averaged one point three million euros",
    "startSec": 22.451,
    "endSec": 25.067
  },
  {
    "word": "a year. After twenty-three thousand.",
    "startSec": 25.067,
    "endSec": 27.364
  },
  {
    "word": "The whole list of structural works",
    "startSec": 27.584,
    "endSec": 29.713
  },
  {
    "word": "on that bridge",
    "startSec": 29.713,
    "endSec": 30.59
  },
  {
    "word": "over thirty-six years",
    "startSec": 30.59,
    "endSec": 31.905
  },
  {
    "word": "is seven lines long.",
    "startSec": 31.905,
    "endSec": 33.157
  },
  {
    "word": "Then 2005: fifty thousand. 2015:",
    "startSec": 33.377,
    "endSec": 35.543
  },
  {
    "word": "two hundred and eighty-eight thousand.",
    "startSec": 35.543,
    "endSec": 38.115
  },
  {
    "word": "That is the whole of it.",
    "startSec": 38.115,
    "endSec": 39.739
  },
  {
    "word": "The commission drew the obvious conclusion",
    "startSec": 39.959,
    "endSec": 42.191
  },
  {
    "word": "and it wrote it down",
    "startSec": 42.191,
    "endSec": 43.253
  },
  {
    "word": "in the language",
    "startSec": 43.253,
    "endSec": 44.05
  },
  {
    "word": "of the concession contract.",
    "startSec": 44.05,
    "endSec": 45.485
  },
  {
    "word": "Not doing simple ordinary maintenance",
    "startSec": 45.705,
    "endSec": 47.881
  },
  {
    "word": "today means wanting",
    "startSec": 47.881,
    "endSec": 48.999
  },
  {
    "word": "to do a great deal",
    "startSec": 48.999,
    "endSec": 50.058
  },
  {
    "word": "of extraordinary maintenance tomorrow",
    "startSec": 50.058,
    "endSec": 52.234
  },
  {
    "word": "at certainly higher costs",
    "startSec": 52.234,
    "endSec": 53.705
  },
  {
    "word": "with a mirror-image higher remunerativeness.",
    "startSec": 53.705,
    "endSec": 56.293
  }
];
