// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #46.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT46_TOTAL_SEC = 53.06;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.641
  },
  {
    "id": "L2",
    "start": 7.361,
    "end": 19.621
  },
  {
    "id": "L3",
    "start": 20.341,
    "end": 33.205
  },
  {
    "id": "L4",
    "start": 33.925,
    "end": 48.693
  },
  {
    "id": "L5",
    "start": 49.413,
    "end": 52.06
  }
];

export const SHORT46_CAPTIONS: ShortCaption[] = [
  {
    "word": "An officer questions you.",
    "startSec": 0.0,
    "endSec": 1.372
  },
  {
    "word": "He never reads you your rights.",
    "startSec": 1.372,
    "endSec": 3.074
  },
  {
    "word": "Your own written words go on trial.",
    "startSec": 3.074,
    "endSec": 4.994
  },
  {
    "word": "Can you make him pay for that?",
    "startSec": 4.994,
    "endSec": 6.641
  },
  {
    "word": "In Los Angeles a hospital worker was",
    "startSec": 7.361,
    "endSec": 9.395
  },
  {
    "word": "questioned by a sheriff's deputy.",
    "startSec": 9.395,
    "endSec": 11.259
  },
  {
    "word": "No warning no right to stay silent",
    "startSec": 11.259,
    "endSec": 13.18
  },
  {
    "word": "was ever spoken.",
    "startSec": 13.18,
    "endSec": 14.084
  },
  {
    "word": "He wrote a statement and it was",
    "startSec": 14.084,
    "endSec": 15.836
  },
  {
    "word": "used against him at trial.",
    "startSec": 15.836,
    "endSec": 17.305
  },
  {
    "word": "A jury heard everything and set him free.",
    "startSec": 17.305,
    "endSec": 19.621
  },
  {
    "word": "So he sued the deputy for money",
    "startSec": 20.341,
    "endSec": 22.01
  },
  {
    "word": "under a civil rights law for the",
    "startSec": 22.01,
    "endSec": 23.732
  },
  {
    "word": "warning that never came.",
    "startSec": 23.732,
    "endSec": 25.024
  },
  {
    "word": "Twice juries sided with the officer.",
    "startSec": 25.024,
    "endSec": 26.961
  },
  {
    "word": "An appeals court said that missing warning",
    "startSec": 26.961,
    "endSec": 29.222
  },
  {
    "word": "could support the lawsuit.",
    "startSec": 29.222,
    "endSec": 30.621
  },
  {
    "word": "So the deputy asked the Supreme Court",
    "startSec": 30.621,
    "endSec": 32.613
  },
  {
    "word": "to step in.",
    "startSec": 32.613,
    "endSec": 33.205
  },
  {
    "word": "In 2022 the Court ruled six to three.",
    "startSec": 33.925,
    "endSec": 36.24
  },
  {
    "word": "Skipping the Miranda warning by itself is",
    "startSec": 36.24,
    "endSec": 38.806
  },
  {
    "word": "not something you can sue an officer over.",
    "startSec": 38.806,
    "endSec": 41.434
  },
  {
    "word": "But Miranda still stands.",
    "startSec": 41.434,
    "endSec": 42.999
  },
  {
    "word": "Your unwarned words can still be kept",
    "startSec": 42.999,
    "endSec": 45.314
  },
  {
    "word": "out of your trial.",
    "startSec": 45.314,
    "endSec": 46.44
  },
  {
    "word": "A right is not the same as a payout.",
    "startSec": 46.44,
    "endSec": 48.693
  },
  {
    "word": "Watch the full case on the channel.",
    "startSec": 49.413,
    "endSec": 51.23
  },
  {
    "word": "Follow for more.",
    "startSec": 51.23,
    "endSec": 52.06
  }
];
