// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #33.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT33_TOTAL_SEC = 63.555;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 8.777
  },
  {
    "id": "L2",
    "start": 9.497,
    "end": 26.68
  },
  {
    "id": "L3",
    "start": 27.4,
    "end": 40.078
  },
  {
    "id": "L4",
    "start": 40.798,
    "end": 58.724
  },
  {
    "id": "L5",
    "start": 59.444,
    "end": 62.555
  }
];

export const SHORT33_CAPTIONS: ShortCaption[] = [
  {
    "word": "You owe the county fifteen thousand dollars.",
    "startSec": 0.0,
    "endSec": 2.758
  },
  {
    "word": "They take your home",
    "startSec": 2.758,
    "endSec": 3.95
  },
  {
    "word": "sell it for forty thousand",
    "startSec": 3.95,
    "endSec": 5.58
  },
  {
    "word": "and keep every last dollar.",
    "startSec": 5.58,
    "endSec": 7.272
  },
  {
    "word": "Can they really do that?",
    "startSec": 7.272,
    "endSec": 8.777
  },
  {
    "word": "That's what happened to Geraldine Tyler. At ninety-four",
    "startSec": 9.497,
    "endSec": 12.679
  },
  {
    "word": "she owed about fifteen thousand in property",
    "startSec": 12.679,
    "endSec": 15.167
  },
  {
    "word": "taxes and penalties on her old condo. Hennepin County",
    "startSec": 15.167,
    "endSec": 18.233
  },
  {
    "word": "Minnesota seized it",
    "startSec": 18.233,
    "endSec": 19.332
  },
  {
    "word": "sold it for forty thousand",
    "startSec": 19.332,
    "endSec": 20.837
  },
  {
    "word": "and kept the entire amount",
    "startSec": 20.837,
    "endSec": 22.341
  },
  {
    "word": "including roughly twenty-five thousand that had nothing",
    "startSec": 22.341,
    "endSec": 25.523
  },
  {
    "word": "to do with the debt.",
    "startSec": 25.523,
    "endSec": 26.68
  },
  {
    "word": "The Constitution's Fifth Amendment says if the",
    "startSec": 27.4,
    "endSec": 29.914
  },
  {
    "word": "government takes your property",
    "startSec": 29.914,
    "endSec": 31.553
  },
  {
    "word": "it has to pay for it.",
    "startSec": 31.553,
    "endSec": 32.701
  },
  {
    "word": "That extra twenty-five thousand was hers",
    "startSec": 32.701,
    "endSec": 34.887
  },
  {
    "word": "not the county's. Keeping it",
    "startSec": 34.887,
    "endSec": 36.417
  },
  {
    "word": "her lawyers said",
    "startSec": 36.417,
    "endSec": 37.291
  },
  {
    "word": "was the government taking far more than",
    "startSec": 37.291,
    "endSec": 39.422
  },
  {
    "word": "it was owed.",
    "startSec": 39.422,
    "endSec": 40.078
  },
  {
    "word": "In 2023",
    "startSec": 40.798,
    "endSec": 41.498
  },
  {
    "word": "the Supreme Court agreed",
    "startSec": 41.498,
    "endSec": 43.024
  },
  {
    "word": "nine to zero.",
    "startSec": 43.024,
    "endSec": 43.85
  },
  {
    "word": "Chief Justice Roberts wrote that a taxpayer",
    "startSec": 43.85,
    "endSec": 46.583
  },
  {
    "word": "must render unto Caesar what is Caesar's",
    "startSec": 46.583,
    "endSec": 49.126
  },
  {
    "word": "but no more.",
    "startSec": 49.126,
    "endSec": 49.889
  },
  {
    "word": "Pocketing the surplus was an unconstitutional taking.",
    "startSec": 49.889,
    "endSec": 53.258
  },
  {
    "word": "Most states already banned what critics call",
    "startSec": 53.258,
    "endSec": 56.055
  },
  {
    "word": "home equity theft",
    "startSec": 56.055,
    "endSec": 57.136
  },
  {
    "word": "now it's the rule everywhere.",
    "startSec": 57.136,
    "endSec": 58.724
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 59.444,
    "endSec": 61.598
  },
  {
    "word": "Follow for more.",
    "startSec": 61.598,
    "endSec": 62.555
  }
];
