// AUTO-GENERATED by scripts/build_short08_mix.py — narration-driven timing for SHORT #8.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT08_TOTAL_SEC = 40.639;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.362
  },
  {
    "id": "L2",
    "start": 9.062,
    "end": 14.263
  },
  {
    "id": "L3",
    "start": 16.963,
    "end": 23.279
  },
  {
    "id": "L4",
    "start": 25.979,
    "end": 33.967
  },
  {
    "id": "L5",
    "start": 36.667,
    "end": 39.639
  }
];

export const SHORT08_CAPTIONS: ShortCaption[] = [
  {
    "word": "Your phone keeps a record of everywhere you go.",
    "startSec": 0.0,
    "endSec": 2.534
  },
  {
    "word": "Police wanted a hundred and twenty-seven days of it, without a warrant.",
    "startSec": 2.534,
    "endSec": 6.362
  },
  {
    "word": "Every few minutes, a phone connects to a nearby cell tower and leaves a trace of where you are.",
    "startSec": 9.062,
    "endSec": 14.263
  },
  {
    "word": "Police got months of that location history from the carrier, and placed a suspect near a string of robberies.",
    "startSec": 16.963,
    "endSec": 23.279
  },
  {
    "word": "In 2018, the Supreme Court said no.",
    "startSec": 25.979,
    "endSec": 28.163
  },
  {
    "word": "This much location data needs a warrant.",
    "startSec": 28.163,
    "endSec": 30.659
  },
  {
    "word": "For the first time, your digital trail was protected.",
    "startSec": 30.659,
    "endSec": 33.967
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 36.667,
    "endSec": 38.725
  },
  {
    "word": "Follow for more.",
    "startSec": 38.725,
    "endSec": 39.639
  }
];
