// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #174.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT174_TOTAL_SEC = 39.496;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 3.669
  },
  {
    "id": "L2",
    "start": 3.889,
    "end": 13.409
  },
  {
    "id": "L3",
    "start": 13.629,
    "end": 22.035
  },
  {
    "id": "L4",
    "start": 22.255,
    "end": 32.332
  },
  {
    "id": "L5",
    "start": 32.552,
    "end": 38.496
  }
];

export const SHORT174_CAPTIONS: ShortCaption[] = [
  {
    "word": "A court can erase a child's record.",
    "startSec": 0.0,
    "endSec": 1.976
  },
  {
    "word": "It cannot give back the years.",
    "startSec": 1.976,
    "endSec": 3.669
  },
  {
    "word": "Pennsylvania's Supreme Court reached back into",
    "startSec": 3.889,
    "endSec": 6.363
  },
  {
    "word": "that courtroom and unmade it",
    "startSec": 6.363,
    "endSec": 7.869
  },
  {
    "word": "throwing out thousands of adjudications and",
    "startSec": 7.869,
    "endSec": 10.182
  },
  {
    "word": "clearing the records of as many",
    "startSec": 10.182,
    "endSec": 11.849
  },
  {
    "word": "as several thousand children.",
    "startSec": 11.849,
    "endSec": 13.409
  },
  {
    "word": "Behind each of those",
    "startSec": 13.629,
    "endSec": 14.912
  },
  {
    "word": "cases was a year or two",
    "startSec": 14.912,
    "endSec": 16.388
  },
  {
    "word": "or three that the",
    "startSec": 16.388,
    "endSec": 17.479
  },
  {
    "word": "county had already spent.",
    "startSec": 17.479,
    "endSec": 19.083
  },
  {
    "word": "Nights in a cell that",
    "startSec": 19.083,
    "endSec": 20.431
  },
  {
    "word": "no order could give back.",
    "startSec": 20.431,
    "endSec": 22.035
  },
  {
    "word": "The judges are named and gone.",
    "startSec": 22.255,
    "endSec": 23.944
  },
  {
    "word": "One spent years in prison.",
    "startSec": 23.944,
    "endSec": 25.408
  },
  {
    "word": "The other was quietly",
    "startSec": 25.408,
    "endSec": 26.59
  },
  {
    "word": "granted an early release",
    "startSec": 26.59,
    "endSec": 27.941
  },
  {
    "word": "and walked back out while the children",
    "startSec": 27.941,
    "endSec": 30.08
  },
  {
    "word": "he sentenced were still carrying theirs.",
    "startSec": 30.08,
    "endSec": 32.332
  },
  {
    "word": "The men could be punished.",
    "startSec": 32.552,
    "endSec": 34.082
  },
  {
    "word": "The years still do not come back.",
    "startSec": 34.082,
    "endSec": 36.024
  },
  {
    "word": "That is what a",
    "startSec": 36.024,
    "endSec": 36.848
  },
  {
    "word": "cleared record cannot reach.",
    "startSec": 36.848,
    "endSec": 38.496
  }
];
