// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #135.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT135_TOTAL_SEC = 40.982;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.269
  },
  {
    "id": "L2",
    "start": 6.489,
    "end": 15.684
  },
  {
    "id": "L3",
    "start": 15.904,
    "end": 25.053
  },
  {
    "id": "L4",
    "start": 25.273,
    "end": 33.725
  },
  {
    "id": "L5",
    "start": 33.945,
    "end": 39.982
  }
];

export const SHORT135_CAPTIONS: ShortCaption[] = [
  {
    "word": "The test that decides whether",
    "startSec": 0.0,
    "endSec": 1.668
  },
  {
    "word": "police need a warrant to",
    "startSec": 1.668,
    "endSec": 3.048
  },
  {
    "word": "track you is not fixed. It moves.",
    "startSec": 3.048,
    "endSec": 4.946
  },
  {
    "word": "And it has been moving.",
    "startSec": 4.946,
    "endSec": 6.269
  },
  {
    "word": "Harlan's phrase",
    "startSec": 6.489,
    "endSec": 7.496
  },
  {
    "word": "a reasonable expectation of privacy",
    "startSec": 7.496,
    "endSec": 9.845
  },
  {
    "word": "was only one justice's gloss in 1967.",
    "startSec": 9.845,
    "endSec": 12.328
  },
  {
    "word": "Courts reached for it until",
    "startSec": 12.328,
    "endSec": 14.14
  },
  {
    "word": "it became the standard.",
    "startSec": 14.14,
    "endSec": 15.684
  },
  {
    "word": "When judges today ask whether police need",
    "startSec": 15.904,
    "endSec": 18.583
  },
  {
    "word": "a warrant to track your phone",
    "startSec": 18.583,
    "endSec": 20.479
  },
  {
    "word": "read your messages",
    "startSec": 20.479,
    "endSec": 21.655
  },
  {
    "word": "or follow your car",
    "startSec": 21.655,
    "endSec": 22.831
  },
  {
    "word": "they are asking Harlan's question.",
    "startSec": 22.831,
    "endSec": 25.053
  },
  {
    "word": "But reasonable is a moving target.",
    "startSec": 25.273,
    "endSec": 27.371
  },
  {
    "word": "The more ordinary it",
    "startSec": 27.371,
    "endSec": 28.604
  },
  {
    "word": "becomes to be watched",
    "startSec": 28.604,
    "endSec": 29.9
  },
  {
    "word": "the weaker anyone's claim that",
    "startSec": 29.9,
    "endSec": 31.751
  },
  {
    "word": "a given expectation still holds.",
    "startSec": 31.751,
    "endSec": 33.725
  },
  {
    "word": "So the privacy you have tomorrow",
    "startSec": 33.945,
    "endSec": 35.785
  },
  {
    "word": "depends on how much watching we",
    "startSec": 35.785,
    "endSec": 37.567
  },
  {
    "word": "get used to today.",
    "startSec": 37.567,
    "endSec": 38.602
  },
  {
    "word": "Which way is that going?",
    "startSec": 38.602,
    "endSec": 39.982
  }
];
