// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #316.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT316_TOTAL_SEC = 55.806;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 7.802
  },
  {
    "id": "L2",
    "start": 8.022,
    "end": 15.87
  },
  {
    "id": "L3",
    "start": 16.09,
    "end": 26.957
  },
  {
    "id": "L4",
    "start": 27.177,
    "end": 32.146
  },
  {
    "id": "L5",
    "start": 32.366,
    "end": 40.911
  },
  {
    "id": "L6",
    "start": 41.131,
    "end": 46.007
  },
  {
    "id": "L7",
    "start": 46.227,
    "end": 48.642
  },
  {
    "id": "L8",
    "start": 48.862,
    "end": 54.806
  }
];

export const SHORT316_CAPTIONS: ShortCaption[] = [
  {
    "word": "There is a gauge in this story.",
    "startSec": 0.0,
    "endSec": 1.89
  },
  {
    "word": "It is about the size",
    "startSec": 1.89,
    "endSec": 3.109
  },
  {
    "word": "of a pocket watch",
    "startSec": 3.109,
    "endSec": 4.145
  },
  {
    "word": "it costs less than a good pair",
    "startSec": 4.145,
    "endSec": 5.973
  },
  {
    "word": "of boots",
    "startSec": 5.973,
    "endSec": 6.673
  },
  {
    "word": "and it has one needle.",
    "startSec": 6.673,
    "endSec": 7.802
  },
  {
    "word": "You cannot see the threads inside",
    "startSec": 8.022,
    "endSec": 9.693
  },
  {
    "word": "the nut without taking",
    "startSec": 9.693,
    "endSec": 10.807
  },
  {
    "word": "the whole assembly off the aeroplane.",
    "startSec": 10.807,
    "endSec": 12.68
  },
  {
    "word": "So the manufacturer designed a way",
    "startSec": 12.68,
    "endSec": 14.402
  },
  {
    "word": "to measure the wear in place.",
    "startSec": 14.402,
    "endSec": 15.87
  },
  {
    "word": "You measure that movement",
    "startSec": 16.09,
    "endSec": 17.591
  },
  {
    "word": "with a dial indicator.",
    "startSec": 17.591,
    "endSec": 18.912
  },
  {
    "word": "If the reading is between three",
    "startSec": 18.912,
    "endSec": 20.773
  },
  {
    "word": "thousandths of an inch",
    "startSec": 20.773,
    "endSec": 22.094
  },
  {
    "word": "and forty thousandths",
    "startSec": 22.094,
    "endSec": 23.355
  },
  {
    "word": "the assembly stays on the aeroplane.",
    "startSec": 23.355,
    "endSec": 25.516
  },
  {
    "word": "Above forty",
    "startSec": 25.516,
    "endSec": 26.216
  },
  {
    "word": "it comes off.",
    "startSec": 26.216,
    "endSec": 26.957
  },
  {
    "word": "That is the entire safety net.",
    "startSec": 27.177,
    "endSec": 29.017
  },
  {
    "word": "A number",
    "startSec": 29.017,
    "endSec": 29.717
  },
  {
    "word": "in thousandths of an inch",
    "startSec": 29.717,
    "endSec": 31.251
  },
  {
    "word": "read off a needle.",
    "startSec": 31.251,
    "endSec": 32.146
  },
  {
    "word": "Before July 2000",
    "startSec": 32.366,
    "endSec": 33.336
  },
  {
    "word": "five months after this accident",
    "startSec": 33.336,
    "endSec": 35.214
  },
  {
    "word": "an end play measurement",
    "startSec": 35.214,
    "endSec": 36.608
  },
  {
    "word": "that came out inside",
    "startSec": 36.608,
    "endSec": 37.82
  },
  {
    "word": "the limits was not required",
    "startSec": 37.82,
    "endSec": 39.457
  },
  {
    "word": "to be recorded anywhere.",
    "startSec": 39.457,
    "endSec": 40.911
  },
  {
    "word": "If the needle read thirty-nine thousandths",
    "startSec": 41.131,
    "endSec": 43.406
  },
  {
    "word": "the aeroplane passed",
    "startSec": 43.406,
    "endSec": 44.49
  },
  {
    "word": "and the number went nowhere.",
    "startSec": 44.49,
    "endSec": 46.007
  },
  {
    "word": "Nobody wrote it down",
    "startSec": 46.227,
    "endSec": 47.377
  },
  {
    "word": "because nobody had to.",
    "startSec": 47.377,
    "endSec": 48.642
  },
  {
    "word": "Which means there was no way",
    "startSec": 48.862,
    "endSec": 50.309
  },
  {
    "word": "to compare one check against the next.",
    "startSec": 50.309,
    "endSec": 52.273
  },
  {
    "word": "No way to see",
    "startSec": 52.273,
    "endSec": 52.973
  },
  {
    "word": "a number creeping up over the years.",
    "startSec": 52.973,
    "endSec": 54.806
  }
];
