// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #271.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT271_TOTAL_SEC = 35.374;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.92
  },
  {
    "id": "L2",
    "start": 7.14,
    "end": 11.273
  },
  {
    "id": "L3",
    "start": 11.493,
    "end": 14.047
  },
  {
    "id": "L4",
    "start": 14.267,
    "end": 20.444
  },
  {
    "id": "L5",
    "start": 20.664,
    "end": 24.333
  },
  {
    "id": "L6",
    "start": 24.553,
    "end": 25.575
  },
  {
    "id": "L7",
    "start": 25.795,
    "end": 29.835
  },
  {
    "id": "L8",
    "start": 30.055,
    "end": 34.374
  }
];

export const SHORT271_CAPTIONS: ShortCaption[] = [
  {
    "word": "A state wildlife officer walks onto",
    "startSec": 0.0,
    "endSec": 2.07
  },
  {
    "word": "private land in West Tennessee",
    "startSec": 2.07,
    "endSec": 3.844
  },
  {
    "word": "cuts a branch off a tree",
    "startSec": 3.844,
    "endSec": 5.264
  },
  {
    "word": "and installs a camera on it.",
    "startSec": 5.264,
    "endSec": 6.92
  },
  {
    "word": "The land runs to approximately ninety-three acres.",
    "startSec": 7.14,
    "endSec": 10.319
  },
  {
    "word": "A man farms it.",
    "startSec": 10.319,
    "endSec": 11.273
  },
  {
    "word": "The Fourth Amendment does",
    "startSec": 11.493,
    "endSec": 12.852
  },
  {
    "word": "not protect that land.",
    "startSec": 12.852,
    "endSec": 14.047
  },
  {
    "word": "Open fields are afforded no constitutional",
    "startSec": 14.267,
    "endSec": 16.484
  },
  {
    "word": "protection from warrantless searches and seizure",
    "startSec": 16.484,
    "endSec": 19.019
  },
  {
    "word": "under the Fourth Amendment.",
    "startSec": 19.019,
    "endSec": 20.444
  },
  {
    "word": "The statute he entered under does",
    "startSec": 20.664,
    "endSec": 22.369
  },
  {
    "word": "not provide notice to property owners.",
    "startSec": 22.369,
    "endSec": 24.333
  },
  {
    "word": "Nobody has to.",
    "startSec": 24.553,
    "endSec": 25.575
  },
  {
    "word": "A Tennessee court later found the",
    "startSec": 25.795,
    "endSec": 27.756
  },
  {
    "word": "state constitution does protect it.",
    "startSec": 27.756,
    "endSec": 29.835
  },
  {
    "word": "On the day the branch",
    "startSec": 30.055,
    "endSec": 31.11
  },
  {
    "word": "came off the tree",
    "startSec": 31.11,
    "endSec": 31.963
  },
  {
    "word": "nothing in the federal charter",
    "startSec": 31.963,
    "endSec": 33.47
  },
  {
    "word": "said he could not.",
    "startSec": 33.47,
    "endSec": 34.374
  }
];
