import type {ShortArt, ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT08_CAPTIONS, SHORT08_TOTAL_SEC} from './short08_timing';

/**
 * SHORT #8 — Carpenter v. United States ("Police need a warrant for your location history").
 * US-market English (the channel is US English; matches short06/short07).
 * Source of truth: episodes/_planning/SHORTS_EP1-8.md (VO/telop) + SHORTS_MOTION_DESIGN.md §3 #8
 * (BigNumber 127 days / DiagramFlow / Vote 5–4 / Citation 2018).
 *
 * NARRATION-DRIVEN: the cuts below are laid out against the real narration line windows
 * (short08_timing.ts, generated by scripts/build_short08_mix.py). Each line's visual cuts split
 * the span up to the next line so the picture is continuous. Audio = the finished 4-layer mix.
 * Same footage exports for YouTube and TikTok; only the CTA text differs (platform prop).
 */

const img = (n: string) => `shorts/short08/short08_${n}.png`;
const r3 = (n: number) => Math.round(n * 1000) / 1000;

type Cut = {
  line: string;
  id: string;
  src: string | null;
  kind: 'image' | 'video' | 'card';
  motion: ShortBeat['motion'];
  telop?: string;
  fast?: boolean;
  art?: ShortArt;
};

// Visual cuts grouped by narration line (L1..L5). Within a line they split the time evenly.
const CUTS: Cut[] = [
  // L1 — hook: "your phone records everywhere you go / 127 days, no warrant"
  {line: 'L1', id: 'hook', src: img('01'), kind: 'image', motion: 'pushin', fast: true,
   telop: 'YOUR PHONE\nTRACKS YOU', art: {kind: 'bignum', top: '127 DAYS', bottom: 'NO WARRANT'}},
  {line: 'L1', id: 'h2', src: img('02'), kind: 'image', motion: 'parallax'},
  // L2 — "every few minutes it pings a nearby cell tower"
  {line: 'L2', id: 'b1', src: img('03'), kind: 'image', motion: 'kenburns', telop: 'PINGS A TOWER\nEVERY FEW MIN'},
  // L3 — "months of history from the carrier -> suspect near the scene"
  {line: 'L3', id: 'b2a', src: img('04'), kind: 'image', motion: 'kenburns', telop: 'MONTHS OF\nLOCATION DATA'},
  {line: 'L3', id: 'b2b', src: img('05'), kind: 'image', motion: 'pushin',
   art: {kind: 'diagram', steps: ['Carrier', 'Months of history', 'Suspect near the scene']}},
  // L4 — climax: "2018 SCOTUS no, 5-4, warrant needed, digital trail protected"
  {line: 'L4', id: 'c1', src: img('06'), kind: 'image', motion: 'kenburns',
   telop: '2018: 5-4\nGET A WARRANT', art: {kind: 'vote', yes: 5, no: 4}},
  {line: 'L4', id: 'c2', src: img('07'), kind: 'image', motion: 'pushin',
   art: {kind: 'citation', label: 'Carpenter v. United States', source: '2018'}},
  {line: 'L4', id: 'c3', src: img('07'), kind: 'image', motion: 'parallax', telop: 'YOUR DIGITAL\nTRAIL, PROTECTED'},
  // L5 — CTA (platform-specific endcard text swapped at export)
  {line: 'L5', id: 'cta', src: img('01'), kind: 'image', motion: 'kenburns'},
];

/** Lay each line's cuts continuously across [line.start, nextLine.start) (last -> total). */
const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const spanStart = win.start;
    const spanEnd = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT08_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    const each = (spanEnd - spanStart) / Math.max(1, cuts.length);
    cuts.forEach((cut, k) => {
      const {line: _line, ...rest} = cut;
      beats.push({...rest, startSec: r3(spanStart + k * each), durSec: r3(each)});
    });
  });
  return beats;
};

export const SHORT08: ShortData = {
  shortId: 'short08',
  episodeId: 'PD-2026-008-carpenter',
  durationSec: SHORT08_TOTAL_SEC,
  narrationSrc: 'shorts/short08/audio/short08_final_mix_v002_en_us.mp3', // full 4-layer mix
  captions: SHORT08_CAPTIONS,
  bgmSrc: null, // BGM/ambience/SFX already inside the mix
  ctaTextYT: 'Watch on YouTube',
  ctaTextTT: 'Full episode on our profile',
  beats: buildBeats(),
};
