import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT301_CAPTIONS, SHORT301_TOTAL_SEC} from './short301_timing';

/**
 * short301 — The inspection found broken wires; the company's own manual says broken wires are a seventy, and a seventy means measures up to closing the road; the number written in the box was forty.
 * Episode PD-2026-076-morandi.  Type ?.
 *
 * AVOIDS: Names nobody and blames nobody by name; the scores, the manual's definitions and the commission's corrections are quoted as the record's own sentences. Does not say the collapse was foreseen, does not state a cause, does not mention the dead - this Short stays entirely inside the inspection paperwork.
 * LEAVES FOR THE LONG-FORM: What was inside the concrete the inspectors were scoring - and what happened the one time anybody cut into it?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-076-morandi.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short301/short301_01.png', kind: 'image', motion: 'parallax', fast: true},   // close on a concrete beam where the cover has broken away, 
  {line: 'L1', id: 'p02', src: 'shorts/short301/short301_02.png', kind: 'image', motion: 'kenburns', fast: true},   // macro of a bundle of high-tensile steel wires inside broke
  {line: 'L2', id: 'p03', src: 'shorts/short301/short301_03.png', kind: 'image', motion: 'pushin', fast: true},   // a hand holding a ballpoint pen above one empty ruled box o
  {line: 'L2', id: 'p04', src: 'shorts/short301/short301_04.png', kind: 'image', motion: 'parallax'},   // extreme close on one empty ruled box on a printed inspecti
  {line: 'L3', id: 'p05', src: 'shorts/short301/short301_05.png', kind: 'image', motion: 'kenburns'},   // a plain ring-bound technical manual lying open on a lamina
  {line: 'L3', id: 'p06', src: 'shorts/short301/short301_06.png', kind: 'image', motion: 'pushin'},   // a printed table on a plain sheet: ruled rows and columns
  {line: 'L4', id: 'p07', src: 'shorts/short301/short301_07.png', kind: 'image', motion: 'parallax'},   // a clipboard carrying a blank ruled form, hooked over a rai
  {line: 'L4', id: 'p08', src: 'shorts/short301/short301_08.png', kind: 'image', motion: 'kenburns'},   // a printed form with a large empty ruled observations area
  {line: 'L5', id: 'p09', src: 'shorts/short301/short301_09.png', kind: 'image', motion: 'pushin'},   // close on a bundle of prestressing strands inside broken co
  {line: 'L6', id: 'p10', src: 'shorts/short301/short301_10.png', kind: 'image', motion: 'parallax'},   // close inside a concrete box girder chamber - prestressing 
  {line: 'L6', id: 'p11', src: 'shorts/short301/short301_11.png', kind: 'image', motion: 'kenburns'},   // close on prestressing strands gone visibly slack inside a 
  {line: 'L7', id: 'p12', src: 'shorts/short301/short301_12.png', kind: 'image', motion: 'pushin'},   // macro of seven-wire steel strand, rust-brown and deeply pi
  {line: 'L8', id: 'p13', src: 'shorts/short301/short301_13.png', kind: 'image', motion: 'parallax'},   // a blank graph grid printed on a plain sheet, axes ruled, n
  {line: 'L8', id: 'p14', src: 'shorts/short301/short301_14.png', kind: 'image', motion: 'kenburns', isCta: true, rewind: true, fast: true},   // a rubber date stamp lying on an ink pad beside a blank doc
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT301_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT301: ShortData = {
  shortId: 'short301',
  episodeId: 'PD-2026-076-morandi',
  durationSec: SHORT301_TOTAL_SEC,
  narrationSrc: 'shorts/short301/audio/short301_final_mix_v002_en_us.mp3',
  captions: SHORT301_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short301/short301_ctathumb.jpg',
  ctaLongTitle: "Genoa's Motorway Viaduct Got 23,000...",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short301.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short301/short301_kin_close_the_road.webm', atSec: 17.88, durSec: 2.2, phrase: "SEVENTY CLOSE THE ROAD"},
    {src: 'shorts/short301/short301_kin_number_in_box.webm', atSec: 47.94, durSec: 2.4, phrase: "A NUMBER IN A BOX"},
  ],
};
