import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT115_CAPTIONS, SHORT115_TOTAL_SEC} from './short115_timing';

/**
 * short115 — Forfeiture works by filing the case against your property instead of against you, which is the exact mechanism that lets 'innocent until proven guilty' stop applying.
 * Episode PD-2026-009-timbs.  Type A — second-person threat ('this can reach you').
 *
 * AVOIDS: The existing Short tells the seizure story and the nine to nothing outcome. It never explains the legal fiction that makes seizure possible without a conviction, or why forfeiture cases are captioned against objects.
 * LEAVES FOR THE LONG-FORM: Where the limit on all of this finally came from, and why it is older than the country.
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-009-timbs.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short115/short115_01.png', kind: 'image', motion: 'parallax', fast: true},   // a dark SUV standing alone in a floodlit impound lot
  {line: 'L1', id: 'p02', src: 'shorts/short115/short115_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a set of car keys on a bare steel counter
  {line: 'L1', id: 'p04', src: 'shorts/short115/short115_04.png', kind: 'image', motion: 'parallax'},   // a dry rectangle on a wet driveway where a vehicle stood
  {line: 'L2', id: 'p05', src: 'shorts/short115/short115_05.png', kind: 'image', motion: 'kenburns'},   // a printed form with every field worn blank
  {line: 'L2', id: 'p06', src: 'shorts/short115/fx/fx_06.mp4', kind: 'video', motion: 'video'},   // a hand signing paperwork on a clipboard
  {line: 'L2', id: 'p07', src: 'shorts/short115/short115_07.png', kind: 'image', motion: 'parallax'},   // an empty counsel chair with a single car key on the table 
  {line: 'L2', id: 'p08', src: 'shorts/short115/short115_08.png', kind: 'image', motion: 'kenburns'},   // an evidence tag tied to a car door handle
  {line: 'L2', id: 'p09', src: 'shorts/short115/short115_09.png', kind: 'image', motion: 'pushin'},   // a tow hook clamped under a front wheel at night
  {line: 'L2', id: 'p10', src: 'shorts/short115/fx/fx_10.mp4', kind: 'video', motion: 'video'},   // a recovery truck lifting a car under sodium light
  {line: 'L2', id: 'p11', src: 'shorts/short115/short115_11.png', kind: 'image', motion: 'kenburns'},   // a chain and padlock across an impound gate
  {line: 'L3', id: 'p12', src: 'shorts/short115/short115_12.png', kind: 'image', motion: 'pushin'},   // an open case folder holding a photograph of a vehicle
  {line: 'L3', id: 'p13', src: 'shorts/short115/fx/fx_13.mp4', kind: 'video', motion: 'video'},   // an empty judge's bench in a dark courtroom
  {line: 'L3', id: 'p14', src: 'shorts/short115/short115_14.png', kind: 'image', motion: 'kenburns'},   // a small house behind a chain link fence at dusk
  {line: 'L3', id: 'p15', src: 'shorts/short115/short115_15.png', kind: 'image', motion: 'pushin'},   // rows of seized vehicles inside a floodlit compound
  {line: 'L3', id: 'p16', src: 'shorts/short115/fx/fx_16.mp4', kind: 'video', motion: 'video'},   // a wide parking area of cars under night lights
  {line: 'L4', id: 'p17', src: 'shorts/short115/short115_17.png', kind: 'image', motion: 'kenburns'},   // an empty jury box of twelve chairs
  {line: 'L4', id: 'p18', src: 'shorts/short115/short115_18.png', kind: 'image', motion: 'pushin'},   // a wall of numbered lock boxes with one drawer open and emp
  {line: 'L4', id: 'p19', src: 'shorts/short115/fx/fx_19.mp4', kind: 'video', motion: 'video'},   // keys lying on a bare table under one lamp
  {line: 'L4', id: 'p20', src: 'shorts/short115/short115_20.png', kind: 'image', motion: 'kenburns'},   // an empty driver's seat with the dome light on
  {line: 'L4', id: 'p21', src: 'shorts/short115/fx/fx_21.mp4', kind: 'video', motion: 'video'},   // a counter of unclaimed property under one strip light
  {line: 'L4', id: 'p22', src: 'shorts/short115/short115_22.png', kind: 'image', motion: 'parallax'},   // a vehicle silhouette receding behind a closing gate
  {line: 'L8', id: 'p23', src: 'shorts/short115/short115_04.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short115/short115_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short115/short115_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to plate 01: a dark SUV standing alone in a floodli
  {line: 'L5', id: 'p26', src: 'shorts/short115/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // an open duffel bag packed with bundled money
  {line: 'L5', id: 'p27', src: 'shorts/short115/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // shelves of stacked boxes in an evidence store
  {line: 'L5', id: 'p28', src: 'shorts/short115/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a heavy steel security door with a throw bolt
  {line: 'L5', id: 'p29', src: 'shorts/short115/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // a patrol car parked at a kerb in daylight
  {line: 'L5', id: 'p30', src: 'shorts/short115/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // a counting machine running banknotes through
  {line: 'L6', id: 'p31', src: 'shorts/short115/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // coins dropping one by one into a glass jar
  {line: 'L6', id: 'p32', src: 'shorts/short115/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // hands laying banknotes into a cash drawer
  {line: 'L6', id: 'p33', src: 'shorts/short115/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // the entrance doors of a police station by day
  {line: 'L6', id: 'p34', src: 'shorts/short115/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // a garage door rolling up on a vehicle bay
  {line: 'L6', id: 'p35', src: 'shorts/short115/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // a steel cash box unlocked and opened on a desk
  {line: 'L7', id: 'p36', src: 'shorts/short115/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // rows of empty seats in a public meeting hall
  {line: 'L7', id: 'p37', src: 'shorts/short115/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // stone courthouse steps and columns in daylight
  {line: 'L7', id: 'p38', src: 'shorts/short115/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // coins stacked into rising columns on a desk
  {line: 'L7', id: 'p39', src: 'shorts/short115/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // two microphones set side by side on a table
  {line: 'L7', id: 'p40', src: 'shorts/short115/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a hand pressing a stamp down onto blank paper
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT115_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT115: ShortData = {
  shortId: 'short115',
  episodeId: 'PD-2026-009-timbs',
  durationSec: SHORT115_TOTAL_SEC,
  narrationSrc: 'shorts/short115/audio/short115_final_mix_v002_en_us.mp3',
  captions: SHORT115_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short115/short115_ctathumb.jpg',
  ctaLongTitle: "Police Took His $42,000 Car. The",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short115.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short115/short115_kin_a.webm', atSec: 14.0, durSec: 2.3, phrase: "THE PROPERTY IS THE SUSPECT"},
    {src: 'shorts/short115/short115_kin_b.webm', atSec: 42.1, durSec: 2.3, phrase: "POLICING FOR PROFIT"},
  ],
};
