// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #143.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT143_TOTAL_SEC = 39.635;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.851
  },
  {
    "id": "L2",
    "start": 6.071,
    "end": 14.105
  },
  {
    "id": "L3",
    "start": 14.325,
    "end": 22.824
  },
  {
    "id": "L4",
    "start": 23.044,
    "end": 31.728
  },
  {
    "id": "L5",
    "start": 31.948,
    "end": 38.635
  }
];

export const SHORT143_CAPTIONS: ShortCaption[] = [
  {
    "word": "The Supreme Court let a",
    "startSec": 0.0,
    "endSec": 1.258
  },
  {
    "word": "deputy stop a truck without",
    "startSec": 1.258,
    "endSec": 2.734
  },
  {
    "word": "ever looking at the driver.",
    "startSec": 2.734,
    "endSec": 4.211
  },
  {
    "word": "One word in the record is why.",
    "startSec": 4.211,
    "endSec": 5.851
  },
  {
    "word": "Justice Elena Kagan wrote separately",
    "startSec": 6.071,
    "endSec": 8.167
  },
  {
    "word": "joined by Justice Ruth Bader Ginsburg",
    "startSec": 8.167,
    "endSec": 10.321
  },
  {
    "word": "to underline how little it takes",
    "startSec": 10.321,
    "endSec": 12.184
  },
  {
    "word": "to break the officer's inference.",
    "startSec": 12.184,
    "endSec": 14.105
  },
  {
    "word": "What made this stop reasonable she stressed",
    "startSec": 14.325,
    "endSec": 17.052
  },
  {
    "word": "was that the license was revoked.",
    "startSec": 17.052,
    "endSec": 19.145
  },
  {
    "word": "In Kansas that signals a driver",
    "startSec": 19.145,
    "endSec": 21.112
  },
  {
    "word": "who keeps ignoring the law.",
    "startSec": 21.112,
    "endSec": 22.824
  },
  {
    "word": "If the license had merely been suspended",
    "startSec": 23.044,
    "endSec": 25.456
  },
  {
    "word": "over something like an unpaid fee",
    "startSec": 25.456,
    "endSec": 27.446
  },
  {
    "word": "the case for assuming he was still",
    "startSec": 27.446,
    "endSec": 29.497
  },
  {
    "word": "behind the wheel would be far weaker.",
    "startSec": 29.497,
    "endSec": 31.728
  },
  {
    "word": "Revoked.",
    "startSec": 31.948,
    "endSec": 32.648
  },
  {
    "word": "That was the word.",
    "startSec": 32.648,
    "endSec": 33.677
  },
  {
    "word": "And a single glance showing the",
    "startSec": 33.677,
    "endSec": 35.449
  },
  {
    "word": "driver is not the owner is",
    "startSec": 35.449,
    "endSec": 36.935
  },
  {
    "word": "enough to wipe the suspicion away.",
    "startSec": 36.935,
    "endSec": 38.635
  }
];
