// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #297.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT297_TOTAL_SEC = 54.276;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 12.678
  },
  {
    "id": "L2",
    "start": 12.898,
    "end": 19.307
  },
  {
    "id": "L3",
    "start": 19.527,
    "end": 24.682
  },
  {
    "id": "L4",
    "start": 24.902,
    "end": 27.828
  },
  {
    "id": "L5",
    "start": 28.048,
    "end": 33.064
  },
  {
    "id": "L6",
    "start": 33.284,
    "end": 41.272
  },
  {
    "id": "L7",
    "start": 41.492,
    "end": 46.09
  },
  {
    "id": "L8",
    "start": 46.31,
    "end": 53.276
  }
];

export const SHORT297_CAPTIONS: ShortCaption[] = [
  {
    "word": "A hundred and fifty-nine people died.",
    "startSec": 0.0,
    "endSec": 2.896
  },
  {
    "word": "A court convicted one official acquitted another",
    "startSec": 2.896,
    "endSec": 6.652
  },
  {
    "word": "and explained the difference",
    "startSec": 6.652,
    "endSec": 8.843
  },
  {
    "word": "in one sentence",
    "startSec": 8.843,
    "endSec": 10.017
  },
  {
    "word": "about who the law was written for.",
    "startSec": 10.017,
    "endSec": 12.678
  },
  {
    "word": "Nobody organised it.",
    "startSec": 12.898,
    "endSec": 13.635
  },
  {
    "word": "There was no ticket no promoter",
    "startSec": 13.635,
    "endSec": 14.776
  },
  {
    "word": "no stage no permit",
    "startSec": 14.776,
    "endSec": 15.476
  },
  {
    "word": "no name on anything.",
    "startSec": 15.476,
    "endSec": 16.213
  },
  {
    "word": "Hold on to that",
    "startSec": 16.213,
    "endSec": 16.913
  },
  {
    "word": "because in two years' time",
    "startSec": 16.913,
    "endSec": 17.871
  },
  {
    "word": "a court is going to build",
    "startSec": 17.871,
    "endSec": 18.792
  },
  {
    "word": "an acquittal on it.",
    "startSec": 18.792,
    "endSec": 19.307
  },
  {
    "word": "The chief of the ward office",
    "startSec": 19.527,
    "endSec": 20.985
  },
  {
    "word": "and other ward officials were indicted.",
    "startSec": 20.985,
    "endSec": 23.016
  },
  {
    "word": "The court found them not guilty.",
    "startSec": 23.016,
    "endSec": 24.682
  },
  {
    "word": "Not insufficient evidence.",
    "startSec": 24.902,
    "endSec": 26.17
  },
  {
    "word": "Something more specific than that.",
    "startSec": 26.17,
    "endSec": 27.828
  },
  {
    "word": "Related law",
    "startSec": 28.048,
    "endSec": 28.748
  },
  {
    "word": "and regulations did not require them",
    "startSec": 28.748,
    "endSec": 30.42
  },
  {
    "word": "to come up with safety measures",
    "startSec": 30.42,
    "endSec": 31.86
  },
  {
    "word": "for events without organizers.",
    "startSec": 31.86,
    "endSec": 33.064
  },
  {
    "word": "A hundred thousand people walking",
    "startSec": 33.284,
    "endSec": 35.222
  },
  {
    "word": "into a district",
    "startSec": 35.222,
    "endSec": 36.103
  },
  {
    "word": "because it is the twenty-ninth",
    "startSec": 36.103,
    "endSec": 37.865
  },
  {
    "word": "of October is not anybody's event.",
    "startSec": 37.865,
    "endSec": 39.862
  },
  {
    "word": "There is no form for it.",
    "startSec": 39.862,
    "endSec": 41.272
  },
  {
    "word": "And so",
    "startSec": 41.492,
    "endSec": 42.192
  },
  {
    "word": "in the judgment of that court",
    "startSec": 42.192,
    "endSec": 43.838
  },
  {
    "word": "there was no duty attached to it.",
    "startSec": 43.838,
    "endSec": 45.711
  },
  {
    "word": "There is now.",
    "startSec": 45.711,
    "endSec": 46.09
  },
  {
    "word": "The law now knows",
    "startSec": 46.31,
    "endSec": 47.281
  },
  {
    "word": "that a crowd can happen without anybody",
    "startSec": 47.281,
    "endSec": 49.508
  },
  {
    "word": "calling it an event.",
    "startSec": 49.508,
    "endSec": 50.649
  },
  {
    "word": "On the night this film is about",
    "startSec": 50.649,
    "endSec": 52.42
  },
  {
    "word": "it was not law.",
    "startSec": 52.42,
    "endSec": 53.276
  }
];
