// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #120.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT120_TOTAL_SEC = 62.075;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 3.715
  },
  {
    "id": "L2",
    "start": 3.935,
    "end": 14.059
  },
  {
    "id": "L3",
    "start": 14.279,
    "end": 22.034
  },
  {
    "id": "L4",
    "start": 22.254,
    "end": 33.353
  },
  {
    "id": "L5",
    "start": 33.573,
    "end": 38.774
  },
  {
    "id": "L6",
    "start": 38.994,
    "end": 47.214
  },
  {
    "id": "L7",
    "start": 47.434,
    "end": 55.654
  },
  {
    "id": "L8",
    "start": 55.874,
    "end": 61.075
  }
];

export const SHORT120_CAPTIONS: ShortCaption[] = [
  {
    "word": "The Court protected the student and refused",
    "startSec": 0.0,
    "endSec": 2.188
  },
  {
    "word": "to tell you where the line is.",
    "startSec": 2.188,
    "endSec": 3.715
  },
  {
    "word": "It pointedly did not say that schools",
    "startSec": 3.935,
    "endSec": 6.178
  },
  {
    "word": "can never reach off campus speech.",
    "startSec": 6.178,
    "endSec": 8.239
  },
  {
    "word": "It listed what might",
    "startSec": 8.239,
    "endSec": 9.452
  },
  {
    "word": "still justify stepping in.",
    "startSec": 9.452,
    "endSec": 11.028
  },
  {
    "word": "Serious bullying or harassment. Threats. Cheating.",
    "startSec": 11.028,
    "endSec": 14.059
  },
  {
    "word": "Then it declined to",
    "startSec": 14.279,
    "endSec": 15.477
  },
  {
    "word": "draw one bright line.",
    "startSec": 15.477,
    "endSec": 16.801
  },
  {
    "word": "The result is a gray zone every",
    "startSec": 16.801,
    "endSec": 18.755
  },
  {
    "word": "student and parent now lives in",
    "startSec": 18.755,
    "endSec": 20.71
  },
  {
    "word": "decided post by post.",
    "startSec": 20.71,
    "endSec": 22.034
  },
  {
    "word": "And notice what the Court protected.",
    "startSec": 22.254,
    "endSec": 24.524
  },
  {
    "word": "Not a noble political statement. A crude",
    "startSec": 24.524,
    "endSec": 27.047
  },
  {
    "word": "throwaway post that vanished in seconds.",
    "startSec": 27.047,
    "endSec": 29.569
  },
  {
    "word": "On purpose.",
    "startSec": 29.569,
    "endSec": 30.269
  },
  {
    "word": "Free speech is tested by",
    "startSec": 30.269,
    "endSec": 31.783
  },
  {
    "word": "the speech we find petty.",
    "startSec": 31.783,
    "endSec": 33.353
  },
  {
    "word": "The post went out to about",
    "startSec": 33.573,
    "endSec": 34.582
  },
  {
    "word": "two hundred and fifty friends and",
    "startSec": 34.582,
    "endSec": 35.863
  },
  {
    "word": "was supposed to vanish.",
    "startSec": 35.863,
    "endSec": 36.756
  },
  {
    "word": "Someone took a screenshot",
    "startSec": 36.756,
    "endSec": 37.726
  },
  {
    "word": "and it reached the coaches.",
    "startSec": 37.726,
    "endSec": 38.774
  },
  {
    "word": "After Mahanoy",
    "startSec": 38.994,
    "endSec": 39.822
  },
  {
    "word": "a public school cannot punish a",
    "startSec": 39.822,
    "endSec": 41.798
  },
  {
    "word": "student simply for an ordinary off campus",
    "startSec": 41.798,
    "endSec": 44.41
  },
  {
    "word": "online vent that does",
    "startSec": 44.41,
    "endSec": 45.748
  },
  {
    "word": "not disrupt the school.",
    "startSec": 45.748,
    "endSec": 47.214
  },
  {
    "word": "The alternative was a school reaching a",
    "startSec": 47.434,
    "endSec": 49.724
  },
  {
    "word": "student's words twenty-four hours a day anywhere",
    "startSec": 49.724,
    "endSec": 52.542
  },
  {
    "word": "because almost anything said",
    "startSec": 52.542,
    "endSec": 54.186
  },
  {
    "word": "online could ripple back.",
    "startSec": 54.186,
    "endSec": 55.654
  },
  {
    "word": "So the gray zone",
    "startSec": 55.874,
    "endSec": 56.809
  },
  {
    "word": "is not an accident.",
    "startSec": 56.809,
    "endSec": 57.919
  },
  {
    "word": "It is what eight justices",
    "startSec": 57.919,
    "endSec": 59.38
  },
  {
    "word": "decided they could live with.",
    "startSec": 59.38,
    "endSec": 61.075
  }
];
