// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #14.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT14_TOTAL_SEC = 42.765;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.573
  },
  {
    "id": "L2",
    "start": 8.073,
    "end": 14.157
  },
  {
    "id": "L3",
    "start": 16.657,
    "end": 20.651
  },
  {
    "id": "L4",
    "start": 23.151,
    "end": 36.061
  },
  {
    "id": "L5",
    "start": 38.561,
    "end": 41.765
  }
];

export const SHORT14_CAPTIONS: ShortCaption[] = [
  {
    "word": "An officer chases you over something minor, and you step inside your home.",
    "startSec": 0.0,
    "endSec": 4.341
  },
  {
    "word": "Can he follow you in?",
    "startSec": 4.341,
    "endSec": 5.573
  },
  {
    "word": "One man was just playing his music too loud.",
    "startSec": 8.073,
    "endSec": 10.361
  },
  {
    "word": "An officer flipped on his lights, and the man pulled into his own garage.",
    "startSec": 10.361,
    "endSec": 14.157
  },
  {
    "word": "The officer stuck his foot under the closing garage door, and walked right in.",
    "startSec": 16.657,
    "endSec": 20.651
  },
  {
    "word": "In 2021, the Supreme Court said no: chasing a minor offense, by itself, does not automatically let police enter your home.",
    "startSec": 23.151,
    "endSec": 30.214
  },
  {
    "word": "They need a warrant, or a real emergency.",
    "startSec": 30.214,
    "endSec": 32.587
  },
  {
    "word": "Your home is still the hardest place for the state to enter.",
    "startSec": 32.587,
    "endSec": 36.061
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 38.561,
    "endSec": 40.779
  },
  {
    "word": "Follow for more.",
    "startSec": 40.779,
    "endSec": 41.765
  }
];
