// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #178.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT178_TOTAL_SEC = 43.955;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 4.412
  },
  {
    "id": "L2",
    "start": 4.632,
    "end": 14.338
  },
  {
    "id": "L3",
    "start": 14.558,
    "end": 24.914
  },
  {
    "id": "L4",
    "start": 25.134,
    "end": 35.351
  },
  {
    "id": "L5",
    "start": 35.571,
    "end": 42.955
  }
];

export const SHORT178_CAPTIONS: ShortCaption[] = [
  {
    "word": "Every side of this argument",
    "startSec": 0.0,
    "endSec": 1.752
  },
  {
    "word": "quotes the same sentence",
    "startSec": 1.752,
    "endSec": 3.309
  },
  {
    "word": "from a 1960 case.",
    "startSec": 3.309,
    "endSec": 4.412
  },
  {
    "word": "The Takings Clause was designed to",
    "startSec": 4.632,
    "endSec": 6.529
  },
  {
    "word": "bar Government from forcing some people",
    "startSec": 6.529,
    "endSec": 8.704
  },
  {
    "word": "alone to bear public burdens which",
    "startSec": 8.704,
    "endSec": 10.601
  },
  {
    "word": "in all fairness and justice",
    "startSec": 10.601,
    "endSec": 12.107
  },
  {
    "word": "should be borne by the",
    "startSec": 12.107,
    "endSec": 13.334
  },
  {
    "word": "public as a whole.",
    "startSec": 13.334,
    "endSec": 14.338
  },
  {
    "word": "Some people alone.",
    "startSec": 14.558,
    "endSec": 15.681
  },
  {
    "word": "In November 2024",
    "startSec": 15.681,
    "endSec": 16.679
  },
  {
    "word": "when the Supreme Court declined",
    "startSec": 16.679,
    "endSec": 18.613
  },
  {
    "word": "one of these cases",
    "startSec": 18.613,
    "endSec": 19.736
  },
  {
    "word": "Justice Sotomayor wrote a",
    "startSec": 19.736,
    "endSec": 21.296
  },
  {
    "word": "statement respecting that denial",
    "startSec": 21.296,
    "endSec": 23.292
  },
  {
    "word": "joined by Justice Gorsuch.",
    "startSec": 23.292,
    "endSec": 24.914
  },
  {
    "word": "She wrote that the question",
    "startSec": 25.134,
    "endSec": 26.563
  },
  {
    "word": "divides the courts of appeals",
    "startSec": 26.563,
    "endSec": 28.099
  },
  {
    "word": "and that it would benefit from",
    "startSec": 28.099,
    "endSec": 29.687
  },
  {
    "word": "further percolation in the lower courts",
    "startSec": 29.687,
    "endSec": 31.751
  },
  {
    "word": "before the Court steps in.",
    "startSec": 31.751,
    "endSec": 33.128
  },
  {
    "word": "The denial expressed no",
    "startSec": 33.128,
    "endSec": 34.345
  },
  {
    "word": "view on the merits.",
    "startSec": 34.345,
    "endSec": 35.351
  },
  {
    "word": "So the sentence stands",
    "startSec": 35.571,
    "endSec": 36.914
  },
  {
    "word": "and so does the split.",
    "startSec": 36.914,
    "endSec": 38.256
  },
  {
    "word": "She cited one Colorado case by name",
    "startSec": 38.256,
    "endSec": 40.392
  },
  {
    "word": "where a family alone",
    "startSec": 40.392,
    "endSec": 41.612
  },
  {
    "word": "bore the whole burden.",
    "startSec": 41.612,
    "endSec": 42.955
  }
];
