// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #274.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT274_TOTAL_SEC = 26.319;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 2.972
  },
  {
    "id": "L2",
    "start": 3.192,
    "end": 6.118
  },
  {
    "id": "L3",
    "start": 6.338,
    "end": 8.753
  },
  {
    "id": "L4",
    "start": 8.973,
    "end": 13.292
  },
  {
    "id": "L5",
    "start": 13.512,
    "end": 15.37
  },
  {
    "id": "L6",
    "start": 15.59,
    "end": 18.191
  },
  {
    "id": "L7",
    "start": 18.411,
    "end": 22.266
  },
  {
    "id": "L8",
    "start": 22.486,
    "end": 25.319
  }
];

export const SHORT274_CAPTIONS: ShortCaption[] = [
  {
    "word": "Dublin California. February 27th 2011.",
    "startSec": 0.0,
    "endSec": 2.972
  },
  {
    "word": "Sergio Ramirez has come to",
    "startSec": 3.192,
    "endSec": 4.846
  },
  {
    "word": "buy a Nissan Maxima.",
    "startSec": 4.846,
    "endSec": 6.118
  },
  {
    "word": "His wife is with him",
    "startSec": 6.338,
    "endSec": 7.488
  },
  {
    "word": "and his father-in-law.",
    "startSec": 7.488,
    "endSec": 8.753
  },
  {
    "word": "The salesman runs a credit check",
    "startSec": 8.973,
    "endSec": 10.866
  },
  {
    "word": "and says Nissan will not",
    "startSec": 10.866,
    "endSec": 12.286
  },
  {
    "word": "sell him the car.",
    "startSec": 12.286,
    "endSec": 13.292
  },
  {
    "word": "His name is on a terrorist list.",
    "startSec": 13.512,
    "endSec": 15.37
  },
  {
    "word": "The list is real",
    "startSec": 15.59,
    "endSec": 16.475
  },
  {
    "word": "and it belongs to the Treasury.",
    "startSec": 16.475,
    "endSec": 18.191
  },
  {
    "word": "It is generally unlawful to transact business",
    "startSec": 18.411,
    "endSec": 20.787
  },
  {
    "word": "with any person on the list.",
    "startSec": 20.787,
    "endSec": 22.266
  },
  {
    "word": "The letter that follows will not",
    "startSec": 22.486,
    "endSec": 24.076
  },
  {
    "word": "say how to argue with it.",
    "startSec": 24.076,
    "endSec": 25.319
  }
];
