// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #131.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT131_TOTAL_SEC = 64.164;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.944
  },
  {
    "id": "L2",
    "start": 6.164,
    "end": 15.127
  },
  {
    "id": "L3",
    "start": 15.347,
    "end": 22.359
  },
  {
    "id": "L4",
    "start": 22.579,
    "end": 29.638
  },
  {
    "id": "L5",
    "start": 29.858,
    "end": 38.031
  },
  {
    "id": "L6",
    "start": 38.251,
    "end": 45.774
  },
  {
    "id": "L7",
    "start": 45.994,
    "end": 55.096
  },
  {
    "id": "L8",
    "start": 55.316,
    "end": 63.164
  }
];

export const SHORT131_CAPTIONS: ShortCaption[] = [
  {
    "word": "The Supreme Court compared a",
    "startSec": 0.0,
    "endSec": 1.585
  },
  {
    "word": "DNA swab to a fingerprint.",
    "startSec": 1.585,
    "endSec": 3.057
  },
  {
    "word": "Look at how far apart",
    "startSec": 3.057,
    "endSec": 4.246
  },
  {
    "word": "those two things actually are.",
    "startSec": 4.246,
    "endSec": 5.944
  },
  {
    "word": "A fingerprint reveals almost nothing about",
    "startSec": 6.164,
    "endSec": 8.608
  },
  {
    "word": "you except its own pattern.",
    "startSec": 8.608,
    "endSec": 10.18
  },
  {
    "word": "DNA is a blueprint that",
    "startSec": 10.18,
    "endSec": 11.519
  },
  {
    "word": "can expose your relatives your health",
    "startSec": 11.519,
    "endSec": 13.672
  },
  {
    "word": "your most private traits.",
    "startSec": 13.672,
    "endSec": 15.127
  },
  {
    "word": "The majority answered that the law reads",
    "startSec": 15.347,
    "endSec": 17.627
  },
  {
    "word": "only a narrow set of identifying markers",
    "startSec": 17.627,
    "endSec": 19.908
  },
  {
    "word": "not your whole genome.",
    "startSec": 19.908,
    "endSec": 21.162
  },
  {
    "word": "That was the promise.",
    "startSec": 21.162,
    "endSec": 22.359
  },
  {
    "word": "But critics answered that the",
    "startSec": 22.579,
    "endSec": 24.191
  },
  {
    "word": "physical sample itself is kept.",
    "startSec": 24.191,
    "endSec": 25.914
  },
  {
    "word": "And that the line",
    "startSec": 25.914,
    "endSec": 26.859
  },
  {
    "word": "the state draws today",
    "startSec": 26.859,
    "endSec": 28.026
  },
  {
    "word": "it can quietly move tomorrow.",
    "startSec": 28.026,
    "endSec": 29.638
  },
  {
    "word": "In much of the country",
    "startSec": 29.858,
    "endSec": 31.422
  },
  {
    "word": "being arrested for a serious offense now",
    "startSec": 31.422,
    "endSec": 34.264
  },
  {
    "word": "means giving a sample before any trial",
    "startSec": 34.264,
    "endSec": 36.965
  },
  {
    "word": "and it is kept.",
    "startSec": 36.965,
    "endSec": 38.031
  },
  {
    "word": "The people swept into those",
    "startSec": 38.251,
    "endSec": 39.712
  },
  {
    "word": "databases include the merely arrested",
    "startSec": 39.712,
    "endSec": 41.715
  },
  {
    "word": "whose genetic code is on file because",
    "startSec": 41.715,
    "endSec": 43.717
  },
  {
    "word": "of a single encounter with the police.",
    "startSec": 43.717,
    "endSec": 45.774
  },
  {
    "word": "The other side is real.",
    "startSec": 45.994,
    "endSec": 47.399
  },
  {
    "word": "DNA databases have closed cold cases",
    "startSec": 47.399,
    "endSec": 49.598
  },
  {
    "word": "freed innocent people",
    "startSec": 49.598,
    "endSec": 50.881
  },
  {
    "word": "and identified violent offenders who",
    "startSec": 50.881,
    "endSec": 53.08
  },
  {
    "word": "would otherwise have walked free.",
    "startSec": 53.08,
    "endSec": 55.096
  },
  {
    "word": "The Court weighed that risk against a",
    "startSec": 55.316,
    "endSec": 57.252
  },
  {
    "word": "public interest and called the swab reasonable.",
    "startSec": 57.252,
    "endSec": 59.711
  },
  {
    "word": "Whether that holds depends on what",
    "startSec": 59.711,
    "endSec": 61.49
  },
  {
    "word": "you think a swab actually takes.",
    "startSec": 61.49,
    "endSec": 63.164
  }
];
