// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #303.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT303_TOTAL_SEC = 51.766;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.573
  },
  {
    "id": "L2",
    "start": 5.793,
    "end": 11.877
  },
  {
    "id": "L3",
    "start": 12.097,
    "end": 20.317
  },
  {
    "id": "L4",
    "start": 20.537,
    "end": 26.481
  },
  {
    "id": "L5",
    "start": 26.701,
    "end": 30.881
  },
  {
    "id": "L6",
    "start": 31.101,
    "end": 34.212
  },
  {
    "id": "L7",
    "start": 34.432,
    "end": 39.958
  },
  {
    "id": "L8",
    "start": 40.178,
    "end": 50.766
  }
];

export const SHORT303_CAPTIONS: ShortCaption[] = [
  {
    "word": "The commission asked the company",
    "startSec": 0.0,
    "endSec": 1.564
  },
  {
    "word": "for everything it had spent",
    "startSec": 1.564,
    "endSec": 2.884
  },
  {
    "word": "on structural work on the whole viaduct",
    "startSec": 2.884,
    "endSec": 4.791
  },
  {
    "word": "and totalled it.",
    "startSec": 4.791,
    "endSec": 5.573
  },
  {
    "word": "From 1982 to 2018: twenty-four million",
    "startSec": 5.793,
    "endSec": 8.513
  },
  {
    "word": "six hundred and ten thousand",
    "startSec": 8.513,
    "endSec": 10.517
  },
  {
    "word": "five hundred euros.",
    "startSec": 10.517,
    "endSec": 11.877
  },
  {
    "word": "Ninety-eight per cent of that was spent",
    "startSec": 12.097,
    "endSec": 14.814
  },
  {
    "word": "before 1999",
    "startSec": 14.814,
    "endSec": 15.58
  },
  {
    "word": "the year the motorway company was privatised.",
    "startSec": 15.58,
    "endSec": 18.715
  },
  {
    "word": "After 1999",
    "startSec": 18.715,
    "endSec": 19.415
  },
  {
    "word": "two per cent.",
    "startSec": 19.415,
    "endSec": 20.317
  },
  {
    "word": "Before 1999 it averaged one point three",
    "startSec": 20.537,
    "endSec": 23.142
  },
  {
    "word": "million euros a year. After twenty-three thousand.",
    "startSec": 23.142,
    "endSec": 26.481
  },
  {
    "word": "The whole list of structural works",
    "startSec": 26.701,
    "endSec": 28.571
  },
  {
    "word": "over thirty-six years is seven lines long.",
    "startSec": 28.571,
    "endSec": 30.881
  },
  {
    "word": "Then 2005: fifty thousand.",
    "startSec": 31.101,
    "endSec": 32.719
  },
  {
    "word": "That is the whole of it.",
    "startSec": 32.719,
    "endSec": 34.212
  },
  {
    "word": "The commission drew the obvious conclusion",
    "startSec": 34.432,
    "endSec": 36.664
  },
  {
    "word": "and it wrote it down",
    "startSec": 36.664,
    "endSec": 37.726
  },
  {
    "word": "in the language",
    "startSec": 37.726,
    "endSec": 38.523
  },
  {
    "word": "of the concession contract.",
    "startSec": 38.523,
    "endSec": 39.958
  },
  {
    "word": "Not doing simple ordinary maintenance",
    "startSec": 40.178,
    "endSec": 42.354
  },
  {
    "word": "today means wanting",
    "startSec": 42.354,
    "endSec": 43.472
  },
  {
    "word": "to do a great deal",
    "startSec": 43.472,
    "endSec": 44.531
  },
  {
    "word": "of extraordinary maintenance tomorrow",
    "startSec": 44.531,
    "endSec": 46.707
  },
  {
    "word": "at certainly higher costs",
    "startSec": 46.707,
    "endSec": 48.178
  },
  {
    "word": "with a mirror-image higher remunerativeness.",
    "startSec": 48.178,
    "endSec": 50.766
  }
];
