import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT99_CAPTIONS, SHORT99_TOTAL_SEC} from './short99_timing';

/**
 * short99 — The baseline nobody states out loud: without a warrant, your door stays shut.
 * Episode PD-2026-014-lange.  Type A — the rule the exceptions hang off.
 *
 * AVOIDS: short14 is about the garage and the 2021 ruling. It never states the underlying baseline or how narrow the exceptions are.
 * LEAVES FOR THE LONG-FORM: How narrow is narrow — what actually counts as an emergency?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-014-lange.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short99/short99_01.png', kind: 'image', motion: 'parallax', fast: true},   // a front door from inside a dark hallway, chain across it
  {line: 'L1', id: 'p02', src: 'shorts/short99/fx/fx_02.mp4', kind: 'video', motion: 'video', fast: true},   // a hand pressing a pen to a blank warrant sheet
  {line: 'L1', id: 'p03', src: 'shorts/short99/short99_03.png', kind: 'image', motion: 'pushin', fast: true},   // courthouse columns from directly below
  {line: 'L1', id: 'p04', src: 'shorts/short99/short99_04.png', kind: 'image', motion: 'parallax'},   // a cruiser's single roof beacon at a kerb
  {line: 'L2', id: 'p05', src: 'shorts/short99/short99_05.png', kind: 'image', motion: 'kenburns'},   // a shaft of light narrowed to a thin slot across a hallway 
  {line: 'L2', id: 'p06', src: 'shorts/short99/short99_06.png', kind: 'image', motion: 'pushin'},   // a long corridor receding toward one lit doorway
  {line: 'L2', id: 'p07', src: 'shorts/short99/short99_07.png', kind: 'image', motion: 'parallax'},   // a thin stack of only three worn folders on a bare desk
  {line: 'L2', id: 'p08', src: 'shorts/short99/short99_08.png', kind: 'image', motion: 'kenburns'},   // an empty judge's bench from the floor
  {line: 'L2', id: 'p09', src: 'shorts/short99/short99_09.png', kind: 'image', motion: 'pushin'},   // a wall clock with a blank featureless face
  {line: 'L2', id: 'p10', src: 'shorts/short99/short99_10.png', kind: 'image', motion: 'parallax'},   // a rubber stamp beside a blank warrant form
  {line: 'L2', id: 'p11', src: 'shorts/short99/short99_11.png', kind: 'image', motion: 'kenburns'},   // a heavy brass deadbolt thrown across a jamb
  {line: 'L3', id: 'p12', src: 'shorts/short99/short99_12.png', kind: 'image', motion: 'pushin'},   // a garage door descending on a narrowing blade of driveway 
  {line: 'L3', id: 'p13', src: 'shorts/short99/short99_13.png', kind: 'image', motion: 'parallax'},   // a boot wedged under the descending garage door
  {line: 'L3', id: 'p14', src: 'shorts/short99/short99_14.png', kind: 'image', motion: 'kenburns'},   // the dark garage past the rear bumper of a parked wagon
  {line: 'L3', id: 'p15', src: 'shorts/short99/short99_15.png', kind: 'image', motion: 'pushin'},   // two hands laid flat on the cold hood of the wagon
  {line: 'L3', id: 'p16', src: 'shorts/short99/short99_16.png', kind: 'image', motion: 'parallax'},   // a worn doormat and a single boot print, seen from above
  {line: 'L4', id: 'p18', src: 'shorts/short99/short99_18.png', kind: 'image', motion: 'pushin'},   // a single empty chair in a cone of light in the courtroom w
  {line: 'L4', id: 'p19', src: 'shorts/short99/short99_19.png', kind: 'image', motion: 'parallax'},   // a gavel caught mid-strike
  {line: 'L4', id: 'p20', src: 'shorts/short99/short99_20.png', kind: 'image', motion: 'kenburns'},   // the United States with borders as glowing seams
  {line: 'L4', id: 'p21', src: 'shorts/short99/fx/fx_21.mp4', kind: 'video', motion: 'video'},   // a silhouette walking away through a doorway into daylight
  {line: 'L4', id: 'p22', src: 'shorts/short99/short99_22.png', kind: 'image', motion: 'parallax'},   // a front door standing open onto blinding daylight
  {line: 'L8', id: 'p23', src: 'shorts/short99/short99_04.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short99/short99_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short99/short99_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the hook plate — identical framing to plate 01
  {line: 'L5', id: 'p26', src: 'shorts/short99/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // evidence about to be destroyed
  {line: 'L5', id: 'p27', src: 'shorts/short99/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // a person in danger inside
  {line: 'L5', id: 'p28', src: 'shorts/short99/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a suspect actively getting away
  {line: 'L5', id: 'p30', src: 'shorts/short99/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // the door those exceptions are about
  {line: 'L6', id: 'p31', src: 'shorts/short99/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // the state's answer was yes, automatically
  {line: 'L6', id: 'p32', src: 'shorts/short99/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // any flight at all, from anything
  {line: 'L6', id: 'p33', src: 'shorts/short99/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // every front door that rule would reach
  {line: 'L6', id: 'p34', src: 'shorts/short99/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // flight in, door open
  {line: 'L6', id: 'p35', src: 'shorts/short99/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // where an automatic rule ends up
  {line: 'L7', id: 'p36', src: 'shorts/short99/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // the protection switched off
  {line: 'L7', id: 'p37', src: 'shorts/short99/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // the house the Fourth Amendment is strongest in
  {line: 'L7', id: 'p38', src: 'shorts/short99/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // the trivial file the whole chase was over
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT99_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT99: ShortData = {
  shortId: 'short99',
  episodeId: 'PD-2026-014-lange',
  durationSec: SHORT99_TOTAL_SEC,
  narrationSrc: 'shorts/short99/audio/short99_final_mix_v002_en_us.mp3',
  captions: SHORT99_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short99/short99_ctathumb.jpg',
  ctaLongTitle: "He Drove Home Honking. The Police",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short99.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short99/short99_kin_a.webm', atSec: 10.47, durSec: 2.3, phrase: "A FOOT UNDER THE DOOR"},
    {src: 'shorts/short99/short99_kin_b.webm', atSec: 35.65, durSec: 2.3, phrase: "FLIGHT IN DOOR OPEN"},
  ],
};
