import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT197_CAPTIONS, SHORT197_TOTAL_SEC} from './short197_timing';

/**
 * short197 — A Treasury watchdog measured these structuring seizures and found nine in ten of the traceable cases involved money from legal sources, which made her a representative case rather than an unlucky one.
 * Episode PD-2026-035-hinders.  Type ?.
 *
 * AVOIDS: Short 35 told her story and the reform; this cut is the audit figure underneath it and why an agency memo did not stop the seizures.
 * LEAVES FOR THE LONG-FORM: What it finally took to close the specific trap that number exposed, and how much of the power survived.
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-035-hinders.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short197/short197_01.png', kind: 'image', motion: 'parallax', fast: true},   // an aisle of pulled files
  {line: 'L1', id: 'p02', src: 'shorts/short197/short197_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a tower of case folders on a desk
  {line: 'L1', id: 'p03', src: 'shorts/short197/short197_03.png', kind: 'image', motion: 'pushin', fast: true},   // a report's pages, every figure blank
  {line: 'L1', id: 'p04', src: 'shorts/short197/short197_04.png', kind: 'image', motion: 'parallax'},   // a lamp burning into camera over the desk
  {line: 'L2', id: 'p05', src: 'shorts/short197/short197_05.png', kind: 'image', motion: 'kenburns'},   // a wall of unlabelled folders
  {line: 'L2', id: 'p06', src: 'shorts/short197/short197_06.png', kind: 'image', motion: 'pushin'},   // an in-tray overflowing
  {line: 'L2', id: 'p07', src: 'shorts/short197/short197_07.png', kind: 'image', motion: 'parallax'},   // banded notes on a dark desk
  {line: 'L2', id: 'p08', src: 'shorts/short197/short197_08.png', kind: 'image', motion: 'kenburns'},   // one drawer pulled from a wall of them
  {line: 'L2', id: 'p09', src: 'shorts/short197/short197_09.png', kind: 'image', motion: 'pushin'},   // a line on dark glass that only rises
  {line: 'L2', id: 'p10', src: 'shorts/short197/short197_10.png', kind: 'image', motion: 'parallax'},   // a blank clock over the audit
  {line: 'L2', id: 'p11', src: 'shorts/short197/short197_11.png', kind: 'image', motion: 'kenburns'},   // the stamp on each file
  {line: 'L3', id: 'p12', src: 'shorts/short197/short197_12.png', kind: 'image', motion: 'pushin'},   // an empty diner counter
  {line: 'L3', id: 'p13', src: 'shorts/short197/short197_13.png', kind: 'image', motion: 'parallax'},   // a shop window at first light
  {line: 'L3', id: 'p14', src: 'shorts/short197/short197_14.png', kind: 'image', motion: 'kenburns'},   // hands flat on a diner counter
  {line: 'L3', id: 'p15', src: 'shorts/short197/short197_15.png', kind: 'image', motion: 'pushin'},   // a single stool in a cone of light
  {line: 'L3', id: 'p16', src: 'shorts/short197/short197_16.png', kind: 'image', motion: 'parallax'},   // dust in a closed kitchen
  {line: 'L4', id: 'p17', src: 'shorts/short197/short197_17.png', kind: 'image', motion: 'kenburns'},   // a room where nobody was identified
  {line: 'L4', id: 'p18', src: 'shorts/short197/short197_18.png', kind: 'image', motion: 'pushin'},   // a sealed envelope on a counter
  {line: 'L4', id: 'p19', src: 'shorts/short197/short197_19.png', kind: 'image', motion: 'parallax'},   // one owner alone in a hall
  {line: 'L4', id: 'p20', src: 'shorts/short197/short197_20.png', kind: 'image', motion: 'kenburns'},   // a bank vault door, closed
  {line: 'L4', id: 'p21', src: 'shorts/short197/short197_21.png', kind: 'image', motion: 'pushin'},   // a door closing on a blade of light
  {line: 'L4', id: 'p22', src: 'shorts/short197/short197_22.png', kind: 'image', motion: 'parallax'},   // years of dates worn blank
  {line: 'L8', id: 'p23', src: 'shorts/short197/short197_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short197/short197_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short197/short197_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to an aisle of pulled files
  {line: 'L5', id: 'p26', src: 'shorts/short197/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // a pen left on a blank pad
  {line: 'L5', id: 'p27', src: 'shorts/short197/short197_27.png', kind: 'image', motion: 'pushin'},   // a phone face down beside it
  {line: 'L5', id: 'p28', src: 'shorts/short197/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a stairwell between floors of an agency
  {line: 'L5', id: 'p29', src: 'shorts/short197/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // a corridor to a lit doorway
  {line: 'L5', id: 'p30', src: 'shorts/short197/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // a blank memo on a desk
  {line: 'L6', id: 'p31', src: 'shorts/short197/short197_31.png', kind: 'image', motion: 'parallax'},   // an empty committee chamber
  {line: 'L6', id: 'p32', src: 'shorts/short197/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // the front of a federal building
  {line: 'L6', id: 'p33', src: 'shorts/short197/short197_33.png', kind: 'image', motion: 'pushin'},   // doors opening on daylight
  {line: 'L6', id: 'p34', src: 'shorts/short197/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // a door locked from outside
  {line: 'L6', id: 'p35', src: 'shorts/short197/short197_35.png', kind: 'image', motion: 'kenburns'},   // a floor of dark desks after hours
  {line: 'L7', id: 'p36', src: 'shorts/short197/short197_36.png', kind: 'image', motion: 'pushin'},   // someone walking away down a hallway
  {line: 'L7', id: 'p37', src: 'shorts/short197/short197_37.png', kind: 'image', motion: 'parallax'},   // the table where the questions happen
  {line: 'L7', id: 'p38', src: 'shorts/short197/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a counter of a person's things
  {line: 'L7', id: 'p39', src: 'shorts/short197/short197_39.png', kind: 'image', motion: 'pushin'},   // a room with a rail and a gate
  {line: 'L7', id: 'p40', src: 'shorts/short197/short197_40.png', kind: 'image', motion: 'parallax'},   // a grain elevator against a pale sky
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT197_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT197: ShortData = {
  shortId: 'short197',
  episodeId: 'PD-2026-035-hinders',
  durationSec: SHORT197_TOTAL_SEC,
  narrationSrc: 'shorts/short197/audio/short197_final_mix_v002_en_us.mp3',
  captions: SHORT197_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short197/short197_ctathumb.jpg',
  ctaLongTitle: "Following the deposit rule is what",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short197.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short197/short197_kin_a.webm', atSec: 17.04, durSec: 2.3, phrase: "9 IN 10 NO CRIME"},
    {src: 'shorts/short197/short197_kin_b.webm', atSec: 37.23, durSec: 2.3, phrase: "A MEMO IS NOT A LAW"},
  ],
};
