import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT109_CAPTIONS, SHORT109_TOTAL_SEC} from './short109_timing';

/**
 * short109 — Nobody ever proved what he meant to do with the four point eight million files.
 * Episode PD-2026-023-swartz.  Type C — the question that was never answered.
 *
 * AVOIDS: short23 states the download and the charges. It never says that the purpose was never proven.
 * LEAVES FOR THE LONG-FORM: If the intent was never proven, what were the thirteen counts actually built on?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-023-swartz.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short109/short109_01.png', kind: 'image', motion: 'parallax', fast: true},   // a laptop open on the floor of a cramped wiring closet
  {line: 'L1', id: 'p02', src: 'shorts/short109/short109_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a steel utility door standing ajar in a basement corridor
  {line: 'L1', id: 'p03', src: 'shorts/short109/short109_03.png', kind: 'image', motion: 'pushin', fast: true},   // a corridor receding toward one lit doorway
  {line: 'L1', id: 'p04', src: 'shorts/short109/short109_04.png', kind: 'image', motion: 'parallax'},   // library stacks receding into darkness, volumes unlabelled
  {line: 'L2', id: 'p05', src: 'shorts/short109/short109_05.png', kind: 'image', motion: 'kenburns'},   // a single empty wooden chair in a cone of light
  {line: 'L2', id: 'p06', src: 'shorts/short109/short109_06.png', kind: 'image', motion: 'pushin'},   // a thick case file closed and tied with a band
  {line: 'L2', id: 'p07', src: 'shorts/short109/short109_07.png', kind: 'image', motion: 'parallax'},   // an empty tiered lecture hall, one lamp at the podium
  {line: 'L2', id: 'p08', src: 'shorts/short109/short109_08.png', kind: 'image', motion: 'kenburns'},   // a phone lying face down on a dark table
  {line: 'L2', id: 'p09', src: 'shorts/short109/short109_09.png', kind: 'image', motion: 'pushin'},   // an unplugged network cable lying loose on a dark floor
  {line: 'L2', id: 'p10', src: 'shorts/short109/short109_10.png', kind: 'image', motion: 'parallax'},   // a shaft of light crossing an empty room, thick with dust
  {line: 'L2', id: 'p11', src: 'shorts/short109/short109_11.png', kind: 'image', motion: 'kenburns'},   // a wall clock with a blank featureless face
  {line: 'L3', id: 'p12', src: 'shorts/short109/short109_12.png', kind: 'image', motion: 'pushin'},   // a printed sheet alone on a dark desk, every line worn blan
  {line: 'L3', id: 'p13', src: 'shorts/short109/short109_13.png', kind: 'image', motion: 'parallax'},   // a hand pressing a pen to a blank sheet
  {line: 'L3', id: 'p14', src: 'shorts/short109/short109_14.png', kind: 'image', motion: 'kenburns'},   // a keyboard in the dark, one key catching a hard rim light
  {line: 'L3', id: 'p15', src: 'shorts/short109/short109_15.png', kind: 'image', motion: 'pushin'},   // a photocopier platen glowing under a closed lid
  {line: 'L3', id: 'p16', src: 'shorts/short109/fx/fx_16.mp4', kind: 'video', motion: 'video'},   // a heavy door swinging shut on a narrowing blade of light
  {line: 'L4', id: 'p17', src: 'shorts/short109/fx/fx_17.mp4', kind: 'video', motion: 'video'},   // banded stacks of cash under one lamp
  {line: 'L4', id: 'p18', src: 'shorts/short109/short109_18.png', kind: 'image', motion: 'pushin'},   // a booking tray holding a belt, keys and a few coins
  {line: 'L4', id: 'p19', src: 'shorts/short109/short109_19.png', kind: 'image', motion: 'parallax'},   // a leaning stack of thirteen thin documents, every cover bl
  {line: 'L4', id: 'p21', src: 'shorts/short109/short109_21.png', kind: 'image', motion: 'pushin'},   // a padlock closed on a steel gate across a library aisle
  {line: 'L4', id: 'p22', src: 'shorts/short109/short109_22.png', kind: 'image', motion: 'parallax'},   // heavy doors swinging open onto blinding daylight
  {line: 'L8', id: 'p23', src: 'shorts/short109/short109_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short109/short109_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short109/short109_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the hook plate — identical framing to plate 01
  {line: 'L5', id: 'p26', src: 'shorts/short109/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // a wall of open pigeonholes in a hall
  {line: 'L5', id: 'p27', src: 'shorts/short109/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // a door standing ajar in a corridor
  {line: 'L5', id: 'p28', src: 'shorts/short109/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a library window above a study desk
  {line: 'L5', id: 'p29', src: 'shorts/short109/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // a student walking across a campus lawn
  {line: 'L5', id: 'p30', src: 'shorts/short109/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // empty study desks in a library
  {line: 'L6', id: 'p31', src: 'shorts/short109/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // a hand turning the pages of a wall calendar
  {line: 'L6', id: 'p32', src: 'shorts/short109/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // a wall of steel drawers with one pulled open
  {line: 'L6', id: 'p33', src: 'shorts/short109/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // a stack of external hard drives on a desk
  {line: 'L6', id: 'p34', src: 'shorts/short109/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // boxes stacked to the ceiling in a storeroom
  {line: 'L6', id: 'p35', src: 'shorts/short109/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // a person pushing a trolley of boxes down a corridor
  {line: 'L7', id: 'p36', src: 'shorts/short109/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // hands adjusting a microscope in a laboratory
  {line: 'L7', id: 'p37', src: 'shorts/short109/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // a large satellite dish against a pale sky
  {line: 'L7', id: 'p38', src: 'shorts/short109/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // two researchers working together at a bench
  {line: 'L7', id: 'p39', src: 'shorts/short109/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // hands sorting index cards into rows
  {line: 'L7', id: 'p40', src: 'shorts/short109/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // an empty seminar room with chairs in a circle
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT109_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT109: ShortData = {
  shortId: 'short109',
  episodeId: 'PD-2026-023-swartz',
  durationSec: SHORT109_TOTAL_SEC,
  narrationSrc: 'shorts/short109/audio/short109_final_mix_v002_en_us.mp3',
  captions: SHORT109_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short109/short109_ctathumb.jpg',
  ctaLongTitle: "The website he took from never wanted",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
