// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #42.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT42_TOTAL_SEC = 57.1;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 12.353
  },
  {
    "id": "L2",
    "start": 13.073,
    "end": 24.915
  },
  {
    "id": "L3",
    "start": 25.635,
    "end": 35.666
  },
  {
    "id": "L4",
    "start": 36.386,
    "end": 51.386
  },
  {
    "id": "L5",
    "start": 52.106,
    "end": 56.1
  }
];

export const SHORT42_CAPTIONS: ShortCaption[] = [
  {
    "word": "The nine-year-old got out safe. Behind him",
    "startSec": 0.0,
    "endSec": 2.543
  },
  {
    "word": "an armed stranger fleeing police had broken",
    "startSec": 2.543,
    "endSec": 5.147
  },
  {
    "word": "into the house at random",
    "startSec": 5.147,
    "endSec": 6.6
  },
  {
    "word": "a family he'd never met.",
    "startSec": 6.6,
    "endSec": 8.054
  },
  {
    "word": "For nineteen hours the home held.",
    "startSec": 8.054,
    "endSec": 10.052
  },
  {
    "word": "Then it was gone.",
    "startSec": 10.052,
    "endSec": 11.081
  },
  {
    "word": "So who pays for that?",
    "startSec": 11.081,
    "endSec": 12.353
  },
  {
    "word": "Talks failed.",
    "startSec": 13.073,
    "endSec": 13.862
  },
  {
    "word": "Police answered with gas and a BearCat",
    "startSec": 13.862,
    "endSec": 16.17
  },
  {
    "word": "an armored truck that punched holes through the walls.",
    "startSec": 16.17,
    "endSec": 19.449
  },
  {
    "word": "The order on record:",
    "startSec": 19.449,
    "endSec": 20.664
  },
  {
    "word": "take as much of the building as",
    "startSec": 20.664,
    "endSec": 22.547
  },
  {
    "word": "needed without making the roof fall in.",
    "startSec": 22.547,
    "endSec": 24.915
  },
  {
    "word": "The family had done nothing wrong.",
    "startSec": 25.635,
    "endSec": 27.43
  },
  {
    "word": "The city offered five thousand dollars for temporary lodging.",
    "startSec": 27.43,
    "endSec": 30.651
  },
  {
    "word": "Their insurance excluded government acts. To rebuild",
    "startSec": 30.651,
    "endSec": 33.396
  },
  {
    "word": "he borrowed a quarter of a million dollars.",
    "startSec": 33.396,
    "endSec": 35.666
  },
  {
    "word": "So he sued.",
    "startSec": 36.386,
    "endSec": 37.103
  },
  {
    "word": "But the courts called it police power",
    "startSec": 37.103,
    "endSec": 39.516
  },
  {
    "word": "not a taking nothing owed. Their words:",
    "startSec": 39.516,
    "endSec": 42.06
  },
  {
    "word": "the innocence of the property owner does",
    "startSec": 42.06,
    "endSec": 44.669
  },
  {
    "word": "not factor into the determination. In 2020",
    "startSec": 44.669,
    "endSec": 47.408
  },
  {
    "word": "the Supreme Court declined to hear it",
    "startSec": 47.408,
    "endSec": 49.821
  },
  {
    "word": "deciding nothing at all.",
    "startSec": 49.821,
    "endSec": 51.386
  },
  {
    "word": "Full story on the channel.",
    "startSec": 52.106,
    "endSec": 53.633
  },
  {
    "word": "Follow for the cases they don't teach you.",
    "startSec": 53.633,
    "endSec": 56.1
  }
];
