// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #103.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT103_TOTAL_SEC = 57.293;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.177
  },
  {
    "id": "L2",
    "start": 6.397,
    "end": 14.013
  },
  {
    "id": "L3",
    "start": 14.233,
    "end": 20.92
  },
  {
    "id": "L4",
    "start": 21.14,
    "end": 28.385
  },
  {
    "id": "L5",
    "start": 28.605,
    "end": 34.874
  },
  {
    "id": "L6",
    "start": 35.094,
    "end": 43.267
  },
  {
    "id": "L7",
    "start": 43.487,
    "end": 50.732
  },
  {
    "id": "L8",
    "start": 50.952,
    "end": 56.293
  }
];

export const SHORT103_CAPTIONS: ShortCaption[] = [
  {
    "word": "In 2021 the Supreme Court shut a",
    "startSec": 0.0,
    "endSec": 1.847
  },
  {
    "word": "door police had been walking through.",
    "startSec": 1.847,
    "endSec": 3.983
  },
  {
    "word": "It did not shut the",
    "startSec": 3.983,
    "endSec": 5.08
  },
  {
    "word": "one you might need.",
    "startSec": 5.08,
    "endSec": 6.177
  },
  {
    "word": "The Chief Justice",
    "startSec": 6.397,
    "endSec": 7.309
  },
  {
    "word": "joined by Justice Breyer",
    "startSec": 7.309,
    "endSec": 8.596
  },
  {
    "word": "stressed that no warrant is needed",
    "startSec": 8.596,
    "endSec": 10.42
  },
  {
    "word": "to help a person who is",
    "startSec": 10.42,
    "endSec": 11.653
  },
  {
    "word": "seriously injured or threatened with injury.",
    "startSec": 11.653,
    "endSec": 14.013
  },
  {
    "word": "What the Court removed",
    "startSec": 14.233,
    "endSec": 15.501
  },
  {
    "word": "was the general version.",
    "startSec": 15.501,
    "endSec": 16.885
  },
  {
    "word": "Looking after someone is not by itself",
    "startSec": 16.885,
    "endSec": 19.075
  },
  {
    "word": "a reason to cross the threshold.",
    "startSec": 19.075,
    "endSec": 20.92
  },
  {
    "word": "One phone call asking officers to check",
    "startSec": 21.14,
    "endSec": 23.437
  },
  {
    "word": "that a man was alive ended with",
    "startSec": 23.437,
    "endSec": 25.263
  },
  {
    "word": "his handguns in an evidence bag.",
    "startSec": 25.263,
    "endSec": 27.148
  },
  {
    "word": "No warrant. No crime.",
    "startSec": 27.148,
    "endSec": 28.385
  },
  {
    "word": "The doors that were",
    "startSec": 28.605,
    "endSec": 29.589
  },
  {
    "word": "already open stayed open.",
    "startSec": 29.589,
    "endSec": 30.885
  },
  {
    "word": "A valid warrant. Your consent.",
    "startSec": 30.885,
    "endSec": 32.439
  },
  {
    "word": "And exigent circumstances",
    "startSec": 32.439,
    "endSec": 33.734
  },
  {
    "word": "the genuine emergency.",
    "startSec": 33.734,
    "endSec": 34.874
  },
  {
    "word": "Change one detail and the answer flips.",
    "startSec": 35.094,
    "endSec": 37.491
  },
  {
    "word": "The officers reach the porch",
    "startSec": 37.491,
    "endSec": 39.211
  },
  {
    "word": "and hear a gunshot inside.",
    "startSec": 39.211,
    "endSec": 40.809
  },
  {
    "word": "Nothing in this decision keeps them out.",
    "startSec": 40.809,
    "endSec": 43.267
  },
  {
    "word": "A unanimous Supreme Court did",
    "startSec": 43.487,
    "endSec": 45.223
  },
  {
    "word": "not end his case.",
    "startSec": 45.223,
    "endSec": 46.241
  },
  {
    "word": "It vacated the decision against",
    "startSec": 46.241,
    "endSec": 48.097
  },
  {
    "word": "him and sent it back",
    "startSec": 48.097,
    "endSec": 49.295
  },
  {
    "word": "down to be judged again.",
    "startSec": 49.295,
    "endSec": 50.732
  },
  {
    "word": "Help and a search can begin with",
    "startSec": 50.952,
    "endSec": 52.595
  },
  {
    "word": "exactly the same knock at the door.",
    "startSec": 52.595,
    "endSec": 54.393
  },
  {
    "word": "So which one did",
    "startSec": 54.393,
    "endSec": 55.215
  },
  {
    "word": "the Court leave open?",
    "startSec": 55.215,
    "endSec": 56.293
  }
];
