// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #23.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT23_TOTAL_SEC = 66.543;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 3.204
  },
  {
    "id": "L2",
    "start": 4.404,
    "end": 15.828
  },
  {
    "id": "L3",
    "start": 17.028,
    "end": 34.768
  },
  {
    "id": "L4",
    "start": 35.968,
    "end": 57.284
  },
  {
    "id": "L5",
    "start": 58.484,
    "end": 65.543
  }
];

export const SHORT23_CAPTIONS: ShortCaption[] = [
  {
    "word": "The website he took from didn't even want him charged.",
    "startSec": 0.0,
    "endSec": 3.204
  },
  {
    "word": "Aaron Swartz was a programming prodigy.",
    "startSec": 4.404,
    "endSec": 6.677
  },
  {
    "word": "As a teenager he co-authored the RSS specification and helped build Creative Commons, believing knowledge paid for by the public should belong to the public.",
    "startSec": 6.677,
    "endSec": 15.828
  },
  {
    "word": "Over MIT's open network, he downloaded about four point eight million scholarly articles — most of the JSTOR archive.",
    "startSec": 17.028,
    "endSec": 25.33
  },
  {
    "word": "JSTOR settled and said it did not want him prosecuted.",
    "startSec": 25.33,
    "endSec": 29.162
  },
  {
    "word": "MIT stayed neutral.",
    "startSec": 29.162,
    "endSec": 30.51
  },
  {
    "word": "Prosecutors charged him anyway — four counts, then thirteen.",
    "startSec": 30.51,
    "endSec": 34.768
  },
  {
    "word": "On paper the charges stacked to a theoretical maximum of thirty-five years; but prosecutors signaled a plea of about six months, and legal scholars said that headline wildly overstated what he really faced.",
    "startSec": 35.968,
    "endSec": 49.076
  },
  {
    "word": "Aaron Swartz died by suicide on January 11, 2013, at age 26.",
    "startSec": 49.076,
    "endSec": 52.894
  },
  {
    "word": "His family said the prosecution's overreach contributed to his death.",
    "startSec": 52.894,
    "endSec": 57.284
  },
  {
    "word": "If you're struggling, you can call or text 988, the Suicide and Crisis Lifeline.",
    "startSec": 58.484,
    "endSec": 63.352
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 63.352,
    "endSec": 65.543
  }
];
