import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT86_CAPTIONS, SHORT86_TOTAL_SEC} from './short86_timing';

/**
 * short86 — More than three dozen professionals signed one letter in 2018. The dives went on.
 * Episode PD-2026-016-titan.  Type C — the document.
 *
 * AVOIDS: short16 covered the four-day countdown, the fired safety chief, the game controller, 'All good here', and the 2025 Coast Guard finding. None of that is repeated here.
 * LEAVES FOR THE LONG-FORM: What did the letter actually say — and what happened after it was sent?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-016-titan.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short86/short86_01.png', kind: 'image', motion: 'parallax', fast: true},   // a hand adding one more signature to a crowded letter
  {line: 'L1', id: 'p02', src: 'shorts/short86/fx/fx_02.mp4', kind: 'video', motion: 'video', fast: true},   // the signed letter sealed into a plain envelope
  {line: 'L1', id: 'p03', src: 'shorts/short86/short86_03.png', kind: 'image', motion: 'pushin', fast: true},   // a long table ringed with three dozen empty chairs
  {line: 'L1', id: 'p04', src: 'shorts/short86/short86_04.png', kind: 'image', motion: 'parallax'},   // the warning letter landing in a corporate in-tray
  {line: 'L2', id: 'p05', src: 'shorts/short86/short86_05.png', kind: 'image', motion: 'kenburns'},   // the submersible's small acrylic viewport
  {line: 'L2', id: 'p06', src: 'shorts/short86/short86_06.png', kind: 'image', motion: 'pushin'},   // the carbon-fibre pressure hull on its workshop cradle
  {line: 'L2', id: 'p07', src: 'shorts/short86/fx/fx_07.mp4', kind: 'video', motion: 'video'},   // black water going down past the light
  {line: 'L2', id: 'p08', src: 'shorts/short86/short86_08.png', kind: 'image', motion: 'kenburns'},   // the hatch bolted shut from outside
  {line: 'L2', id: 'p09', src: 'shorts/short86/short86_09.png', kind: 'image', motion: 'pushin'},   // the empty launch cradle on a ship's afterdeck
  {line: 'L2', id: 'p10', src: 'shorts/short86/fx/fx_10.mp4', kind: 'video', motion: 'video'},   // the support ship's deck working at night
  {line: 'L2', id: 'p11', src: 'shorts/short86/short86_11.png', kind: 'image', motion: 'kenburns'},   // the certification stamp that was never used
  {line: 'L3', id: 'p12', src: 'shorts/short86/fx/fx_12.mp4', kind: 'video', motion: 'video'},   // carbon-fibre weave under raking light
  {line: 'L3', id: 'p13', src: 'shorts/short86/short86_13.png', kind: 'image', motion: 'parallax'},   // delaminated layers in a composite wall
  {line: 'L3', id: 'p14', src: 'shorts/short86/short86_14.png', kind: 'image', motion: 'kenburns'},   // the pressure test chamber, dogged shut
  {line: 'L3', id: 'p15', src: 'shorts/short86/fx/fx_15.mp4', kind: 'video', motion: 'video'},   // a pressure gauge needle climbing
  {line: 'L3', id: 'p16', src: 'shorts/short86/short86_16.png', kind: 'image', motion: 'parallax'},   // the dive cycles stacking up, unnumbered
  {line: 'L4', id: 'p17', src: 'shorts/short86/short86_17.png', kind: 'image', motion: 'kenburns'},   // the letter unopened on an empty boardroom table
  {line: 'L4', id: 'p18', src: 'shorts/short86/fx/fx_18.mp4', kind: 'video', motion: 'video'},   // a letter left unopened on a desk
  {line: 'L4', id: 'p19', src: 'shorts/short86/short86_19.png', kind: 'image', motion: 'parallax'},   // the warning filed away in the archive
  {line: 'L4', id: 'p20', src: 'shorts/short86/fx/fx_20.mp4', kind: 'video', motion: 'video'},   // the crane cable taking the load at sea
  {line: 'L4', id: 'p21', src: 'shorts/short86/short86_21.png', kind: 'image', motion: 'pushin'},   // the submersible's lights shrinking into black water
  {line: 'L4', id: 'p22', src: 'shorts/short86/short86_22.png', kind: 'image', motion: 'parallax'},   // the empty deck at first light
  {line: 'L8', id: 'p23', src: 'shorts/short86/short86_04.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short86/short86_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short86/short86_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the crowded signature sheet
  {line: 'L5', id: 'p26', src: 'shorts/short86/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // the letter being written late at night
  {line: 'L5', id: 'p27', src: 'shorts/short86/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // the letter opened out in two hands
  {line: 'L5', id: 'p28', src: 'shorts/short86/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // the pages of the warning turning
  {line: 'L5', id: 'p29', src: 'shorts/short86/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // the five years between the letter and the dive
  {line: 'L5', id: 'p30', src: 'shorts/short86/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // the water the warning was about
  {line: 'L6', id: 'p31', src: 'shorts/short86/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // one man alone with the machine he built
  {line: 'L6', id: 'p32', src: 'shorts/short86/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // the inspector's chair nobody sat in
  {line: 'L6', id: 'p33', src: 'shorts/short86/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // the outside check shut out
  {line: 'L6', id: 'p34', src: 'shorts/short86/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // the inspection walkway standing unused
  {line: 'L6', id: 'p35', src: 'shorts/short86/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // the checklist that was never filled in
  {line: 'L7', id: 'p36', src: 'shorts/short86/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // the hull's own sound drawn as a line
  {line: 'L7', id: 'p38', src: 'shorts/short86/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a detector waiting on the ceiling
  {line: 'L7', id: 'p39', src: 'shorts/short86/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // the break the system was listening for
  {line: 'L7', id: 'p40', src: 'shorts/short86/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // the alarm that only sounds too late
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT86_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT86: ShortData = {
  shortId: 'short86',
  episodeId: 'PD-2026-016-titan',
  durationSec: SHORT86_TOTAL_SEC,
  narrationSrc: 'shorts/short86/audio/short86_final_mix_v002_en_us.mp3',
  captions: SHORT86_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short86/short86_ctathumb.jpg',
  ctaLongTitle: "He called safety pure waste and dove",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
