// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #315.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT315_TOTAL_SEC = 56.27;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.433
  },
  {
    "id": "L2",
    "start": 5.653,
    "end": 11.272
  },
  {
    "id": "L3",
    "start": 11.492,
    "end": 18.922
  },
  {
    "id": "L4",
    "start": 19.142,
    "end": 24.483
  },
  {
    "id": "L5",
    "start": 24.703,
    "end": 35.384
  },
  {
    "id": "L6",
    "start": 35.604,
    "end": 41.641
  },
  {
    "id": "L7",
    "start": 41.861,
    "end": 49.802
  },
  {
    "id": "L8",
    "start": 50.022,
    "end": 55.27
  }
];

export const SHORT315_CAPTIONS: ShortCaption[] = [
  {
    "word": "Airlines cannot watch their pilots fly.",
    "startSec": 0.0,
    "endSec": 2.23
  },
  {
    "word": "So the industry tests them",
    "startSec": 2.23,
    "endSec": 3.717
  },
  {
    "word": "and writes down what happened.",
    "startSec": 3.717,
    "endSec": 5.433
  },
  {
    "word": "Every check ride is a file.",
    "startSec": 5.653,
    "endSec": 7.503
  },
  {
    "word": "Every failure is a file.",
    "startSec": 7.503,
    "endSec": 9.148
  },
  {
    "word": "Paper substitutes for watching.",
    "startSec": 9.148,
    "endSec": 11.272
  },
  {
    "word": "Failing one is not rare. In 2008",
    "startSec": 11.492,
    "endSec": 13.441
  },
  {
    "word": "thirteen point one per cent failed",
    "startSec": 13.441,
    "endSec": 15.512
  },
  {
    "word": "the airline transport pilot certificate",
    "startSec": 15.512,
    "endSec": 17.887
  },
  {
    "word": "on first attempt.",
    "startSec": 17.887,
    "endSec": 18.922
  },
  {
    "word": "Treating a check ride failure",
    "startSec": 19.142,
    "endSec": 20.844
  },
  {
    "word": "as the mark",
    "startSec": 20.844,
    "endSec": 21.544
  },
  {
    "word": "of a dangerous man is not aviation.",
    "startSec": 21.544,
    "endSec": 23.598
  },
  {
    "word": "It is prejudice.",
    "startSec": 23.598,
    "endSec": 24.483
  },
  {
    "word": "Colgan's application asked one question.",
    "startSec": 24.703,
    "endSec": 27.459
  },
  {
    "word": "Have you ever failed any proficiency check",
    "startSec": 27.459,
    "endSec": 30.354
  },
  {
    "word": "FAA check ride",
    "startSec": 30.354,
    "endSec": 31.318
  },
  {
    "word": "IOE or line check?",
    "startSec": 31.318,
    "endSec": 32.559
  },
  {
    "word": "In 2005 he answered yes",
    "startSec": 32.559,
    "endSec": 34.144
  },
  {
    "word": "and described one.",
    "startSec": 34.144,
    "endSec": 35.384
  },
  {
    "word": "True. Complete? No.",
    "startSec": 35.604,
    "endSec": 36.763
  },
  {
    "word": "He was carrying two other certificate disapprovals.",
    "startSec": 36.763,
    "endSec": 39.873
  },
  {
    "word": "Neither appeared on the form.",
    "startSec": 39.873,
    "endSec": 41.641
  },
  {
    "word": "The file",
    "startSec": 41.861,
    "endSec": 42.561
  },
  {
    "word": "that would have contradicted it sat",
    "startSec": 42.561,
    "endSec": 44.62
  },
  {
    "word": "at the Federal Aviation Administration",
    "startSec": 44.62,
    "endSec": 46.855
  },
  {
    "word": "the whole time.",
    "startSec": 46.855,
    "endSec": 47.737
  },
  {
    "word": "Nobody hid it.",
    "startSec": 47.737,
    "endSec": 48.561
  },
  {
    "word": "The systems did not talk.",
    "startSec": 48.561,
    "endSec": 49.802
  },
  {
    "word": "So the record alone proves nothing.",
    "startSec": 50.022,
    "endSec": 51.997
  },
  {
    "word": "What matters is not the failures.",
    "startSec": 51.997,
    "endSec": 53.859
  },
  {
    "word": "It is who could see them.",
    "startSec": 53.859,
    "endSec": 55.27
  }
];
