import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT158_CAPTIONS, SHORT158_TOTAL_SEC} from './short158_timing';

/**
 * short158 — They did not just buy the seat. They wrote the bribe off on their taxes.
 * Episode PD-2026-019-varsityblues.  Type B - what the money actually bought, and who paid the rest of the bill.
 *
 * AVOIDS: short19 names the sham charity and the twenty-five million dollars. It never explains the thank-you letter, the deduction, or the ten million dollars of restitution ordered to the I.R.S.
 * LEAVES FOR THE LONG-FORM: Parents paid roughly twenty-five million dollars. What exactly were they told they were guaranteed?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-019-varsityblues.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short158/short158_01.png', kind: 'image', motion: 'parallax', fast: true},   // a blank cheque torn from the book
  {line: 'L1', id: 'p02', src: 'shorts/short158/fx/fx_02.mp4', kind: 'video', motion: 'video', fast: true},   // an envelope and a letter
  {line: 'L1', id: 'p03', src: 'shorts/short158/short158_03.png', kind: 'image', motion: 'pushin', fast: true},   // the parking garage where it did not happen
  {line: 'L1', id: 'p04', src: 'shorts/short158/short158_04.png', kind: 'image', motion: 'parallax'},   // the side door, very slightly ajar
  {line: 'L2', id: 'p05', src: 'shorts/short158/short158_05.png', kind: 'image', motion: 'kenburns'},   // a wall of small closed post boxes
  {line: 'L2', id: 'p06', src: 'shorts/short158/short158_06.png', kind: 'image', motion: 'pushin'},   // a mailbox and letters
  {line: 'L2', id: 'p07', src: 'shorts/short158/short158_07.png', kind: 'image', motion: 'parallax'},   // a blank sheet slid out of a plain envelope
  {line: 'L2', id: 'p08', src: 'shorts/short158/short158_08.png', kind: 'image', motion: 'kenburns'},   // a letter and envelope on a desk
  {line: 'L2', id: 'p09', src: 'shorts/short158/short158_09.png', kind: 'image', motion: 'pushin'},   // a stamp with the die worn smooth
  {line: 'L2', id: 'p10', src: 'shorts/short158/short158_10.png', kind: 'image', motion: 'parallax'},   // the charity's boardroom, nobody in it
  {line: 'L2', id: 'p11', src: 'shorts/short158/fx/fx_11.mp4', kind: 'video', motion: 'video'},   // a conference table and chairs
  {line: 'L3', id: 'p12', src: 'shorts/short158/short158_12.png', kind: 'image', motion: 'pushin'},   // a sheet held up to the lamp, blank both sides
  {line: 'L3', id: 'p13', src: 'shorts/short158/fx/fx_13.mp4', kind: 'video', motion: 'video'},   // a stack of documents on a desk
  {line: 'L3', id: 'p14', src: 'shorts/short158/short158_14.png', kind: 'image', motion: 'kenburns'},   // a leaning tower of tax folders
  {line: 'L3', id: 'p15', src: 'shorts/short158/short158_15.png', kind: 'image', motion: 'pushin'},   // a metal filing cabinet
  {line: 'L3', id: 'p16', src: 'shorts/short158/short158_16.png', kind: 'image', motion: 'parallax'},   // an in-tray overflowing with blank forms
  {line: 'L4', id: 'p17', src: 'shorts/short158/short158_17.png', kind: 'image', motion: 'kenburns'},   // one bare oar across trestles in the dark
  {line: 'L4', id: 'p18', src: 'shorts/short158/fx/fx_18.mp4', kind: 'video', motion: 'video'},   // a rowing boat on a river
  {line: 'L4', id: 'p19', src: 'shorts/short158/short158_19.png', kind: 'image', motion: 'parallax'},   // the studio where the photograph was staged
  {line: 'L4', id: 'p20', src: 'shorts/short158/short158_20.png', kind: 'image', motion: 'kenburns'},   // the seat that was bought, picked out by a beam
  {line: 'L4', id: 'p21', src: 'shorts/short158/short158_21.png', kind: 'image', motion: 'pushin'},   // a university campus building
  {line: 'L5', id: 'p22', src: 'shorts/short158/short158_22.png', kind: 'image', motion: 'parallax'},   // a shuttered government counter
  {line: 'L8', id: 'p23', src: 'shorts/short158/short158_04.png', kind: 'image', motion: 'parallax'},   // return to the hook plate: a blank cheque torn from the boo
  {line: 'L8', id: 'p24', src: 'shorts/short158/short158_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing: a blan
  {line: 'L8', id: 'p25', src: 'shorts/short158/short158_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to plate 01 a second time: a blank cheque torn from
  {line: 'L5', id: 'p26', src: 'shorts/short158/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // an empty classroom of small desks
  {line: 'L5', id: 'p27', src: 'shorts/short158/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // coins dropping into a glass collection jar
  {line: 'L5', id: 'p28', src: 'shorts/short158/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // washing machines turning in a laundromat
  {line: 'L5', id: 'p29', src: 'shorts/short158/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // cardboard donation boxes stacked in a hall
  {line: 'L5', id: 'p30', src: 'shorts/short158/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // hands folding donated clothes into a box
  {line: 'L6', id: 'p31', src: 'shorts/short158/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // a paper road map spread across a table
  {line: 'L6', id: 'p32', src: 'shorts/short158/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // office shelves filled with ring binders
  {line: 'L6', id: 'p33', src: 'shorts/short158/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // an open plan office of empty desks
  {line: 'L6', id: 'p34', src: 'shorts/short158/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // a desk telephone and headset on an office desk
  {line: 'L6', id: 'p35', src: 'shorts/short158/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // a printer feeding blank pages into a tray
  {line: 'L7', id: 'p36', src: 'shorts/short158/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // two chairs facing each other by a window
  {line: 'L7', id: 'p37', src: 'shorts/short158/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // a desk lamp switched on over an empty desk
  {line: 'L7', id: 'p38', src: 'shorts/short158/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a school hallway lined with metal lockers
  {line: 'L7', id: 'p39', src: 'shorts/short158/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // a backpack hanging on the back of a chair
  {line: 'L7', id: 'p40', src: 'shorts/short158/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a pen and a blank notepad beside a coffee cup
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT158_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT158: ShortData = {
  shortId: 'short158',
  episodeId: 'PD-2026-019-varsityblues',
  durationSec: SHORT158_TOTAL_SEC,
  narrationSrc: 'shorts/short158/audio/short158_final_mix_v002_en_us.mp3',
  captions: SHORT158_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short158/short158_ctathumb.jpg',
  ctaLongTitle: "He sold a side door into America's",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
