// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #94.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT94_TOTAL_SEC = 57.199;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 7.291
  },
  {
    "id": "L2",
    "start": 7.511,
    "end": 13.92
  },
  {
    "id": "L3",
    "start": 14.14,
    "end": 19.806
  },
  {
    "id": "L4",
    "start": 20.026,
    "end": 26.574
  },
  {
    "id": "L5",
    "start": 26.794,
    "end": 34.549
  },
  {
    "id": "L6",
    "start": 34.769,
    "end": 40.806
  },
  {
    "id": "L7",
    "start": 41.026,
    "end": 48.038
  },
  {
    "id": "L8",
    "start": 48.258,
    "end": 56.199
  }
];

export const SHORT94_CAPTIONS: ShortCaption[] = [
  {
    "word": "A financial analyst worked out that",
    "startSec": 0.0,
    "endSec": 1.948
  },
  {
    "word": "the numbers could not be real.",
    "startSec": 1.948,
    "endSec": 3.618
  },
  {
    "word": "He told the regulators.",
    "startSec": 3.618,
    "endSec": 4.898
  },
  {
    "word": "For nearly ten years",
    "startSec": 4.898,
    "endSec": 6.011
  },
  {
    "word": "nobody listened to him.",
    "startSec": 6.011,
    "endSec": 7.291
  },
  {
    "word": "The fund went up in good",
    "startSec": 7.511,
    "endSec": 8.804
  },
  {
    "word": "times and up in bad times",
    "startSec": 8.804,
    "endSec": 10.15
  },
  {
    "word": "with almost none of the dips that",
    "startSec": 10.15,
    "endSec": 11.927
  },
  {
    "word": "real markets force on real investors.",
    "startSec": 11.927,
    "endSec": 13.92
  },
  {
    "word": "Like a player who never ever loses.",
    "startSec": 14.14,
    "endSec": 16.296
  },
  {
    "word": "Not because they are great",
    "startSec": 16.296,
    "endSec": 17.897
  },
  {
    "word": "but because the game is rigged.",
    "startSec": 17.897,
    "endSec": 19.806
  },
  {
    "word": "The later finding was not",
    "startSec": 20.026,
    "endSec": 21.437
  },
  {
    "word": "that the agency was corrupt.",
    "startSec": 21.437,
    "endSec": 23.018
  },
  {
    "word": "There is no evidence",
    "startSec": 23.018,
    "endSec": 24.147
  },
  {
    "word": "anyone was paid off.",
    "startSec": 24.147,
    "endSec": 25.276
  },
  {
    "word": "It was worse than that.",
    "startSec": 25.276,
    "endSec": 26.574
  },
  {
    "word": "He said it took him about five",
    "startSec": 26.794,
    "endSec": 28.909
  },
  {
    "word": "minutes to know something was wrong.",
    "startSec": 28.909,
    "endSec": 31.447
  },
  {
    "word": "He put the red flags in writing",
    "startSec": 31.447,
    "endSec": 33.633
  },
  {
    "word": "step by step.",
    "startSec": 33.633,
    "endSec": 34.549
  },
  {
    "word": "The scheme kept running and",
    "startSec": 34.769,
    "endSec": 36.307
  },
  {
    "word": "the money kept flowing",
    "startSec": 36.307,
    "endSec": 37.56
  },
  {
    "word": "because in a Ponzi scheme the",
    "startSec": 37.56,
    "endSec": 39.211
  },
  {
    "word": "new money is the only money.",
    "startSec": 39.211,
    "endSec": 40.806
  },
  {
    "word": "Nothing happened.",
    "startSec": 41.026,
    "endSec": 41.957
  },
  {
    "word": "The largest fraud in history",
    "startSec": 41.957,
    "endSec": 43.491
  },
  {
    "word": "continued in plain sight",
    "startSec": 43.491,
    "endSec": 44.806
  },
  {
    "word": "because the people with power to",
    "startSec": 44.806,
    "endSec": 46.559
  },
  {
    "word": "stop it never did the math.",
    "startSec": 46.559,
    "endSec": 48.038
  },
  {
    "word": "They had credible",
    "startSec": 48.258,
    "endSec": 49.313
  },
  {
    "word": "specific warnings for years",
    "startSec": 49.313,
    "endSec": 50.988
  },
  {
    "word": "and simply never ran them down.",
    "startSec": 50.988,
    "endSec": 52.911
  },
  {
    "word": "That was the finding. Not corruption.",
    "startSec": 52.911,
    "endSec": 55.206
  },
  {
    "word": "Something worse.",
    "startSec": 55.206,
    "endSec": 56.199
  }
];
