import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT276_CAPTIONS, SHORT276_TOTAL_SEC} from './short276_timing';

/**
 * short276 — Five to four: a company can break a law Congress wrote for you, and that alone does not get you into a federal courtroom.
 * Episode PD-2026-067-ramirez.  Type ?.
 *
 * AVOIDS: No claim the Court found the reports accurate; no damages figure; no assertion about what the ruling does to any other statute; no vote attributed to a justice who did not cast it.
 * LEAVES FOR THE LONG-FORM: The company could not confirm that a single alert it sold was accurate. Why was that not the question?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-067-ramirez.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short276/short276_01.png', kind: 'image', motion: 'parallax', fast: true},   // R042 approved episode plate
  {line: 'L1', id: 'p02', src: 'shorts/short276/short276_02.png', kind: 'image', motion: 'kenburns', fast: true},   // R053 approved episode plate
  {line: 'L2', id: 'p03', src: 'shorts/short276/short276_03.png', kind: 'image', motion: 'pushin'},   // R090 approved episode plate
  {line: 'L3', id: 'p04', src: 'shorts/short276/short276_04.png', kind: 'image', motion: 'parallax'},   // R091 approved episode plate
  {line: 'L4', id: 'p05', src: 'shorts/short276/short276_05.png', kind: 'image', motion: 'kenburns'},   // R039 approved episode plate
  {line: 'L5', id: 'p06', src: 'shorts/short276/short276_06.png', kind: 'image', motion: 'pushin'},   // R041 approved episode plate
  {line: 'L5', id: 'p07', src: 'shorts/short276/short276_07.png', kind: 'image', motion: 'parallax'},   // R092 approved episode plate
  {line: 'L6', id: 'p08', src: 'shorts/short276/short276_08.png', kind: 'image', motion: 'kenburns'},   // R094 approved episode plate
  {line: 'L7', id: 'p09', src: 'shorts/short276/short276_09.png', kind: 'image', motion: 'pushin'},   // R095 approved episode plate
  {line: 'L7', id: 'p10', src: 'shorts/short276/short276_10.png', kind: 'image', motion: 'parallax'},   // R096 approved episode plate
  {line: 'L8', id: 'p11', src: 'shorts/short276/short276_11.png', kind: 'image', motion: 'kenburns'},   // R017 approved episode plate
  {line: 'L8', id: 'p12', src: 'shorts/short276/short276_12.png', kind: 'image', motion: 'pushin', isCta: true, rewind: true, fast: true},   // R018 approved episode plate
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT276_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT276: ShortData = {
  shortId: 'short276',
  episodeId: 'PD-2026-067-ramirez',
  durationSec: SHORT276_TOTAL_SEC,
  narrationSrc: 'shorts/short276/audio/short276_final_mix_v002_en_us.mp3',
  captions: SHORT276_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short276/short276_ctathumb.jpg',
  ctaLongTitle: "A Salesman Said His Name...",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short276.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short276/short276_kin_concretely_harmed.webm', atSec: 11.66, durSec: 2.0, phrase: "CONCRETE HARM"},
    {src: 'shorts/short276/short276_kin_federal_courtroom.webm', atSec: 23.2, durSec: 2.0, phrase: "NOT ENOUGH TO SUE"},
  ],
};
