// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #55.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT55_TOTAL_SEC = 60.957;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.13
  },
  {
    "id": "L2",
    "start": 6.63,
    "end": 21.026
  },
  {
    "id": "L3",
    "start": 21.526,
    "end": 28.353
  },
  {
    "id": "L4",
    "start": 28.853,
    "end": 41.856
  },
  {
    "id": "L5",
    "start": 42.356,
    "end": 59.957
  }
];

export const SHORT55_CAPTIONS: ShortCaption[] = [
  {
    "word": "He ran out of a burning house",
    "startSec": 0.0,
    "endSec": 1.546
  },
  {
    "word": "screaming that his three little girls were still inside.",
    "startSec": 1.546,
    "endSec": 4.531
  },
  {
    "word": "Texas decided he set the fire.",
    "startSec": 4.531,
    "endSec": 6.13
  },
  {
    "word": "December 1991. Corsicana Texas.",
    "startSec": 6.63,
    "endSec": 8.622
  },
  {
    "word": "Neighbors hold Todd Willingham back from the flames.",
    "startSec": 8.622,
    "endSec": 11.964
  },
  {
    "word": "Then investigators walk the ashes and call",
    "startSec": 11.964,
    "endSec": 14.663
  },
  {
    "word": "the fire itself proof:",
    "startSec": 14.663,
    "endSec": 16.077
  },
  {
    "word": "roughly twenty indicators of arson.",
    "startSec": 16.077,
    "endSec": 18.327
  },
  {
    "word": "A jailhouse informant swears he confessed.",
    "startSec": 18.327,
    "endSec": 21.026
  },
  {
    "word": "Prosecutors offer a deal: plead guilty",
    "startSec": 21.526,
    "endSec": 24.045
  },
  {
    "word": "and you live. He refuses.",
    "startSec": 24.045,
    "endSec": 25.702
  },
  {
    "word": "He will not say he killed his daughters.",
    "startSec": 25.702,
    "endSec": 28.353
  },
  {
    "word": "Days before his execution",
    "startSec": 28.853,
    "endSec": 30.835
  },
  {
    "word": "a fire scientist reviews every indicator and",
    "startSec": 30.835,
    "endSec": 34.324
  },
  {
    "word": "warns the state in writing:",
    "startSec": 34.324,
    "endSec": 36.465
  },
  {
    "word": "this science is wrong.",
    "startSec": 36.465,
    "endSec": 38.209
  },
  {
    "word": "Texas executes him anyway. February 17th 2004.",
    "startSec": 38.209,
    "endSec": 41.856
  },
  {
    "word": "Then the part no one can take back.",
    "startSec": 42.356,
    "endSec": 44.51
  },
  {
    "word": "The state's own hired expert re-reads the case:",
    "startSec": 44.51,
    "endSec": 47.402
  },
  {
    "word": "a finding of arson could not be sustained.",
    "startSec": 47.402,
    "endSec": 49.987
  },
  {
    "word": "Five more experts agree",
    "startSec": 49.987,
    "endSec": 51.403
  },
  {
    "word": "none of the science was valid.",
    "startSec": 51.403,
    "endSec": 53.249
  },
  {
    "word": "The fire may never have been a",
    "startSec": 53.249,
    "endSec": 55.095
  },
  {
    "word": "crime at all.",
    "startSec": 55.095,
    "endSec": 55.895
  },
  {
    "word": "Follow for the cases they don't teach you",
    "startSec": 55.895,
    "endSec": 58.418
  },
  {
    "word": "full film on the channel.",
    "startSec": 58.418,
    "endSec": 59.957
  }
];
