// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #11.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT11_TOTAL_SEC = 42.812;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 4.458
  },
  {
    "id": "L2",
    "start": 6.958,
    "end": 13.274
  },
  {
    "id": "L3",
    "start": 15.774,
    "end": 22.09
  },
  {
    "id": "L4",
    "start": 24.59,
    "end": 36.154
  },
  {
    "id": "L5",
    "start": 38.654,
    "end": 41.812
  }
];

export const SHORT11_CAPTIONS: ShortCaption[] = [
  {
    "word": "A post you made on the weekend, from home.",
    "startSec": 0.0,
    "endSec": 2.464
  },
  {
    "word": "Can your school punish you for it?",
    "startSec": 2.464,
    "endSec": 4.458
  },
  {
    "word": "A fourteen-year-old didn't make the varsity cheer team, and vented on Snapchat, a post meant to disappear.",
    "startSec": 6.958,
    "endSec": 13.274
  },
  {
    "word": "But disappearing is a myth.",
    "startSec": 15.774,
    "endSec": 17.324
  },
  {
    "word": "A screenshot reached the coach, and the school suspended her from cheer for a year.",
    "startSec": 17.324,
    "endSec": 22.09
  },
  {
    "word": "In 2021, the Supreme Court ruled eight to one: schools usually can't punish ordinary off-campus speech.",
    "startSec": 24.59,
    "endSec": 31.099
  },
  {
    "word": "Threats and bullying are different.",
    "startSec": 31.099,
    "endSec": 33.31
  },
  {
    "word": "The line between home and school was redrawn.",
    "startSec": 33.31,
    "endSec": 36.154
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 38.654,
    "endSec": 40.84
  },
  {
    "word": "Follow for more.",
    "startSec": 40.84,
    "endSec": 41.812
  }
];
