// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #111.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT111_TOTAL_SEC = 59.662;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.759
  },
  {
    "id": "L2",
    "start": 5.979,
    "end": 12.341
  },
  {
    "id": "L3",
    "start": 12.561,
    "end": 24.496
  },
  {
    "id": "L4",
    "start": 24.716,
    "end": 33.447
  },
  {
    "id": "L5",
    "start": 33.667,
    "end": 40.354
  },
  {
    "id": "L6",
    "start": 40.574,
    "end": 45.497
  },
  {
    "id": "L7",
    "start": 45.717,
    "end": 52.219
  },
  {
    "id": "L8",
    "start": 52.439,
    "end": 58.662
  }
];

export const SHORT111_CAPTIONS: ShortCaption[] = [
  {
    "word": "A guilty person goes free.",
    "startSec": 0.0,
    "endSec": 1.645
  },
  {
    "word": "Not because the evidence was wrong.",
    "startSec": 1.645,
    "endSec": 3.86
  },
  {
    "word": "Because police made a mistake.",
    "startSec": 3.86,
    "endSec": 5.759
  },
  {
    "word": "That is the cost",
    "startSec": 5.979,
    "endSec": 6.913
  },
  {
    "word": "of the Mapp rule.",
    "startSec": 6.913,
    "endSec": 7.905
  },
  {
    "word": "Throw out an illegal search",
    "startSec": 7.905,
    "endSec": 9.481
  },
  {
    "word": "and you sometimes throw out",
    "startSec": 9.481,
    "endSec": 11.057
  },
  {
    "word": "evidence that is true.",
    "startSec": 11.057,
    "endSec": 12.341
  },
  {
    "word": "In 1926",
    "startSec": 12.561,
    "endSec": 13.261
  },
  {
    "word": "a New York judge named Benjamin",
    "startSec": 13.261,
    "endSec": 15.208
  },
  {
    "word": "Cardozo put the objection as bluntly",
    "startSec": 15.208,
    "endSec": 17.47
  },
  {
    "word": "as it can be put.",
    "startSec": 17.47,
    "endSec": 18.538
  },
  {
    "word": "If the police bungle a search",
    "startSec": 18.538,
    "endSec": 20.359
  },
  {
    "word": "he wrote",
    "startSec": 20.359,
    "endSec": 21.059
  },
  {
    "word": "the criminal is to go free",
    "startSec": 21.059,
    "endSec": 22.692
  },
  {
    "word": "because the constable has blundered.",
    "startSec": 22.692,
    "endSec": 24.496
  },
  {
    "word": "That tension has never gone away.",
    "startSec": 24.716,
    "endSec": 26.703
  },
  {
    "word": "The Court has been carving exceptions",
    "startSec": 26.703,
    "endSec": 28.931
  },
  {
    "word": "into its own rule ever since.",
    "startSec": 28.931,
    "endSec": 30.677
  },
  {
    "word": "The rule today is narrower",
    "startSec": 30.677,
    "endSec": 32.243
  },
  {
    "word": "than it was in 1961.",
    "startSec": 32.243,
    "endSec": 33.447
  },
  {
    "word": "Before 1961",
    "startSec": 33.667,
    "endSec": 34.367
  },
  {
    "word": "most states could use what",
    "startSec": 34.367,
    "endSec": 35.992
  },
  {
    "word": "an illegal search turned up. Wolf v.",
    "startSec": 35.992,
    "endSec": 38.242
  },
  {
    "word": "Colorado left them free to choose.",
    "startSec": 38.242,
    "endSec": 40.354
  },
  {
    "word": "The Court answered with a principle.",
    "startSec": 40.574,
    "endSec": 42.588
  },
  {
    "word": "A real right needs a real",
    "startSec": 42.588,
    "endSec": 43.987
  },
  {
    "word": "remedy when it is violated.",
    "startSec": 43.987,
    "endSec": 45.497
  },
  {
    "word": "Without one",
    "startSec": 45.717,
    "endSec": 46.432
  },
  {
    "word": "the Court said",
    "startSec": 46.432,
    "endSec": 47.343
  },
  {
    "word": "the protection becomes a form of words:",
    "startSec": 47.343,
    "endSec": 49.878
  },
  {
    "word": "a guarantee nobody can actually use.",
    "startSec": 49.878,
    "endSec": 52.219
  },
  {
    "word": "So the core of the rule survives",
    "startSec": 52.439,
    "endSec": 54.336
  },
  {
    "word": "exceptions and all",
    "startSec": 54.336,
    "endSec": 55.402
  },
  {
    "word": "and it still ends cases.",
    "startSec": 55.402,
    "endSec": 56.825
  },
  {
    "word": "Which means this happens again.",
    "startSec": 56.825,
    "endSec": 58.662
  }
];
