// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #110.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT110_TOTAL_SEC = 37.22;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 2.972
  },
  {
    "id": "L2",
    "start": 3.192,
    "end": 12.619
  },
  {
    "id": "L3",
    "start": 12.839,
    "end": 21.988
  },
  {
    "id": "L4",
    "start": 22.208,
    "end": 30.567
  },
  {
    "id": "L5",
    "start": 30.787,
    "end": 36.22
  }
];

export const SHORT110_CAPTIONS: ShortCaption[] = [
  {
    "word": "You think Miranda was one man's case.",
    "startSec": 0.0,
    "endSec": 2.244
  },
  {
    "word": "It was four.",
    "startSec": 2.244,
    "endSec": 2.972
  },
  {
    "word": "Ernesto Miranda's appeal did not travel",
    "startSec": 3.192,
    "endSec": 5.504
  },
  {
    "word": "to the Supreme Court alone.",
    "startSec": 5.504,
    "endSec": 7.105
  },
  {
    "word": "Three other cases were folded in.",
    "startSec": 7.105,
    "endSec": 9.062
  },
  {
    "word": "Four defendants.",
    "startSec": 9.062,
    "endSec": 10.01
  },
  {
    "word": "Four interrogation rooms.",
    "startSec": 10.01,
    "endSec": 11.493
  },
  {
    "word": "One shared problem.",
    "startSec": 11.493,
    "endSec": 12.619
  },
  {
    "word": "That combination is a signal.",
    "startSec": 12.839,
    "endSec": 14.734
  },
  {
    "word": "When the Court pulls four",
    "startSec": 14.734,
    "endSec": 16.368
  },
  {
    "word": "cases under a single name",
    "startSec": 16.368,
    "endSec": 18.002
  },
  {
    "word": "it is not fixing",
    "startSec": 18.002,
    "endSec": 19.047
  },
  {
    "word": "one man's bad day.",
    "startSec": 19.047,
    "endSec": 20.224
  },
  {
    "word": "It is looking at a pattern.",
    "startSec": 20.224,
    "endSec": 21.988
  },
  {
    "word": "So the question changed. Not",
    "startSec": 22.208,
    "endSec": 23.981
  },
  {
    "word": "was this one confession unfair.",
    "startSec": 23.981,
    "endSec": 25.944
  },
  {
    "word": "But what has to be true",
    "startSec": 25.944,
    "endSec": 27.401
  },
  {
    "word": "every time",
    "startSec": 27.401,
    "endSec": 28.101
  },
  {
    "word": "before any confession can",
    "startSec": 28.101,
    "endSec": 29.684
  },
  {
    "word": "be used at all.",
    "startSec": 29.684,
    "endSec": 30.567
  },
  {
    "word": "The name on the case",
    "startSec": 30.787,
    "endSec": 31.852
  },
  {
    "word": "belongs to one man.",
    "startSec": 31.852,
    "endSec": 32.864
  },
  {
    "word": "Count the interrogation rooms the",
    "startSec": 32.864,
    "endSec": 34.622
  },
  {
    "word": "Court was actually looking at.",
    "startSec": 34.622,
    "endSec": 36.22
  }
];
