// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #116.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT116_TOTAL_SEC = 39.775;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 4.087
  },
  {
    "id": "L2",
    "start": 4.307,
    "end": 12.248
  },
  {
    "id": "L3",
    "start": 12.468,
    "end": 21.802
  },
  {
    "id": "L4",
    "start": 22.022,
    "end": 31.589
  },
  {
    "id": "L5",
    "start": 31.809,
    "end": 38.775
  }
];

export const SHORT116_CAPTIONS: ShortCaption[] = [
  {
    "word": "Nine to nothing",
    "startSec": 0.0,
    "endSec": 0.807
  },
  {
    "word": "and the Court still did",
    "startSec": 0.807,
    "endSec": 2.043
  },
  {
    "word": "not call the seizure unconstitutional.",
    "startSec": 2.043,
    "endSec": 4.087
  },
  {
    "word": "Read the ruling carefully.",
    "startSec": 4.307,
    "endSec": 5.883
  },
  {
    "word": "It did not declare that taking",
    "startSec": 5.883,
    "endSec": 7.702
  },
  {
    "word": "Tyson Timbs's car was unconstitutional.",
    "startSec": 7.702,
    "endSec": 10.066
  },
  {
    "word": "It did not abolish civil forfeiture.",
    "startSec": 10.066,
    "endSec": 12.248
  },
  {
    "word": "It did something narrower.",
    "startSec": 12.468,
    "endSec": 13.975
  },
  {
    "word": "It sent the case back to Indiana",
    "startSec": 13.975,
    "endSec": 15.831
  },
  {
    "word": "and made whether a forfeiture is",
    "startSec": 15.831,
    "endSec": 17.686
  },
  {
    "word": "an excessive fine a real constitutional",
    "startSec": 17.686,
    "endSec": 19.947
  },
  {
    "word": "question the states must answer.",
    "startSec": 19.947,
    "endSec": 21.802
  },
  {
    "word": "So it is a limit",
    "startSec": 22.022,
    "endSec": 22.95
  },
  {
    "word": "not an ending.",
    "startSec": 22.95,
    "endSec": 23.761
  },
  {
    "word": "Police can still seize property.",
    "startSec": 23.761,
    "endSec": 25.617
  },
  {
    "word": "There is now a ceiling",
    "startSec": 25.617,
    "endSec": 26.892
  },
  {
    "word": "but you have to know it exists",
    "startSec": 26.892,
    "endSec": 28.632
  },
  {
    "word": "and fight for years to reach it.",
    "startSec": 28.632,
    "endSec": 30.487
  },
  {
    "word": "Most people cannot.",
    "startSec": 30.487,
    "endSec": 31.589
  },
  {
    "word": "A unanimous Supreme Court win can still",
    "startSec": 31.809,
    "endSec": 34.018
  },
  {
    "word": "leave you roughly where you started",
    "startSec": 34.018,
    "endSec": 36.0
  },
  {
    "word": "with a limit on paper",
    "startSec": 36.0,
    "endSec": 37.189
  },
  {
    "word": "and years of fighting ahead.",
    "startSec": 37.189,
    "endSec": 38.775
  }
];
