// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #157.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT157_TOTAL_SEC = 37.406;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.223
  },
  {
    "id": "L2",
    "start": 6.443,
    "end": 14.477
  },
  {
    "id": "L3",
    "start": 14.697,
    "end": 23.428
  },
  {
    "id": "L4",
    "start": 23.648,
    "end": 28.013
  },
  {
    "id": "L5",
    "start": 28.233,
    "end": 36.406
  }
];

export const SHORT157_CAPTIONS: ShortCaption[] = [
  {
    "word": "When investigators finally opened up his life",
    "startSec": 0.0,
    "endSec": 3.111
  },
  {
    "word": "the fortune was mostly gone. Not spent.",
    "startSec": 3.111,
    "endSec": 5.808
  },
  {
    "word": "Taken.",
    "startSec": 5.808,
    "endSec": 6.223
  },
  {
    "word": "He had handed his money",
    "startSec": 6.443,
    "endSec": 7.782
  },
  {
    "word": "almost all of it",
    "startSec": 7.782,
    "endSec": 8.713
  },
  {
    "word": "to con men",
    "startSec": 8.713,
    "endSec": 9.413
  },
  {
    "word": "to bogus investments",
    "startSec": 9.413,
    "endSec": 10.578
  },
  {
    "word": "to an outright fraud built to",
    "startSec": 10.578,
    "endSec": 12.266
  },
  {
    "word": "part trusting people from their savings.",
    "startSec": 12.266,
    "endSec": 14.477
  },
  {
    "word": "People who knew him describe a",
    "startSec": 14.697,
    "endSec": 16.455
  },
  {
    "word": "man trading the way a child",
    "startSec": 16.455,
    "endSec": 18.037
  },
  {
    "word": "plays an arcade game.",
    "startSec": 18.037,
    "endSec": 19.268
  },
  {
    "word": "Locked onto the screen",
    "startSec": 19.268,
    "endSec": 20.557
  },
  {
    "word": "hour after hour",
    "startSec": 20.557,
    "endSec": 21.436
  },
  {
    "word": "trying to beat his own high score.",
    "startSec": 21.436,
    "endSec": 23.428
  },
  {
    "word": "He had beaten the high score",
    "startSec": 23.648,
    "endSec": 25.069
  },
  {
    "word": "over and over for years",
    "startSec": 25.069,
    "endSec": 26.237
  },
  {
    "word": "and kept almost none of the points.",
    "startSec": 26.237,
    "endSec": 28.013
  },
  {
    "word": "At his sentencing the",
    "startSec": 28.233,
    "endSec": 29.468
  },
  {
    "word": "prosecutors did something rare.",
    "startSec": 29.468,
    "endSec": 31.291
  },
  {
    "word": "They asked the judge for mercy.",
    "startSec": 31.291,
    "endSec": 33.113
  },
  {
    "word": "He served no further prison at all",
    "startSec": 33.113,
    "endSec": 35.112
  },
  {
    "word": "a single year at home.",
    "startSec": 35.112,
    "endSec": 36.406
  }
];
