import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT252_CAPTIONS, SHORT252_TOTAL_SEC} from './short252_timing';

/**
 * short252 — The office that won every one of those convictions went back through its own files and counted four hundred and sixteen of its own errors.
 * Episode PD-2026-057-fieldtest.  Type ?.
 *
 * AVOIDS: This Short is only the count and the letter. It does not explain the kit, and it does not run the plea-speed arithmetic the second Short carries.
 * LEAVES FOR THE LONG-FORM: What happened to the hundred and seventy-two convictions that were still standing after the office finished counting?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-057-fieldtest.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short252/short252_01.png', kind: 'image', motion: 'parallax', fast: true},   // a wall of steel shelves packed with unlabelled folders
  {line: 'L1', id: 'p02', src: 'shorts/short252/short252_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a records room aisle stacked to the ceiling
  {line: 'L1', id: 'p03', src: 'shorts/short252/short252_03.png', kind: 'image', motion: 'pushin', fast: true},   // a leaning tower of worn case folders
  {line: 'L1', id: 'p04', src: 'shorts/short252/short252_04.png', kind: 'image', motion: 'parallax'},   // an in-tray overflowing with blank forms
  {line: 'L2', id: 'p05', src: 'shorts/short252/short252_05.png', kind: 'image', motion: 'kenburns'},   // a gavel caught mid-strike above its block
  {line: 'L2', id: 'p06', src: 'shorts/short252/short252_06.png', kind: 'image', motion: 'pushin'},   // a thick file closed and tied with a band
  {line: 'L2', id: 'p07', src: 'shorts/short252/short252_07.png', kind: 'image', motion: 'parallax'},   // a laboratory bench with a heavy instrument
  {line: 'L2', id: 'p08', src: 'shorts/short252/short252_08.png', kind: 'image', motion: 'kenburns'},   // a sealed evidence envelope on a steel counter
  {line: 'L2', id: 'p09', src: 'shorts/short252/short252_09.png', kind: 'image', motion: 'pushin'},   // a hand pressing a pen to a blank sheet
  {line: 'L2', id: 'p10', src: 'shorts/short252/short252_10.png', kind: 'image', motion: 'parallax'},   // a rubber stamp resting on an ink pad
  {line: 'L2', id: 'p11', src: 'shorts/short252/short252_11.png', kind: 'image', motion: 'kenburns'},   // a window at first light over a desk of blank folders
  {line: 'L3', id: 'p12', src: 'shorts/short252/short252_12.png', kind: 'image', motion: 'pushin'},   // rows of empty courtroom gallery benches
  {line: 'L3', id: 'p13', src: 'shorts/short252/short252_13.png', kind: 'image', motion: 'parallax'},   // a judge's high bench from the floor, empty
  {line: 'L3', id: 'p14', src: 'shorts/short252/short252_14.png', kind: 'image', motion: 'kenburns'},   // a single empty chair in a cone of light
  {line: 'L3', id: 'p15', src: 'shorts/short252/short252_15.png', kind: 'image', motion: 'pushin'},   // two weathered hands laid flat on a table
  {line: 'L3', id: 'p16', src: 'shorts/short252/short252_16.png', kind: 'image', motion: 'parallax'},   // a shaft of light crossing an empty room, thick with dust
  {line: 'L4', id: 'p17', src: 'shorts/short252/short252_17.png', kind: 'image', motion: 'kenburns'},   // a cruiser fender and roof beacon, tight
  {line: 'L4', id: 'p18', src: 'shorts/short252/short252_18.png', kind: 'image', motion: 'pushin'},   // a car interior washed by beacons from behind
  {line: 'L4', id: 'p19', src: 'shorts/short252/short252_19.png', kind: 'image', motion: 'parallax'},   // handcuffs closing on a pair of wrists
  {line: 'L4', id: 'p20', src: 'shorts/short252/short252_20.png', kind: 'image', motion: 'kenburns'},   // a booking tray of personal effects
  {line: 'L4', id: 'p21', src: 'shorts/short252/short252_21.png', kind: 'image', motion: 'pushin'},   // a cell block corridor of steel doors
  {line: 'L4', id: 'p22', src: 'shorts/short252/short252_22.png', kind: 'image', motion: 'parallax'},   // cell bars in extreme close-up
  {line: 'L8', id: 'p23', src: 'shorts/short252/short252_03.png', kind: 'image', motion: 'pushin'},   // return to the hook plate: a wall of steel shelves packed w
  {line: 'L8', id: 'p24', src: 'shorts/short252/short252_02.png', kind: 'image', motion: 'kenburns'},   // replay of the opening framing: a wall of steel shelves pac
  {line: 'L8', id: 'p25', src: 'shorts/short252/short252_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to plate 01 a third time: a wall of steel shelves p
  {line: 'L5', id: 'p26', src: 'shorts/short252/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // a bare prison cell with a barred window
  {line: 'L5', id: 'p27', src: 'shorts/short252/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // a figure standing behind prison bars
  {line: 'L5', id: 'p28', src: 'shorts/short252/short252_28.png', kind: 'image', motion: 'parallax'},   // a long corridor leading to a lit doorway
  {line: 'L5', id: 'p29', src: 'shorts/short252/short252_29.png', kind: 'image', motion: 'kenburns'},   // a silhouette standing in a bright doorway
  {line: 'L5', id: 'p30', src: 'shorts/short252/short252_30.png', kind: 'image', motion: 'pushin'},   // calendar pages turning on a wall
  {line: 'L6', id: 'p31', src: 'shorts/short252/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // a letter slot in a front door
  {line: 'L6', id: 'p32', src: 'shorts/short252/short252_32.png', kind: 'image', motion: 'kenburns'},   // a hand sliding a letter into an envelope
  {line: 'L6', id: 'p33', src: 'shorts/short252/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // an office corridor of identical closed doors
  {line: 'L6', id: 'p34', src: 'shorts/short252/short252_34.png', kind: 'image', motion: 'parallax'},   // an empty office with a long table and chairs
  {line: 'L6', id: 'p35', src: 'shorts/short252/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // a lamp burning over a stack of envelopes
  {line: 'L7', id: 'p36', src: 'shorts/short252/short252_36.png', kind: 'image', motion: 'pushin'},   // a residential front door seen from a hallway
  {line: 'L7', id: 'p37', src: 'shorts/short252/short252_37.png', kind: 'image', motion: 'parallax'},   // a padlock and chain fastened on a door
  {line: 'L7', id: 'p38', src: 'shorts/short252/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // an apartment door standing open to daylight
  {line: 'L7', id: 'p39', src: 'shorts/short252/short252_39.png', kind: 'image', motion: 'pushin'},   // an envelope lying on a doormat
  {line: 'L7', id: 'p40', src: 'shorts/short252/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a person walking away along a walkway
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT252_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT252: ShortData = {
  shortId: 'short252',
  episodeId: 'PD-2026-057-fieldtest',
  durationSec: SHORT252_TOTAL_SEC,
  narrationSrc: 'shorts/short252/audio/short252_final_mix_v002_en_us.mp3',
  captions: SHORT252_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short252/short252_ctathumb.jpg',
  ctaLongTitle: "A $2 Test Turned Blue. She Served 21",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short252.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short252/short252_kin_a.webm', atSec: 20.47, durSec: 2.3, phrase: "251 CASES NO DRUGS"},
    {src: 'shorts/short252/short252_kin_b.webm', atSec: 30.05, durSec: 2.3, phrase: "93% WENT TO JAIL"},
  ],
};
