// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #140.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT140_TOTAL_SEC = 61.472;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 4.644
  },
  {
    "id": "L2",
    "start": 4.864,
    "end": 12.759
  },
  {
    "id": "L3",
    "start": 12.979,
    "end": 23.01
  },
  {
    "id": "L4",
    "start": 23.23,
    "end": 31.914
  },
  {
    "id": "L5",
    "start": 32.134,
    "end": 40.307
  },
  {
    "id": "L6",
    "start": 40.527,
    "end": 46.704
  },
  {
    "id": "L7",
    "start": 46.924,
    "end": 51.614
  },
  {
    "id": "L8",
    "start": 51.834,
    "end": 60.472
  }
];

export const SHORT140_CAPTIONS: ShortCaption[] = [
  {
    "word": "The Supreme Court took away the",
    "startSec": 0.0,
    "endSec": 1.548
  },
  {
    "word": "right to sue over a skipped",
    "startSec": 1.548,
    "endSec": 2.896
  },
  {
    "word": "Miranda warning using one metaphor.",
    "startSec": 2.896,
    "endSec": 4.644
  },
  {
    "word": "Writing for six justices",
    "startSec": 4.864,
    "endSec": 6.247
  },
  {
    "word": "Justice Samuel Alito called",
    "startSec": 6.247,
    "endSec": 7.803
  },
  {
    "word": "the warnings prophylactic rules.",
    "startSec": 7.803,
    "endSec": 9.647
  },
  {
    "word": "Picture a protective fence built",
    "startSec": 9.647,
    "endSec": 11.491
  },
  {
    "word": "around a deeper right.",
    "startSec": 11.491,
    "endSec": 12.759
  },
  {
    "word": "The Fifth Amendment promise that no one",
    "startSec": 12.979,
    "endSec": 15.214
  },
  {
    "word": "can force you to incriminate yourself.",
    "startSec": 15.214,
    "endSec": 17.393
  },
  {
    "word": "The warnings guard that inner right.",
    "startSec": 17.393,
    "endSec": 19.456
  },
  {
    "word": "But they are not the right.",
    "startSec": 19.456,
    "endSec": 21.004
  },
  {
    "word": "A fence",
    "startSec": 21.004,
    "endSec": 21.704
  },
  {
    "word": "not the ground it stands on.",
    "startSec": 21.704,
    "endSec": 23.01
  },
  {
    "word": "From that one distinction the rest follows.",
    "startSec": 23.23,
    "endSec": 25.703
  },
  {
    "word": "Failing to give the warnings is not",
    "startSec": 25.703,
    "endSec": 27.716
  },
  {
    "word": "on its own",
    "startSec": 27.716,
    "endSec": 28.416
  },
  {
    "word": "a violation of the Constitution.",
    "startSec": 28.416,
    "endSec": 30.256
  },
  {
    "word": "So there is nothing to pay for.",
    "startSec": 30.256,
    "endSec": 31.914
  },
  {
    "word": "The majority insisted the",
    "startSec": 32.134,
    "endSec": 33.88
  },
  {
    "word": "warning still carries weight.",
    "startSec": 33.88,
    "endSec": 35.906
  },
  {
    "word": "A criminal court can still bar",
    "startSec": 35.906,
    "endSec": 38.002
  },
  {
    "word": "the prosecution from those words.",
    "startSec": 38.002,
    "endSec": 40.307
  },
  {
    "word": "That protection at trial",
    "startSec": 40.527,
    "endSec": 41.912
  },
  {
    "word": "Justice Alito wrote",
    "startSec": 41.912,
    "endSec": 43.009
  },
  {
    "word": "is remedy enough.",
    "startSec": 43.009,
    "endSec": 43.991
  },
  {
    "word": "The door the Court closed",
    "startSec": 43.991,
    "endSec": 45.434
  },
  {
    "word": "was the later lawsuit.",
    "startSec": 45.434,
    "endSec": 46.704
  },
  {
    "word": "A jury can clear you",
    "startSec": 46.924,
    "endSec": 47.955
  },
  {
    "word": "and no civil court will make the",
    "startSec": 47.955,
    "endSec": 49.604
  },
  {
    "word": "officer pay for the warning he skipped.",
    "startSec": 49.604,
    "endSec": 51.614
  },
  {
    "word": "Three justices refused to accept that.",
    "startSec": 51.834,
    "endSec": 54.439
  },
  {
    "word": "A right nobody can enforce",
    "startSec": 54.439,
    "endSec": 56.222
  },
  {
    "word": "they warned in dissent",
    "startSec": 56.222,
    "endSec": 57.73
  },
  {
    "word": "slowly stops feeling like",
    "startSec": 57.73,
    "endSec": 59.444
  },
  {
    "word": "a right at all.",
    "startSec": 59.444,
    "endSec": 60.472
  }
];
