// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #153.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT153_TOTAL_SEC = 55.25;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 3.437
  },
  {
    "id": "L2",
    "start": 3.657,
    "end": 9.137
  },
  {
    "id": "L3",
    "start": 9.357,
    "end": 18.227
  },
  {
    "id": "L4",
    "start": 18.447,
    "end": 27.271
  },
  {
    "id": "L5",
    "start": 27.491,
    "end": 33.946
  },
  {
    "id": "L6",
    "start": 34.166,
    "end": 42.061
  },
  {
    "id": "L7",
    "start": 42.281,
    "end": 47.807
  },
  {
    "id": "L8",
    "start": 48.027,
    "end": 54.25
  }
];

export const SHORT153_CAPTIONS: ShortCaption[] = [
  {
    "word": "His defense boiled down:",
    "startSec": 0.0,
    "endSec": 1.447
  },
  {
    "word": "mistakes were made",
    "startSec": 1.447,
    "endSec": 2.533
  },
  {
    "word": "but not crimes.",
    "startSec": 2.533,
    "endSec": 3.437
  },
  {
    "word": "The problem was who sat",
    "startSec": 3.657,
    "endSec": 5.042
  },
  {
    "word": "in the witness chair.",
    "startSec": 5.042,
    "endSec": 6.307
  },
  {
    "word": "Not outside investigators.",
    "startSec": 6.307,
    "endSec": 7.872
  },
  {
    "word": "His own inner circle.",
    "startSec": 7.872,
    "endSec": 9.137
  },
  {
    "word": "The co-founder who built the",
    "startSec": 9.357,
    "endSec": 10.929
  },
  {
    "word": "code with him described out loud",
    "startSec": 10.929,
    "endSec": 12.725
  },
  {
    "word": "the secret setting that",
    "startSec": 12.725,
    "endSec": 14.017
  },
  {
    "word": "let the money move.",
    "startSec": 14.017,
    "endSec": 15.083
  },
  {
    "word": "They testified the use of",
    "startSec": 15.083,
    "endSec": 16.487
  },
  {
    "word": "customer money was no accident.",
    "startSec": 16.487,
    "endSec": 18.227
  },
  {
    "word": "On November 2nd 2023",
    "startSec": 18.447,
    "endSec": 19.794
  },
  {
    "word": "the jury went out.",
    "startSec": 19.794,
    "endSec": 21.007
  },
  {
    "word": "It was back in a few hours.",
    "startSec": 21.007,
    "endSec": 22.825
  },
  {
    "word": "Guilty on all seven counts. Wire fraud",
    "startSec": 22.825,
    "endSec": 25.385
  },
  {
    "word": "conspiracy money laundering.",
    "startSec": 25.385,
    "endSec": 27.271
  },
  {
    "word": "Prosecutors called it one of the",
    "startSec": 27.491,
    "endSec": 28.956
  },
  {
    "word": "biggest financial frauds in American history.",
    "startSec": 28.956,
    "endSec": 31.016
  },
  {
    "word": "FTX was bankrupt",
    "startSec": 31.016,
    "endSec": 31.749
  },
  {
    "word": "and the arena scrubbed its",
    "startSec": 31.749,
    "endSec": 32.939
  },
  {
    "word": "name off the building.",
    "startSec": 32.939,
    "endSec": 33.946
  },
  {
    "word": "Through years of bankruptcy proceedings",
    "startSec": 34.166,
    "endSec": 36.43
  },
  {
    "word": "much of the money was",
    "startSec": 36.43,
    "endSec": 37.649
  },
  {
    "word": "eventually clawed back for customers years later",
    "startSec": 37.649,
    "endSec": 40.436
  },
  {
    "word": "by fighting through a court.",
    "startSec": 40.436,
    "endSec": 42.061
  },
  {
    "word": "To the million customers",
    "startSec": 42.281,
    "endSec": 43.634
  },
  {
    "word": "the balance on the screen was real.",
    "startSec": 43.634,
    "endSec": 45.608
  },
  {
    "word": "On the night it mattered",
    "startSec": 45.608,
    "endSec": 46.961
  },
  {
    "word": "it was a ghost.",
    "startSec": 46.961,
    "endSec": 47.807
  },
  {
    "word": "The jury did not buy it.",
    "startSec": 48.027,
    "endSec": 49.326
  },
  {
    "word": "Twenty-five years in federal prison",
    "startSec": 49.326,
    "endSec": 51.22
  },
  {
    "word": "and an order to forfeit",
    "startSec": 51.22,
    "endSec": 52.464
  },
  {
    "word": "more than eleven billion dollars.",
    "startSec": 52.464,
    "endSec": 54.25
  }
];
