// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #305.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT305_TOTAL_SEC = 57.756;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 8.313
  },
  {
    "id": "L2",
    "start": 8.533,
    "end": 16.149
  },
  {
    "id": "L3",
    "start": 16.369,
    "end": 22.638
  },
  {
    "id": "L4",
    "start": 22.858,
    "end": 30.892
  },
  {
    "id": "L5",
    "start": 31.112,
    "end": 34.874
  },
  {
    "id": "L6",
    "start": 35.094,
    "end": 42.524
  },
  {
    "id": "L7",
    "start": 42.744,
    "end": 49.942
  },
  {
    "id": "L8",
    "start": 50.162,
    "end": 56.756
  }
];

export const SHORT305_CAPTIONS: ShortCaption[] = [
  {
    "word": "Before the investigation reached any",
    "startSec": 0.0,
    "endSec": 2.217
  },
  {
    "word": "question of who did what",
    "startSec": 2.217,
    "endSec": 3.695
  },
  {
    "word": "it looked at the tank cars",
    "startSec": 3.695,
    "endSec": 5.296
  },
  {
    "word": "and what it found there",
    "startSec": 5.296,
    "endSec": 6.712
  },
  {
    "word": "is its own kind of answer.",
    "startSec": 6.712,
    "endSec": 8.313
  },
  {
    "word": "All sixty-three",
    "startSec": 8.533,
    "endSec": 9.373
  },
  {
    "word": "of the derailed cars had been built",
    "startSec": 9.373,
    "endSec": 11.333
  },
  {
    "word": "to a single specification.",
    "startSec": 11.333,
    "endSec": 12.789
  },
  {
    "word": "Seventy-eight per cent of them were less",
    "startSec": 12.789,
    "endSec": 15.029
  },
  {
    "word": "than five years old.",
    "startSec": 15.029,
    "endSec": 16.149
  },
  {
    "word": "Fifty-nine of the sixty-three were breached.",
    "startSec": 16.369,
    "endSec": 18.789
  },
  {
    "word": "Ninety-four per cent.",
    "startSec": 18.789,
    "endSec": 19.943
  },
  {
    "word": "Thirty-seven of them were holed",
    "startSec": 19.943,
    "endSec": 21.648
  },
  {
    "word": "through the shell.",
    "startSec": 21.648,
    "endSec": 22.638
  },
  {
    "word": "All sixty-three derailed tank cars",
    "startSec": 22.858,
    "endSec": 24.667
  },
  {
    "word": "were in compliance",
    "startSec": 24.667,
    "endSec": 25.625
  },
  {
    "word": "with the specification requirement",
    "startSec": 25.625,
    "endSec": 27.434
  },
  {
    "word": "that was in effect at the time",
    "startSec": 27.434,
    "endSec": 29.03
  },
  {
    "word": "of their approval and construction.",
    "startSec": 29.03,
    "endSec": 30.892
  },
  {
    "word": "They were legal.",
    "startSec": 31.112,
    "endSec": 31.972
  },
  {
    "word": "They were current.",
    "startSec": 31.972,
    "endSec": 32.939
  },
  {
    "word": "Ninety-four per cent of them opened.",
    "startSec": 32.939,
    "endSec": 34.874
  },
  {
    "word": "Compliance is not a description",
    "startSec": 35.094,
    "endSec": 36.908
  },
  {
    "word": "of how strong something is.",
    "startSec": 36.908,
    "endSec": 38.487
  },
  {
    "word": "It is a description",
    "startSec": 38.487,
    "endSec": 39.599
  },
  {
    "word": "of what was asked of it",
    "startSec": 39.599,
    "endSec": 40.944
  },
  {
    "word": "on the day it was approved.",
    "startSec": 40.944,
    "endSec": 42.524
  },
  {
    "word": "A car built in nineteen eighty",
    "startSec": 42.744,
    "endSec": 44.344
  },
  {
    "word": "and a car built",
    "startSec": 44.344,
    "endSec": 45.143
  },
  {
    "word": "in twenty twelve were both in compliance",
    "startSec": 45.143,
    "endSec": 47.276
  },
  {
    "word": "because the requirement had not moved",
    "startSec": 47.276,
    "endSec": 49.249
  },
  {
    "word": "between them.",
    "startSec": 49.249,
    "endSec": 49.942
  },
  {
    "word": "The damage clearly indicated",
    "startSec": 50.162,
    "endSec": 51.571
  },
  {
    "word": "that product release",
    "startSec": 51.571,
    "endSec": 52.578
  },
  {
    "word": "could have been reduced had the tank",
    "startSec": 52.578,
    "endSec": 54.39
  },
  {
    "word": "car shells",
    "startSec": 54.39,
    "endSec": 55.09
  },
  {
    "word": "and heads been more impact-resistant.",
    "startSec": 55.09,
    "endSec": 56.756
  }
];
