import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT103_CAPTIONS, SHORT103_TOTAL_SEC} from './short103_timing';

/**
 * short103 — The Court did not say police can never come in for your safety.
 * Episode PD-2026-043-caniglia.  Type A — the correction to what everyone takes away.
 *
 * AVOIDS: short53 lands on 'they left his house carrying his guns'. The limit of the 2021 ruling is not in it, and getting it wrong is dangerous in the other direction.
 * LEAVES FOR THE LONG-FORM: So where exactly is the line between help and a search?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-043-caniglia.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short103/short103_01.png', kind: 'image', motion: 'parallax', fast: true},   // a front door swinging shut on a narrowing blade of porch l
  {line: 'L1', id: 'p02', src: 'shorts/short103/short103_02.png', kind: 'image', motion: 'kenburns', fast: true},   // courthouse columns from directly below
  {line: 'L1', id: 'p03', src: 'shorts/short103/short103_03.png', kind: 'image', motion: 'pushin', fast: true},   // a brass latch and strike plate, the door held just ajar
  {line: 'L1', id: 'p04', src: 'shorts/short103/short103_04.png', kind: 'image', motion: 'parallax'},   // a corridor receding toward one lit doorway
  {line: 'L2', id: 'p05', src: 'shorts/short103/short103_05.png', kind: 'image', motion: 'kenburns'},   // an ambulance's open rear doors at a kerb, stretcher rails 
  {line: 'L2', id: 'p06', src: 'shorts/short103/short103_06.png', kind: 'image', motion: 'pushin'},   // an amber beacon revolving on a parked ambulance roof
  {line: 'L2', id: 'p07', src: 'shorts/short103/short103_07.png', kind: 'image', motion: 'parallax'},   // one high-backed chair pulled forward from eight in shadow
  {line: 'L2', id: 'p08', src: 'shorts/short103/short103_08.png', kind: 'image', motion: 'kenburns'},   // a hand pressing a pen to a blank sheet
  {line: 'L2', id: 'p09', src: 'shorts/short103/short103_09.png', kind: 'image', motion: 'pushin'},   // two hands gripping a chrome stretcher rail
  {line: 'L2', id: 'p11', src: 'shorts/short103/short103_11.png', kind: 'image', motion: 'kenburns'},   // a shaft of light crossing an empty living room, thick with
  {line: 'L3', id: 'p12', src: 'shorts/short103/short103_12.png', kind: 'image', motion: 'pushin'},   // the threshold from inside: a doormat and boots stopped out
  {line: 'L3', id: 'p13', src: 'shorts/short103/short103_13.png', kind: 'image', motion: 'parallax'},   // the United States with borders as glowing seams
  {line: 'L3', id: 'p14', src: 'shorts/short103/short103_14.png', kind: 'image', motion: 'kenburns'},   // a thick case file closed and tied with a band
  {line: 'L3', id: 'p15', src: 'shorts/short103/short103_15.png', kind: 'image', motion: 'pushin'},   // a wall clock with a blank featureless face
  {line: 'L3', id: 'p16', src: 'shorts/short103/short103_16.png', kind: 'image', motion: 'parallax'},   // a gavel caught mid-strike
  {line: 'L4', id: 'p17', src: 'shorts/short103/short103_17.png', kind: 'image', motion: 'kenburns'},   // a phone lying face down on a kitchen counter
  {line: 'L4', id: 'p18', src: 'shorts/short103/short103_18.png', kind: 'image', motion: 'pushin'},   // a cruiser's beacon at a residential kerb
  {line: 'L4', id: 'p19', src: 'shorts/short103/short103_19.png', kind: 'image', motion: 'parallax'},   // two handguns laid side by side on a bare dining table
  {line: 'L4', id: 'p20', src: 'shorts/short103/short103_20.png', kind: 'image', motion: 'kenburns'},   // two handguns sealed in an evidence bag on a steel counter
  {line: 'L4', id: 'p21', src: 'shorts/short103/short103_21.png', kind: 'image', motion: 'pushin'},   // an empty gun cabinet standing open, felt slots bare
  {line: 'L4', id: 'p22', src: 'shorts/short103/fx/fx_22.mp4', kind: 'video', motion: 'video'},   // a silhouette walking away into hard daylight
  {line: 'L8', id: 'p23', src: 'shorts/short103/short103_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short103/short103_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short103/short103_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the hook plate — identical framing to plate 01
  {line: 'L5', id: 'p26', src: 'shorts/short103/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // a fountain pen lying on a leather desk pad, the warrant ro
  {line: 'L5', id: 'p27', src: 'shorts/short103/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // a hand pushing a front door open from outside, consent giv
  {line: 'L5', id: 'p28', src: 'shorts/short103/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a fire engine pulling out of its station, a genuine emerge
  {line: 'L5', id: 'p29', src: 'shorts/short103/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // three wooden doors along a bright hallway, all still open
  {line: 'L5', id: 'p30', src: 'shorts/short103/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // two people shaking hands in a doorway
  {line: 'L6', id: 'p31', src: 'shorts/short103/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // wooden porch steps leading up to the house
  {line: 'L6', id: 'p32', src: 'shorts/short103/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // a fist knocking on a wooden door
  {line: 'L6', id: 'p33', src: 'shorts/short103/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // birds scattering off a rooftop at a sudden sound
  {line: 'L6', id: 'p34', src: 'shorts/short103/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // boots running across a gravel driveway
  {line: 'L6', id: 'p35', src: 'shorts/short103/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // an open door leading into a lit room, nothing keeping them
  {line: 'L7', id: 'p36', src: 'shorts/short103/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // a marble hall with tall interior columns, all nine agreein
  {line: 'L7', id: 'p37', src: 'shorts/short103/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // a wide stone staircase running back down to the lower cour
  {line: 'L7', id: 'p38', src: 'shorts/short103/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a cardboard box of folders carried away to be heard again
  {line: 'L7', id: 'p40', src: 'shorts/short103/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a wristwatch and a wallet in a plastic tray
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT103_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT103: ShortData = {
  shortId: 'short103',
  episodeId: 'PD-2026-043-caniglia',
  durationSec: SHORT103_TOTAL_SEC,
  narrationSrc: 'shorts/short103/audio/short103_final_mix_v002_en_us.mp3',
  captions: SHORT103_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short103/short103_ctathumb.jpg',
  ctaLongTitle: "Police Came for a Welfare Check and",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
