// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #130.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT130_TOTAL_SEC = 38.01;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 7.338
  },
  {
    "id": "L2",
    "start": 7.558,
    "end": 14.245
  },
  {
    "id": "L3",
    "start": 14.465,
    "end": 21.71
  },
  {
    "id": "L4",
    "start": 21.93,
    "end": 30.521
  },
  {
    "id": "L5",
    "start": 30.741,
    "end": 37.01
  }
];

export const SHORT130_CAPTIONS: ShortCaption[] = [
  {
    "word": "Police can swab your DNA at booking",
    "startSec": 0.0,
    "endSec": 1.931
  },
  {
    "word": "because the Supreme Court called it identification.",
    "startSec": 1.931,
    "endSec": 4.745
  },
  {
    "word": "That word does not mean",
    "startSec": 4.745,
    "endSec": 6.014
  },
  {
    "word": "what you think it means.",
    "startSec": 6.014,
    "endSec": 7.338
  },
  {
    "word": "Fingerprints are allowed at",
    "startSec": 7.558,
    "endSec": 8.958
  },
  {
    "word": "booking for one reason.",
    "startSec": 8.958,
    "endSec": 10.15
  },
  {
    "word": "Their purpose is confirming that the",
    "startSec": 10.15,
    "endSec": 12.016
  },
  {
    "word": "person in the cell is who",
    "startSec": 12.016,
    "endSec": 13.312
  },
  {
    "word": "they say they are.",
    "startSec": 13.312,
    "endSec": 14.245
  },
  {
    "word": "Justice Kennedy said identification meant",
    "startSec": 14.465,
    "endSec": 16.602
  },
  {
    "word": "more than a name.",
    "startSec": 16.602,
    "endSec": 17.488
  },
  {
    "word": "Knowing an arrestee's full history helps officers",
    "startSec": 17.488,
    "endSec": 20.042
  },
  {
    "word": "judge how dangerous he might be.",
    "startSec": 20.042,
    "endSec": 21.71
  },
  {
    "word": "Whether he is a flight risk.",
    "startSec": 21.93,
    "endSec": 23.624
  },
  {
    "word": "Whether he threatens the people around him.",
    "startSec": 23.624,
    "endSec": 26.226
  },
  {
    "word": "On that reading the swab",
    "startSec": 26.226,
    "endSec": 27.678
  },
  {
    "word": "was not a fishing expedition.",
    "startSec": 27.678,
    "endSec": 29.432
  },
  {
    "word": "It was processing.",
    "startSec": 29.432,
    "endSec": 30.521
  },
  {
    "word": "The four in dissent lost",
    "startSec": 30.741,
    "endSec": 32.147
  },
  {
    "word": "which means the definition in",
    "startSec": 32.147,
    "endSec": 33.846
  },
  {
    "word": "the majority opinion is the",
    "startSec": 33.846,
    "endSec": 35.428
  },
  {
    "word": "one police work from today.",
    "startSec": 35.428,
    "endSec": 37.01
  }
];
