import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT184_CAPTIONS, SHORT184_TOTAL_SEC} from './short184_timing';

/**
 * short184 — Every heavy thing done to Gail Atwater that afternoon happened before any finding of guilt, because the only sentence the law could ever impose on her was money.
 * Episode PD-2026-047-atwater.  Type A - a sequence of documented facts.
 *
 * AVOIDS: Short 49 ran the arrest through to the 5-4 holding; this cut stays inside the afternoon itself, on the prior stop, the children, the booking and the fifty dollar penalty that was the only punishment on offer.
 * LEAVES FOR THE LONG-FORM: If a cell was never available as her punishment, what did the Supreme Court say the police were still permitted to do to her?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-047-atwater.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short184/short184_01.png', kind: 'image', motion: 'parallax', fast: true},   // the cuffs closing at the roadside
  {line: 'L1', id: 'p02', src: 'shorts/short184/short184_02.png', kind: 'image', motion: 'kenburns', fast: true},   // the cab of the pickup, belts loose
  {line: 'L1', id: 'p03', src: 'shorts/short184/short184_03.png', kind: 'image', motion: 'pushin', fast: true},   // the patrol car that pulled in behind
  {line: 'L1', id: 'p04', src: 'shorts/short184/short184_04.png', kind: 'image', motion: 'parallax'},   // the cell door closing on an hour
  {line: 'L2', id: 'p05', src: 'shorts/short184/short184_05.png', kind: 'image', motion: 'kenburns'},   // the penalty the statute set
  {line: 'L2', id: 'p06', src: 'shorts/short184/short184_06.png', kind: 'image', motion: 'pushin'},   // fifty dollars
  {line: 'L2', id: 'p07', src: 'shorts/short184/short184_07.png', kind: 'image', motion: 'parallax'},   // what a seatbelt ticket became
  {line: 'L2', id: 'p08', src: 'shorts/short184/short184_08.png', kind: 'image', motion: 'kenburns'},   // the fine, stamped and paid
  {line: 'L2', id: 'p09', src: 'shorts/short184/short184_09.png', kind: 'image', motion: 'pushin'},   // the hour she sat there
  {line: 'L2', id: 'p10', src: 'shorts/short184/short184_10.png', kind: 'image', motion: 'parallax'},   // one state's traffic law
  {line: 'L2', id: 'p11', src: 'shorts/short184/short184_11.png', kind: 'image', motion: 'kenburns'},   // the courthouse where the fine was entered
  {line: 'L3', id: 'p12', src: 'shorts/short184/short184_12.png', kind: 'image', motion: 'pushin'},   // the road at first light
  {line: 'L3', id: 'p13', src: 'shorts/short184/short184_13.png', kind: 'image', motion: 'parallax'},   // dust on the shoulder after they left
  {line: 'L3', id: 'p14', src: 'shorts/short184/short184_14.png', kind: 'image', motion: 'kenburns'},   // the ticket book he did not reach for
  {line: 'L3', id: 'p15', src: 'shorts/short184/short184_15.png', kind: 'image', motion: 'pushin'},   // the corridor at the station
  {line: 'L3', id: 'p16', src: 'shorts/short184/short184_16.png', kind: 'image', motion: 'parallax'},   // hands flat on the booking counter
  {line: 'L4', id: 'p17', src: 'shorts/short184/short184_17.png', kind: 'image', motion: 'kenburns'},   // everything she was carrying
  {line: 'L4', id: 'p18', src: 'shorts/short184/short184_18.png', kind: 'image', motion: 'pushin'},   // one chair in a municipal room
  {line: 'L4', id: 'p19', src: 'shorts/short184/short184_19.png', kind: 'image', motion: 'parallax'},   // the holding cell itself
  {line: 'L4', id: 'p20', src: 'shorts/short184/short184_20.png', kind: 'image', motion: 'kenburns'},   // the corridor of identical doors
  {line: 'L4', id: 'p21', src: 'shorts/short184/short184_21.png', kind: 'image', motion: 'pushin'},   // the bond that let her out
  {line: 'L4', id: 'p22', src: 'shorts/short184/short184_22.png', kind: 'image', motion: 'parallax'},   // the seat the children were lifted out of
  {line: 'L8', id: 'p23', src: 'shorts/short184/short184_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short184/short184_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short184/short184_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the hook - replay of the opening framing (3)
  {line: 'L5', id: 'p26', src: 'shorts/short184/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // a door opened by a neighbour
  {line: 'L5', id: 'p27', src: 'shorts/short184/short184_27.png', kind: 'image', motion: 'pushin'},   // the children taken indoors
  {line: 'L5', id: 'p28', src: 'shorts/short184/short184_28.png', kind: 'image', motion: 'parallax'},   // the truck left where it stopped
  {line: 'L5', id: 'p29', src: 'shorts/short184/short184_29.png', kind: 'image', motion: 'kenburns'},   // the house they were taken to
  {line: 'L5', id: 'p30', src: 'shorts/short184/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // the door closing on the car
  {line: 'L6', id: 'p31', src: 'shorts/short184/short184_31.png', kind: 'image', motion: 'parallax'},   // the shoes she was made to hand over
  {line: 'L6', id: 'p32', src: 'shorts/short184/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // an hour in a bare room
  {line: 'L6', id: 'p33', src: 'shorts/short184/short184_33.png', kind: 'image', motion: 'pushin'},   // pockets emptied at the counter
  {line: 'L6', id: 'p34', src: 'shorts/short184/short184_34.png', kind: 'image', motion: 'parallax'},   // the photograph taken of her
  {line: 'L6', id: 'p35', src: 'shorts/short184/short184_35.png', kind: 'image', motion: 'kenburns'},   // the hour, measured
  {line: 'L7', id: 'p36', src: 'shorts/short184/short184_36.png', kind: 'image', motion: 'pushin'},   // fifty dollars, counted out
  {line: 'L7', id: 'p37', src: 'shorts/short184/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // the plea entered later
  {line: 'L7', id: 'p38', src: 'shorts/short184/short184_38.png', kind: 'image', motion: 'kenburns'},   // the belt that started it
  {line: 'L7', id: 'p39', src: 'shorts/short184/short184_39.png', kind: 'image', motion: 'pushin'},   // the road she was driving
  {line: 'L7', id: 'p40', src: 'shorts/short184/short184_40.png', kind: 'image', motion: 'parallax'},   // the town it happened in
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT184_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT184: ShortData = {
  shortId: 'short184',
  episodeId: 'PD-2026-047-atwater',
  durationSec: SHORT184_TOTAL_SEC,
  narrationSrc: 'shorts/short184/audio/short184_final_mix_v002_en_us.mp3',
  captions: SHORT184_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short184/short184_ctathumb.jpg',
  ctaLongTitle: "She Was Handcuffed and Jailed Over a",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short184.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short184/short184_kin_a.webm', atSec: 36.35, durSec: 2.3, phrase: "AN HOUR IN A CELL"},
    {src: 'shorts/short184/short184_kin_b.webm', atSec: 40.66, durSec: 2.3, phrase: "A $50 FINE ARRESTED ANYWAY"},
  ],
};
