// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #106.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT106_TOTAL_SEC = 33.738;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.455
  },
  {
    "id": "L2",
    "start": 6.675,
    "end": 11.876
  },
  {
    "id": "L3",
    "start": 12.096,
    "end": 20.177
  },
  {
    "id": "L4",
    "start": 20.397,
    "end": 26.156
  },
  {
    "id": "L5",
    "start": 26.376,
    "end": 32.738
  }
];

export const SHORT106_CAPTIONS: ShortCaption[] = [
  {
    "word": "In 1997",
    "startSec": 0.0,
    "endSec": 0.7
  },
  {
    "word": "in a small church office",
    "startSec": 0.7,
    "endSec": 2.134
  },
  {
    "word": "Jennifer Thompson finally sat down across from",
    "startSec": 2.134,
    "endSec": 4.884
  },
  {
    "word": "the man she had sent to prison.",
    "startSec": 4.884,
    "endSec": 6.455
  },
  {
    "word": "She had identified Ronald Cotton twice",
    "startSec": 6.675,
    "endSec": 8.713
  },
  {
    "word": "and she had never been more",
    "startSec": 8.713,
    "endSec": 10.16
  },
  {
    "word": "certain of anything in her life.",
    "startSec": 10.16,
    "endSec": 11.876
  },
  {
    "word": "DNA cleared him in 1995.",
    "startSec": 12.096,
    "endSec": 13.648
  },
  {
    "word": "On the thirtieth of June",
    "startSec": 13.648,
    "endSec": 15.199
  },
  {
    "word": "that year he walked out",
    "startSec": 15.199,
    "endSec": 16.686
  },
  {
    "word": "after more than a decade for",
    "startSec": 16.686,
    "endSec": 18.496
  },
  {
    "word": "a crime he did not commit.",
    "startSec": 18.496,
    "endSec": 20.177
  },
  {
    "word": "She told him that even",
    "startSec": 20.397,
    "endSec": 21.639
  },
  {
    "word": "if she spent every remaining",
    "startSec": 21.639,
    "endSec": 23.22
  },
  {
    "word": "day of her life apologising",
    "startSec": 23.22,
    "endSec": 24.744
  },
  {
    "word": "it would never be enough.",
    "startSec": 24.744,
    "endSec": 26.156
  },
  {
    "word": "There is a room somewhere",
    "startSec": 26.376,
    "endSec": 27.809
  },
  {
    "word": "where the person who was wrong",
    "startSec": 27.809,
    "endSec": 29.528
  },
  {
    "word": "and the person who paid for",
    "startSec": 29.528,
    "endSec": 31.076
  },
  {
    "word": "it finally sit down together.",
    "startSec": 31.076,
    "endSec": 32.738
  }
];
