import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT315_CAPTIONS, SHORT315_TOTAL_SEC} from './short315_timing';

/**
 * short315 — Four certificate disapprovals sat in a federal filing cabinet the airline could not open, one incomplete line sat on its own employment form, and a fifth event happened in its own aeroplane with its own examiner. Three years later it upgraded him to captain.
 * Episode PD-2026-078-colgan.  Type ?.
 *
 * AVOIDS: Does not say the captain lied - the script's own words, true but not complete, are spoken, and the failure rate of one applicant in eight is given so the record is not read as a mark of a dangerous man. No fatigue, no pay, no state of mind, no deaths.
 * LEAVES FOR THE LONG-FORM: The same company had a written rule about sleeping in the crew room. What happened to that one?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-078-colgan.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short315/short315_01.png', kind: 'image', motion: 'parallax', fast: true},   // a wall of steel filing cabinets in a government records ro
  {line: 'L1', id: 'p02', src: 'shorts/short315/short315_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a turboprop flight deck seen from the jump seat in dayligh
  {line: 'L2', id: 'p03', src: 'shorts/short315/short315_03.png', kind: 'image', motion: 'pushin', fast: true},   // close-up of hanging file folders packed tight in an open d
  {line: 'L2', id: 'p04', src: 'shorts/short315/short315_04.png', kind: 'image', motion: 'parallax'},   // a single manila folder lying closed on a desk under a gree
  {line: 'L3', id: 'p05', src: 'shorts/short315/short315_05.png', kind: 'image', motion: 'kenburns'},   // a pilot's logbook lying open on a table in daylight
  {line: 'L3', id: 'p06', src: 'shorts/short315/short315_06.png', kind: 'image', motion: 'pushin'},   // a light aircraft parked on a grass airfield in afternoon l
  {line: 'L4', id: 'p07', src: 'shorts/short315/short315_07.png', kind: 'image', motion: 'parallax'},   // a flight training school ramp in bright daylight
  {line: 'L5', id: 'p08', src: 'shorts/short315/short315_08.png', kind: 'image', motion: 'kenburns'},   // an airline employment office in daylight, a counter
  {line: 'L5', id: 'p09', src: 'shorts/short315/short315_09.png', kind: 'image', motion: 'pushin'},   // extreme close-up of a printed form with empty tick boxes
  {line: 'L6', id: 'p10', src: 'shorts/short315/short315_10.png', kind: 'image', motion: 'parallax'},   // a pen lying across a blank sheet of paper on a desk
  {line: 'L7', id: 'p11', src: 'shorts/short315/short315_11.png', kind: 'image', motion: 'kenburns'},   // a long fluorescent-lit government archive corridor
  {line: 'L7', id: 'p12', src: 'shorts/short315/short315_12.png', kind: 'image', motion: 'pushin'},   // a steel in-tray holding a stack of blank sheets
  {line: 'L8', id: 'p13', src: 'shorts/short315/short315_13.png', kind: 'image', motion: 'parallax'},   // a public hearing room in bright daylight, a raised bench
  {line: 'L8', id: 'p14', src: 'shorts/short315/short315_14.png', kind: 'image', motion: 'kenburns', isCta: true, rewind: true, fast: true},   // a single microphone on a witness table in a hearing room
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT315_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT315: ShortData = {
  shortId: 'short315',
  episodeId: 'PD-2026-078-colgan',
  durationSec: SHORT315_TOTAL_SEC,
  narrationSrc: 'shorts/short315/audio/short315_final_mix_v002_en_us.mp3',
  captions: SHORT315_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short315/short315_ctathumb.jpg',
  ctaLongTitle: "The Warning Fired With Wings Level.",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short315.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short315/short315_kin_complete.webm', atSec: 35.65, durSec: 2.2, phrase: "TRUE. COMPLETE?"},
    {src: 'shorts/short315/short315_kin_did_not_talk.webm', atSec: 45.99, durSec: 2.4, phrase: "THE SYSTEMS DID NOT TALK"},
  ],
};
