// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #53.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT53_TOTAL_SEC = 59.468;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 4.969
  },
  {
    "id": "L2",
    "start": 5.689,
    "end": 19.389
  },
  {
    "id": "L3",
    "start": 20.109,
    "end": 29.211
  },
  {
    "id": "L4",
    "start": 29.931,
    "end": 41.169
  },
  {
    "id": "L5",
    "start": 41.889,
    "end": 58.468
  }
];

export const SHORT53_CAPTIONS: ShortCaption[] = [
  {
    "word": "His wife asked the police to check",
    "startSec": 0.0,
    "endSec": 1.797
  },
  {
    "word": "if he was still alive.",
    "startSec": 1.797,
    "endSec": 2.96
  },
  {
    "word": "They left his house carrying his guns.",
    "startSec": 2.96,
    "endSec": 4.969
  },
  {
    "word": "Cranston Rhode Island. 2015.",
    "startSec": 5.689,
    "endSec": 7.636
  },
  {
    "word": "After an awful night",
    "startSec": 7.636,
    "endSec": 9.027
  },
  {
    "word": "a handgun set on the dining table",
    "startSec": 9.027,
    "endSec": 11.322
  },
  {
    "word": "his wife sleeps at a hotel.",
    "startSec": 11.322,
    "endSec": 13.2
  },
  {
    "word": "By morning she can't reach him.",
    "startSec": 13.2,
    "endSec": 15.355
  },
  {
    "word": "She calls the non-emergency line:",
    "startSec": 15.355,
    "endSec": 17.65
  },
  {
    "word": "just make sure he's okay.",
    "startSec": 17.65,
    "endSec": 19.389
  },
  {
    "word": "Officers find him alive. Calm.",
    "startSec": 20.109,
    "endSec": 22.209
  },
  {
    "word": "On his own porch.",
    "startSec": 22.209,
    "endSec": 23.4
  },
  {
    "word": "He agrees to a psychiatric evaluation on one condition he says:",
    "startSec": 23.4,
    "endSec": 27.811
  },
  {
    "word": "leave my guns alone.",
    "startSec": 27.811,
    "endSec": 29.211
  },
  {
    "word": "The moment the ambulance leaves",
    "startSec": 29.931,
    "endSec": 31.814
  },
  {
    "word": "they walk into his home no warrant no emergency",
    "startSec": 31.814,
    "endSec": 34.669
  },
  {
    "word": "and carry out two handguns.",
    "startSec": 34.669,
    "endSec": 36.309
  },
  {
    "word": "They called it caretaking. For years",
    "startSec": 36.309,
    "endSec": 38.496
  },
  {
    "word": "in much of the country",
    "startSec": 38.496,
    "endSec": 39.833
  },
  {
    "word": "that was simply legal.",
    "startSec": 39.833,
    "endSec": 41.169
  },
  {
    "word": "So he carried one question to the Supreme Court:",
    "startSec": 41.889,
    "endSec": 45.191
  },
  {
    "word": "can police enter your home just to",
    "startSec": 45.191,
    "endSec": 47.53
  },
  {
    "word": "look after you?",
    "startSec": 47.53,
    "endSec": 48.562
  },
  {
    "word": "Nine to zero",
    "startSec": 48.562,
    "endSec": 49.387
  },
  {
    "word": "the answer came back: no.",
    "startSec": 49.387,
    "endSec": 51.107
  },
  {
    "word": "Caretaking does not open your front door.",
    "startSec": 51.107,
    "endSec": 53.928
  },
  {
    "word": "Follow for the cases they don't teach you",
    "startSec": 53.928,
    "endSec": 56.748
  },
  {
    "word": "full film on the channel.",
    "startSec": 56.748,
    "endSec": 58.468
  }
];
