import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT151_CAPTIONS, SHORT151_TOTAL_SEC} from './short151_timing';

/**
 * short151 — Winning at the Supreme Court did not set him free. It sent him back to the same courtroom to be tried all over again.
 * Episode PD-2026-002-gideon.  Type A - same man, same charge, opposite verdict.
 *
 * AVOIDS: short02 stops at the 1963 ruling and the public defender system. It never says Gideon was retried, or that with a lawyer in the chair the same jury question came back the other way.
 * LEAVES FOR THE LONG-FORM: The Court could create the right with a stroke of a pen. Who was ever going to pay for it?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-002-gideon.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short151/short151_01.png', kind: 'image', motion: 'parallax', fast: true},   // a gate opening onto another corridor, not daylight
  {line: 'L1', id: 'p02', src: 'shorts/short151/short151_02.png', kind: 'image', motion: 'kenburns', fast: true},   // his effects pushed back across the counter
  {line: 'L1', id: 'p03', src: 'shorts/short151/short151_03.png', kind: 'image', motion: 'pushin', fast: true},   // handcuffs, macro
  {line: 'L1', id: 'p04', src: 'shorts/short151/short151_04.png', kind: 'image', motion: 'parallax'},   // the corridor back to the same courtroom
  {line: 'L2', id: 'p05', src: 'shorts/short151/short151_05.png', kind: 'image', motion: 'kenburns'},   // the same file, opened again
  {line: 'L2', id: 'p06', src: 'shorts/short151/short151_06.png', kind: 'image', motion: 'pushin'},   // the same empty chair at the defence table
  {line: 'L2', id: 'p07', src: 'shorts/short151/short151_07.png', kind: 'image', motion: 'parallax'},   // the chair filled: a jacket over its back, a case beside it
  {line: 'L2', id: 'p08', src: 'shorts/short151/fx/fx_08.mp4', kind: 'video', motion: 'video'},   // a plain wooden chair, still
  {line: 'L2', id: 'p09', src: 'shorts/short151/short151_09.png', kind: 'image', motion: 'pushin'},   // the gallery of the same small courtroom
  {line: 'L2', id: 'p10', src: 'shorts/short151/short151_10.png', kind: 'image', motion: 'parallax'},   // a lawyer's window at first light
  {line: 'L2', id: 'p11', src: 'shorts/short151/fx/fx_11.mp4', kind: 'video', motion: 'video'},   // a metal filing cabinet
  {line: 'L3', id: 'p12', src: 'shorts/short151/short151_12.png', kind: 'image', motion: 'pushin'},   // a lawyer's hands, flat and ready
  {line: 'L3', id: 'p13', src: 'shorts/short151/short151_13.png', kind: 'image', motion: 'parallax'},   // the witness box, empty and waiting
  {line: 'L3', id: 'p14', src: 'shorts/short151/short151_14.png', kind: 'image', motion: 'kenburns'},   // a sealed evidence envelope, writing worn away
  {line: 'L3', id: 'p15', src: 'shorts/short151/fx/fx_15.mp4', kind: 'video', motion: 'video'},   // a stack of documents beside a lamp
  {line: 'L3', id: 'p16', src: 'shorts/short151/short151_16.png', kind: 'image', motion: 'parallax'},   // dust in the well of the court
  {line: 'L4', id: 'p17', src: 'shorts/short151/fx/fx_17.mp4', kind: 'video', motion: 'video'},   // a prison corridor receding
  {line: 'L4', id: 'p18', src: 'shorts/short151/short151_18.png', kind: 'image', motion: 'pushin'},   // the bars, from the first trial
  {line: 'L4', id: 'p19', src: 'shorts/short151/short151_19.png', kind: 'image', motion: 'parallax'},   // the jury box, twelve empty seats
  {line: 'L4', id: 'p20', src: 'shorts/short151/short151_20.png', kind: 'image', motion: 'kenburns'},   // the gavel, mid-strike
  {line: 'L4', id: 'p21', src: 'shorts/short151/short151_21.png', kind: 'image', motion: 'pushin'},   // the gate open onto daylight this time
  {line: 'L4', id: 'p22', src: 'shorts/short151/short151_22.png', kind: 'image', motion: 'parallax'},   // a man walking out into the light
  {line: 'L8', id: 'p23', src: 'shorts/short151/short151_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short151/short151_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short151/short151_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the hook plate: a gate opening onto another corr
  {line: 'L5', id: 'p26', src: 'shorts/short151/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // the Court that answered with one voice
  {line: 'L5', id: 'p27', src: 'shorts/short151/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // nine copies of one opinion, closed
  {line: 'L5', id: 'p28', src: 'shorts/short151/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // the long bench where every one of them agreed
  {line: 'L5', id: 'p29', src: 'shorts/short151/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // the signing of the judgment
  {line: 'L5', id: 'p30', src: 'shorts/short151/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // one plain rule, stamped
  {line: 'L6', id: 'p31', src: 'shorts/short151/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // the page the old rule left blank
  {line: 'L6', id: 'p32', src: 'shorts/short151/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // the shelves the overruled case went back to
  {line: 'L6', id: 'p33', src: 'shorts/short151/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // too poor to hire one
  {line: 'L6', id: 'p34', src: 'shorts/short151/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // the door the new rule left standing open
  {line: 'L6', id: 'p35', src: 'shorts/short151/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // the appointments the clerk now had to make
  {line: 'L7', id: 'p36', src: 'shorts/short151/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // the states the rule now reached
  {line: 'L7', id: 'p37', src: 'shorts/short151/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // courthouse doors, open in every state
  {line: 'L7', id: 'p38', src: 'shorts/short151/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // the small towns it reached too
  {line: 'L7', id: 'p39', src: 'shorts/short151/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // a bare cell in any state at all
  {line: 'L7', id: 'p40', src: 'shorts/short151/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // one man standing where the light reaches
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT151_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT151: ShortData = {
  shortId: 'short151',
  episodeId: 'PD-2026-002-gideon',
  durationSec: SHORT151_TOTAL_SEC,
  narrationSrc: 'shorts/short151/audio/short151_final_mix_v002_en_us.mp3',
  captions: SHORT151_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short151/short151_ctathumb.jpg',
  ctaLongTitle: "He Had No Lawyer. So He Wrote the",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short151.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short151/short151_kin_a.webm', atSec: 24.56, durSec: 2.3, phrase: "ALONE: GUILTY WITH A LAWYER: FREE"},
    {src: 'shorts/short151/short151_kin_b.webm', atSec: 32.76, durSec: 2.3, phrase: "A NECESSITY NOT A FRILL"},
  ],
};
