import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT175_CAPTIONS, SHORT175_TOTAL_SEC} from './short175_timing';

/**
 * short175 — Officers may speak a lie about the evidence, and one Florida court held they may not print that lie on a letterhead.
 * Episode PD-2026-039-frazier.  Type C — a quotation or document.
 *
 * AVOIDS: Short 41 established that a spoken lie about fingerprints is lawful; this cut finds the one place a court drew a line and would not move it.
 * LEAVES FOR THE LONG-FORM: What a spoken lie about a fingerprint took from a man with the comprehension of a ten-year-old.
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-039-frazier.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short175/short175_01.png', kind: 'image', motion: 'parallax', fast: true},   // a sheet of headed paper with the letterhead blank
  {line: 'L1', id: 'p02', src: 'shorts/short175/fx/fx_02.mp4', kind: 'video', motion: 'video', fast: true},   // the machine the lie was typed on
  {line: 'L1', id: 'p03', src: 'shorts/short175/short175_03.png', kind: 'image', motion: 'pushin', fast: true},   // the room where they showed it to him
  {line: 'L1', id: 'p04', src: 'shorts/short175/short175_04.png', kind: 'image', motion: 'parallax'},   // a manila folder closed on the table
  {line: 'L2', id: 'p05', src: 'shorts/short175/short175_05.png', kind: 'image', motion: 'kenburns'},   // a blank sheet on the copier glass
  {line: 'L2', id: 'p06', src: 'shorts/short175/fx/fx_06.mp4', kind: 'video', motion: 'video'},   // the copier running off the reports
  {line: 'L2', id: 'p07', src: 'shorts/short175/short175_07.png', kind: 'image', motion: 'parallax'},   // two reports, two different crests, both blank
  {line: 'L2', id: 'p08', src: 'shorts/short175/short175_08.png', kind: 'image', motion: 'kenburns'},   // the crest press and the stamp beside it
  {line: 'L2', id: 'p09', src: 'shorts/short175/fx/fx_09.mp4', kind: 'video', motion: 'video'},   // paper coming off the machine
  {line: 'L2', id: 'p10', src: 'shorts/short175/short175_10.png', kind: 'image', motion: 'parallax'},   // the laboratory the report pretended to come from
  {line: 'L2', id: 'p11', src: 'shorts/short175/short175_11.png', kind: 'image', motion: 'kenburns'},   // the sheet slid across to a suspect's hands
  {line: 'L3', id: 'p12', src: 'shorts/short175/short175_12.png', kind: 'image', motion: 'pushin'},   // the courtroom that suppressed it
  {line: 'L3', id: 'p13', src: 'shorts/short175/short175_13.png', kind: 'image', motion: 'parallax'},   // dust in the room where it was argued
  {line: 'L3', id: 'p14', src: 'shorts/short175/short175_14.png', kind: 'image', motion: 'kenburns'},   // the document held up to the light
  {line: 'L3', id: 'p15', src: 'shorts/short175/short175_15.png', kind: 'image', motion: 'pushin'},   // the sealed envelope the real evidence lived in
  {line: 'L3', id: 'p16', src: 'shorts/short175/fx/fx_16.mp4', kind: 'video', motion: 'video'},   // the forgery in the bin
  {line: 'L4', id: 'p17', src: 'shorts/short175/fx/fx_17.mp4', kind: 'video', motion: 'video'},   // the words they were still allowed to say
  {line: 'L4', id: 'p18', src: 'shorts/short175/short175_18.png', kind: 'image', motion: 'pushin'},   // the tape running on the spoken lie
  {line: 'L4', id: 'p19', src: 'shorts/short175/short175_19.png', kind: 'image', motion: 'parallax'},   // the blank page feeding out of the platen
  {line: 'L4', id: 'p20', src: 'shorts/short175/short175_20.png', kind: 'image', motion: 'kenburns'},   // the report torn in two on the floor
  {line: 'L4', id: 'p21', src: 'shorts/short175/fx/fx_21.mp4', kind: 'video', motion: 'video'},   // the drawer the fakes were filed in
  {line: 'L4', id: 'p22', src: 'shorts/short175/short175_22.png', kind: 'image', motion: 'parallax'},   // the agency door the lie borrowed
  {line: 'L8', id: 'p23', src: 'shorts/short175/short175_04.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short175/short175_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short175/short175_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the blank letterhead
  {line: 'L5', id: 'p26', src: 'shorts/short175/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // the file the fake report went into
  {line: 'L5', id: 'p27', src: 'shorts/short175/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // the light over the table where he read it
  {line: 'L5', id: 'p28', src: 'shorts/short175/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // the report itself, blank to us
  {line: 'L5', id: 'p30', src: 'shorts/short175/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // the desk where the document was made
  {line: 'L6', id: 'p31', src: 'shorts/short175/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // the review that counted the cases
  {line: 'L6', id: 'p32', src: 'shorts/short175/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // where an innocent confession ends
  {line: 'L6', id: 'p34', src: 'shorts/short175/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // the officers the study was about
  {line: 'L6', id: 'p35', src: 'shorts/short175/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // the room the false evidence was shown in
  {line: 'L7', id: 'p37', src: 'shorts/short175/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // the conviction unlocked
  {line: 'L7', id: 'p38', src: 'shorts/short175/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // the doors that opened afterwards
  {line: 'L7', id: 'p39', src: 'shorts/short175/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // the record left with nothing in it
  {line: 'L7', id: 'p40', src: 'shorts/short175/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // the way out, finally
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT175_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT175: ShortData = {
  shortId: 'short175',
  episodeId: 'PD-2026-039-frazier',
  durationSec: SHORT175_TOTAL_SEC,
  narrationSrc: 'shorts/short175/audio/short175_final_mix_v002_en_us.mp3',
  captions: SHORT175_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short175/short175_ctathumb.jpg',
  ctaLongTitle: "Police Are Allowed to Lie to You Until",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short175.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short175/short175_kin_a.webm', atSec: 31.67, durSec: 2.3, phrase: "THEY MAY SAY IT NOT PRINT IT"},
    {src: 'shorts/short175/short175_kin_b.webm', atSec: 35.71, durSec: 2.3, phrase: "A DOCUMENT THAT WAS FALSE"},
  ],
};
