// AUTO-GENERATED by scripts/build_short07_mix.py — narration-driven timing for SHORT #7.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT07_TOTAL_SEC = 35.065;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 3.158
  },
  {
    "id": "L2",
    "start": 5.858,
    "end": 10.641
  },
  {
    "id": "L3",
    "start": 13.341,
    "end": 20.446
  },
  {
    "id": "L4",
    "start": 23.146,
    "end": 28.254
  },
  {
    "id": "L5",
    "start": 30.954,
    "end": 34.065
  }
];

export const SHORT07_CAPTIONS: ShortCaption[] = [
  {
    "word": "Even after an arrest, police cannot just open your phone.",
    "startSec": 0.0,
    "endSec": 3.158
  },
  {
    "word": "For two centuries, officers could search the things you had on you when you were arrested.",
    "startSec": 5.858,
    "endSec": 10.641
  },
  {
    "word": "But a phone is different.",
    "startSec": 13.341,
    "endSec": 15.033
  },
  {
    "word": "It can hold your messages, photos, location history, and almost your whole life.",
    "startSec": 15.033,
    "endSec": 20.446
  },
  {
    "word": "In 2014, the Supreme Court was unanimous.",
    "startSec": 23.146,
    "endSec": 25.902
  },
  {
    "word": "Phones are different.",
    "startSec": 25.902,
    "endSec": 27.313
  },
  {
    "word": "Get a warrant.",
    "startSec": 27.313,
    "endSec": 28.254
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 30.954,
    "endSec": 33.108
  },
  {
    "word": "Follow for more.",
    "startSec": 33.108,
    "endSec": 34.065
  }
];
