// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #135.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT135_TOTAL_SEC = 59.429;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.269
  },
  {
    "id": "L2",
    "start": 6.489,
    "end": 15.684
  },
  {
    "id": "L3",
    "start": 15.904,
    "end": 25.053
  },
  {
    "id": "L4",
    "start": 25.273,
    "end": 33.725
  },
  {
    "id": "L5",
    "start": 33.945,
    "end": 39.982
  },
  {
    "id": "L6",
    "start": 40.202,
    "end": 46.286
  },
  {
    "id": "L7",
    "start": 46.506,
    "end": 52.311
  },
  {
    "id": "L8",
    "start": 52.531,
    "end": 58.429
  }
];

export const SHORT135_CAPTIONS: ShortCaption[] = [
  {
    "word": "The test that decides whether",
    "startSec": 0.0,
    "endSec": 1.668
  },
  {
    "word": "police need a warrant to",
    "startSec": 1.668,
    "endSec": 3.048
  },
  {
    "word": "track you is not fixed. It moves.",
    "startSec": 3.048,
    "endSec": 4.946
  },
  {
    "word": "And it has been moving.",
    "startSec": 4.946,
    "endSec": 6.269
  },
  {
    "word": "Harlan's phrase",
    "startSec": 6.489,
    "endSec": 7.496
  },
  {
    "word": "a reasonable expectation of privacy",
    "startSec": 7.496,
    "endSec": 9.845
  },
  {
    "word": "was only one justice's gloss in 1967.",
    "startSec": 9.845,
    "endSec": 12.328
  },
  {
    "word": "Courts reached for it until",
    "startSec": 12.328,
    "endSec": 14.14
  },
  {
    "word": "it became the standard.",
    "startSec": 14.14,
    "endSec": 15.684
  },
  {
    "word": "When judges today ask whether police need",
    "startSec": 15.904,
    "endSec": 18.583
  },
  {
    "word": "a warrant to track your phone",
    "startSec": 18.583,
    "endSec": 20.479
  },
  {
    "word": "read your messages",
    "startSec": 20.479,
    "endSec": 21.655
  },
  {
    "word": "or follow your car",
    "startSec": 21.655,
    "endSec": 22.831
  },
  {
    "word": "they are asking Harlan's question.",
    "startSec": 22.831,
    "endSec": 25.053
  },
  {
    "word": "But reasonable is a moving target.",
    "startSec": 25.273,
    "endSec": 27.371
  },
  {
    "word": "The more ordinary it",
    "startSec": 27.371,
    "endSec": 28.604
  },
  {
    "word": "becomes to be watched",
    "startSec": 28.604,
    "endSec": 29.9
  },
  {
    "word": "the weaker anyone's claim that",
    "startSec": 29.9,
    "endSec": 31.751
  },
  {
    "word": "a given expectation still holds.",
    "startSec": 31.751,
    "endSec": 33.725
  },
  {
    "word": "Harlan's test has two parts.",
    "startSec": 33.945,
    "endSec": 35.135
  },
  {
    "word": "A person must genuinely expect privacy",
    "startSec": 35.135,
    "endSec": 36.751
  },
  {
    "word": "and that expectation must be one society",
    "startSec": 36.751,
    "endSec": 38.451
  },
  {
    "word": "is prepared to accept as reasonable.",
    "startSec": 38.451,
    "endSec": 39.982
  },
  {
    "word": "The Court also drew a limit:",
    "startSec": 40.202,
    "endSec": 41.889
  },
  {
    "word": "what a person knowingly",
    "startSec": 41.889,
    "endSec": 43.274
  },
  {
    "word": "exposes to the public",
    "startSec": 43.274,
    "endSec": 44.539
  },
  {
    "word": "even at home",
    "startSec": 44.539,
    "endSec": 45.262
  },
  {
    "word": "is not protected.",
    "startSec": 45.262,
    "endSec": 46.286
  },
  {
    "word": "Katz freed privacy from the walls",
    "startSec": 46.506,
    "endSec": 48.611
  },
  {
    "word": "and tied it instead to what",
    "startSec": 48.611,
    "endSec": 50.333
  },
  {
    "word": "we are still willing to expect.",
    "startSec": 50.333,
    "endSec": 52.311
  },
  {
    "word": "So the privacy you have tomorrow",
    "startSec": 52.531,
    "endSec": 54.328
  },
  {
    "word": "depends on how much watching we",
    "startSec": 54.328,
    "endSec": 56.07
  },
  {
    "word": "get used to today.",
    "startSec": 56.07,
    "endSec": 57.081
  },
  {
    "word": "Which way is that going?",
    "startSec": 57.081,
    "endSec": 58.429
  }
];
