// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #25.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT25_TOTAL_SEC = 59.81;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.341
  },
  {
    "id": "L2",
    "start": 6.541,
    "end": 18.662
  },
  {
    "id": "L3",
    "start": 19.862,
    "end": 34.909
  },
  {
    "id": "L4",
    "start": 36.109,
    "end": 54.499
  },
  {
    "id": "L5",
    "start": 55.699,
    "end": 58.81
  }
];

export const SHORT25_CAPTIONS: ShortCaption[] = [
  {
    "word": "He never knocked.",
    "startSec": 0.0,
    "endSec": 0.926
  },
  {
    "word": "He never crossed the lawn.",
    "startSec": 0.926,
    "endSec": 2.344
  },
  {
    "word": "The Supreme Court still called it a search of the home.",
    "startSec": 2.344,
    "endSec": 5.341
  },
  {
    "word": "On a freezing night in January 1992, a federal agent sat in a car on a public street in Florence, Oregon.",
    "startSec": 6.541,
    "endSec": 12.81
  },
  {
    "word": "He pointed a thermal-imaging device at Danny Kyllo's home and read the heat leaking off the walls.",
    "startSec": 12.81,
    "endSec": 18.662
  },
  {
    "word": "The garage roof and one wall glowed hot — to the agent, the sign of grow lamps.",
    "startSec": 19.862,
    "endSec": 24.714
  },
  {
    "word": "That helped win a warrant, and inside were over a hundred marijuana plants.",
    "startSec": 24.714,
    "endSec": 29.32
  },
  {
    "word": "But the device never saw through the wall.",
    "startSec": 29.32,
    "endSec": 31.9
  },
  {
    "word": "It only read heat already drifting into open air.",
    "startSec": 31.9,
    "endSec": 34.909
  },
  {
    "word": "On June 11, 2001, the Court split five to four.",
    "startSec": 36.109,
    "endSec": 38.924
  },
  {
    "word": "Justice Scalia wrote that using a device not in general public use to learn what's inside a home is a search that needs a warrant.",
    "startSec": 38.924,
    "endSec": 46.712
  },
  {
    "word": "The dissent called it just reading heat off the outside.",
    "startSec": 46.712,
    "endSec": 50.066
  },
  {
    "word": "But the majority drew a line at the front door it called firm, and bright.",
    "startSec": 50.066,
    "endSec": 54.499
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 55.699,
    "endSec": 57.853
  },
  {
    "word": "Follow for more.",
    "startSec": 57.853,
    "endSec": 58.81
  }
];
