import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT192_CAPTIONS, SHORT192_TOTAL_SEC} from './short192_timing';

/**
 * short192 — Her lawyers stopped arguing about a Minnesota statute and argued eight hundred years of law instead — Magna Carta's residue clause, a 1692 English statute, and the Court's own 1884 and 1980 decisions.
 * Episode PD-2026-033-tyler.  Type ?.
 *
 * AVOIDS: Short 33 told the seizure, the sale and the 9-0 ruling; this cut is the legal history underneath it, which that Short never mentioned.
 * LEAVES FOR THE LONG-FORM: What nine justices did when a county's modern statute was set against a rule that old.
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-033-tyler.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short192/short192_01.png', kind: 'image', motion: 'parallax', fast: true},   // the modern file closed, the old law opened
  {line: 'L1', id: 'p02', src: 'shorts/short192/short192_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a hand over a blank sheet of parchment
  {line: 'L1', id: 'p03', src: 'shorts/short192/short192_03.png', kind: 'image', motion: 'pushin', fast: true},   // stone columns of an old hall
  {line: 'L1', id: 'p04', src: 'shorts/short192/short192_04.png', kind: 'image', motion: 'parallax'},   // one flame burning into camera
  {line: 'L2', id: 'p05', src: 'shorts/short192/short192_05.png', kind: 'image', motion: 'kenburns'},   // the chest emptied down to the debt
  {line: 'L2', id: 'p06', src: 'shorts/short192/short192_06.png', kind: 'image', motion: 'pushin'},   // coin counted out on a plank table
  {line: 'L2', id: 'p07', src: 'shorts/short192/short192_07.png', kind: 'image', motion: 'parallax'},   // hands flat on a plank table
  {line: 'L2', id: 'p08', src: 'shorts/short192/short192_08.png', kind: 'image', motion: 'kenburns'},   // an iron-bound door, closed
  {line: 'L2', id: 'p09', src: 'shorts/short192/short192_09.png', kind: 'image', motion: 'pushin'},   // an empty chair in a stone hall
  {line: 'L2', id: 'p10', src: 'shorts/short192/short192_10.png', kind: 'image', motion: 'parallax'},   // one coin standing on edge
  {line: 'L2', id: 'p11', src: 'shorts/short192/short192_11.png', kind: 'image', motion: 'kenburns'},   // dust in a stone room
  {line: 'L3', id: 'p12', src: 'shorts/short192/short192_12.png', kind: 'image', motion: 'pushin'},   // the seal pressed into wax
  {line: 'L3', id: 'p13', src: 'shorts/short192/short192_13.png', kind: 'image', motion: 'parallax'},   // a narrow window at first light over a writing desk
  {line: 'L3', id: 'p14', src: 'shorts/short192/short192_14.png', kind: 'image', motion: 'kenburns'},   // a riverbank at last light
  {line: 'L3', id: 'p15', src: 'shorts/short192/short192_15.png', kind: 'image', motion: 'pushin'},   // a stone corridor to a lit doorway
  {line: 'L3', id: 'p16', src: 'shorts/short192/short192_16.png', kind: 'image', motion: 'parallax'},   // a blank-faced clock in a hall
  {line: 'L4', id: 'p17', src: 'shorts/short192/short192_17.png', kind: 'image', motion: 'kenburns'},   // the residue set aside on the table
  {line: 'L4', id: 'p18', src: 'shorts/short192/short192_18.png', kind: 'image', motion: 'pushin'},   // a wooden mallet mid-strike
  {line: 'L4', id: 'p19', src: 'shorts/short192/short192_19.png', kind: 'image', motion: 'parallax'},   // an aisle of chests and boxes
  {line: 'L4', id: 'p20', src: 'shorts/short192/short192_20.png', kind: 'image', motion: 'kenburns'},   // one figure in a shaft of light
  {line: 'L4', id: 'p21', src: 'shorts/short192/short192_21.png', kind: 'image', motion: 'pushin'},   // a heavy door closing on light
  {line: 'L4', id: 'p22', src: 'shorts/short192/short192_22.png', kind: 'image', motion: 'parallax'},   // doors opening onto daylight
  {line: 'L8', id: 'p23', src: 'shorts/short192/short192_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short192/short192_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short192/short192_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the modern file closed, the old law opened
  {line: 'L5', id: 'p26', src: 'shorts/short192/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // the centuries between the promise and the county
  {line: 'L5', id: 'p27', src: 'shorts/short192/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // bound volumes stacked on a table
  {line: 'L5', id: 'p28', src: 'shorts/short192/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a wall of bound volumes
  {line: 'L5', id: 'p29', src: 'shorts/short192/short192_29.png', kind: 'image', motion: 'kenburns'},   // a hand set down beside the book
  {line: 'L5', id: 'p30', src: 'shorts/short192/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // a figure walking away down a hall
  {line: 'L6', id: 'p31', src: 'shorts/short192/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // a corridor of court chambers
  {line: 'L6', id: 'p32', src: 'shorts/short192/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // an old courtroom gallery
  {line: 'L6', id: 'p33', src: 'shorts/short192/short192_33.png', kind: 'image', motion: 'pushin'},   // an empty chamber of seats
  {line: 'L6', id: 'p34', src: 'shorts/short192/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // two chairs facing across a room
  {line: 'L6', id: 'p35', src: 'shorts/short192/short192_35.png', kind: 'image', motion: 'kenburns'},   // one sheet on the floor of a hall
  {line: 'L7', id: 'p36', src: 'shorts/short192/short192_36.png', kind: 'image', motion: 'pushin'},   // the county tray the file sat in
  {line: 'L7', id: 'p37', src: 'shorts/short192/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // a locked service door
  {line: 'L7', id: 'p38', src: 'shorts/short192/short192_38.png', kind: 'image', motion: 'kenburns'},   // a counter of small personal things
  {line: 'L7', id: 'p39', src: 'shorts/short192/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // a long empty meeting table
  {line: 'L7', id: 'p40', src: 'shorts/short192/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a water tower over a small town at dawn
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT192_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT192: ShortData = {
  shortId: 'short192',
  episodeId: 'PD-2026-033-tyler',
  durationSec: SHORT192_TOTAL_SEC,
  narrationSrc: 'shorts/short192/audio/short192_final_mix_v002_en_us.mp3',
  captions: SHORT192_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short192/short192_ctathumb.jpg',
  ctaLongTitle: "The county sold her condo and kept the",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short192.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short192/short192_kin_a.webm', atSec: 14.65, durSec: 2.0, phrase: "1215 / EVEN THE KING"},
    {src: 'shorts/short192/short192_kin_b.webm', atSec: 43.77, durSec: 2.3, phrase: "THEY FORGOT THE LIMIT"},
  ],
};
