// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #317.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT317_TOTAL_SEC = 57.061;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.201
  },
  {
    "id": "L2",
    "start": 5.421,
    "end": 13.362
  },
  {
    "id": "L3",
    "start": 13.582,
    "end": 21.848
  },
  {
    "id": "L4",
    "start": 22.068,
    "end": 32.61
  },
  {
    "id": "L5",
    "start": 32.83,
    "end": 34.409
  },
  {
    "id": "L6",
    "start": 34.629,
    "end": 43.453
  },
  {
    "id": "L7",
    "start": 43.673,
    "end": 53.565
  },
  {
    "id": "L8",
    "start": 53.785,
    "end": 56.061
  }
];

export const SHORT317_CAPTIONS: ShortCaption[] = [
  {
    "word": "Was any of this a secret?",
    "startSec": 0.0,
    "endSec": 1.461
  },
  {
    "word": "Was there some piece of knowledge",
    "startSec": 1.461,
    "endSec": 3.389
  },
  {
    "word": "that the industry did not have?",
    "startSec": 3.389,
    "endSec": 5.201
  },
  {
    "word": "On the twenty-ninth of May 1984",
    "startSec": 5.421,
    "endSec": 7.49
  },
  {
    "word": "sixteen years before this accident",
    "startSec": 7.49,
    "endSec": 9.759
  },
  {
    "word": "McDonnell Douglas issued a service letter",
    "startSec": 9.759,
    "endSec": 12.494
  },
  {
    "word": "to operators.",
    "startSec": 12.494,
    "endSec": 13.362
  },
  {
    "word": "It reported three cases where",
    "startSec": 13.582,
    "endSec": 15.129
  },
  {
    "word": "a jackscrew assembly had come",
    "startSec": 15.129,
    "endSec": 16.675
  },
  {
    "word": "off an aeroplane far earlier than expected",
    "startSec": 16.675,
    "endSec": 18.915
  },
  {
    "word": "because of excessive play",
    "startSec": 18.915,
    "endSec": 20.248
  },
  {
    "word": "between the screw and the nut.",
    "startSec": 20.248,
    "endSec": 21.848
  },
  {
    "word": "Every nut showed severe wear",
    "startSec": 22.068,
    "endSec": 23.638
  },
  {
    "word": "on the thread surfaces.",
    "startSec": 23.638,
    "endSec": 24.928
  },
  {
    "word": "And the letter records what they found",
    "startSec": 24.928,
    "endSec": 27.059
  },
  {
    "word": "in the lubrication passages of two",
    "startSec": 27.059,
    "endSec": 28.965
  },
  {
    "word": "of them.",
    "startSec": 28.965,
    "endSec": 29.665
  },
  {
    "word": "The grease was dry",
    "startSec": 29.665,
    "endSec": 30.674
  },
  {
    "word": "and without evidence of recent renewal.",
    "startSec": 30.674,
    "endSec": 32.61
  },
  {
    "word": "Dry. In 1984.",
    "startSec": 32.83,
    "endSec": 34.409
  },
  {
    "word": "The letter concluded",
    "startSec": 34.629,
    "endSec": 35.753
  },
  {
    "word": "that inadequate lubrication was the most",
    "startSec": 35.753,
    "endSec": 38.001
  },
  {
    "word": "probable cause of the wear",
    "startSec": 38.001,
    "endSec": 39.463
  },
  {
    "word": "and it asked operators to keep",
    "startSec": 39.463,
    "endSec": 41.149
  },
  {
    "word": "to a conscientious lubrication programme.",
    "startSec": 41.149,
    "endSec": 43.453
  },
  {
    "word": "That is the manufacturer in writing",
    "startSec": 43.673,
    "endSec": 45.81
  },
  {
    "word": "sixteen years early",
    "startSec": 45.81,
    "endSec": 46.97
  },
  {
    "word": "describing the exact failure sequence",
    "startSec": 46.97,
    "endSec": 49.23
  },
  {
    "word": "that would eventually bring down flight 261",
    "startSec": 49.23,
    "endSec": 51.855
  },
  {
    "word": "and naming the exact remedy.",
    "startSec": 51.855,
    "endSec": 53.565
  },
  {
    "word": "None of this was hidden.",
    "startSec": 53.785,
    "endSec": 55.086
  },
  {
    "word": "It was circulated.",
    "startSec": 55.086,
    "endSec": 56.061
  }
];
