// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #47.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT47_TOTAL_SEC = 55.01;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 7.895
  },
  {
    "id": "L2",
    "start": 8.615,
    "end": 19.807
  },
  {
    "id": "L3",
    "start": 20.527,
    "end": 32.508
  },
  {
    "id": "L4",
    "start": 33.228,
    "end": 50.457
  },
  {
    "id": "L5",
    "start": 51.177,
    "end": 54.01
  }
];

export const SHORT47_CAPTIONS: ShortCaption[] = [
  {
    "word": "She lost her job then her car",
    "startSec": 0.0,
    "endSec": 1.612
  },
  {
    "word": "then her license.",
    "startSec": 1.612,
    "endSec": 2.558
  },
  {
    "word": "Then a court took her freedom over",
    "startSec": 2.558,
    "endSec": 4.448
  },
  {
    "word": "unpaid traffic tickets.",
    "startSec": 4.448,
    "endSec": 5.727
  },
  {
    "word": "Can they jail you just for being broke?",
    "startSec": 5.727,
    "endSec": 7.895
  },
  {
    "word": "In Montgomery unpaid fines only grew.",
    "startSec": 8.615,
    "endSec": 10.903
  },
  {
    "word": "A judge signed one order:",
    "startSec": 10.903,
    "endSec": 12.449
  },
  {
    "word": "pay fifteen hundred dollars or thirty-one days in jail.",
    "startSec": 12.449,
    "endSec": 15.85
  },
  {
    "word": "No one asked if she could pay.",
    "startSec": 15.85,
    "endSec": 17.705
  },
  {
    "word": "She could not and the door closed.",
    "startSec": 17.705,
    "endSec": 19.807
  },
  {
    "word": "Her probation was run by a private",
    "startSec": 20.527,
    "endSec": 22.439
  },
  {
    "word": "company for profit.",
    "startSec": 22.439,
    "endSec": 23.508
  },
  {
    "word": "Forty dollars of every payment went to",
    "startSec": 23.508,
    "endSec": 25.646
  },
  {
    "word": "them not her fines.",
    "startSec": 25.646,
    "endSec": 26.714
  },
  {
    "word": "The more she owed the more they earned.",
    "startSec": 26.714,
    "endSec": 28.908
  },
  {
    "word": "And decades earlier the Supreme Court had",
    "startSec": 28.908,
    "endSec": 31.214
  },
  {
    "word": "already forbidden this.",
    "startSec": 31.214,
    "endSec": 32.508
  },
  {
    "word": "In 1983 Bearden versus Georgia said it plainly:",
    "startSec": 33.228,
    "endSec": 36.454
  },
  {
    "word": "you cannot be jailed just for being",
    "startSec": 36.454,
    "endSec": 38.857
  },
  {
    "word": "too poor to pay.",
    "startSec": 38.857,
    "endSec": 39.955
  },
  {
    "word": "The law was on her side all along.",
    "startSec": 39.955,
    "endSec": 42.289
  },
  {
    "word": "What freed her was not the Supreme",
    "startSec": 42.289,
    "endSec": 44.622
  },
  {
    "word": "Court but a lower-court settlement in 2014.",
    "startSec": 44.622,
    "endSec": 47.574
  },
  {
    "word": "The rule held;",
    "startSec": 47.574,
    "endSec": 48.535
  },
  {
    "word": "enforcing it is what failed.",
    "startSec": 48.535,
    "endSec": 50.457
  },
  {
    "word": "Watch the full case on the channel.",
    "startSec": 51.177,
    "endSec": 53.121
  },
  {
    "word": "Follow for more.",
    "startSec": 53.121,
    "endSec": 54.01
  }
];
