import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT132_CAPTIONS, SHORT132_TOTAL_SEC} from './short132_timing';

/**
 * short132 — The rule protecting your home from a heat scan is tied to how rare the device is, so the protection weakens as the technology becomes ordinary.
 * Episode PD-2026-025-kyllo.  Type A.
 *
 * AVOIDS: The existing Short delivers the 2001 holding and the bright line at the front door; this cut is about the expiry date built into the phrase that holding depends on.
 * LEAVES FOR THE LONG-FORM: Which of today's ordinary sensors has already crossed from exotic into general public use?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-025-kyllo.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short132/short132_01.png', kind: 'image', motion: 'parallax', fast: true},   // a dark house seen through a windscreen, one wall warm
  {line: 'L1', id: 'p02', src: 'shorts/short132/short132_02.png', kind: 'image', motion: 'kenburns', fast: true},   // a boxed thermal imager on a car dashboard
  {line: 'L1', id: 'p03', src: 'shorts/short132/fx/fx_03.mp4', kind: 'video', motion: 'video', fast: true},   // frost creeping across glass
  {line: 'L1', id: 'p04', src: 'shorts/short132/short132_04.png', kind: 'image', motion: 'parallax'},   // calendar pages caught mid turn, dates blank
  {line: 'L2', id: 'p05', src: 'shorts/short132/short132_05.png', kind: 'image', motion: 'kenburns'},   // courthouse columns from directly below
  {line: 'L2', id: 'p06', src: 'shorts/short132/short132_06.png', kind: 'image', motion: 'pushin'},   // a pen underlining one blank line
  {line: 'L2', id: 'p07', src: 'shorts/short132/short132_07.png', kind: 'image', motion: 'parallax'},   // the imager alone on a workbench, dials blank
  {line: 'L2', id: 'p08', src: 'shorts/short132/fx/fx_08.mp4', kind: 'video', motion: 'video'},   // hands turning a lens ring
  {line: 'L2', id: 'p09', src: 'shorts/short132/short132_09.png', kind: 'image', motion: 'pushin'},   // a gloved hand clearing condensation from a car window
  {line: 'L2', id: 'p10', src: 'shorts/short132/short132_10.png', kind: 'image', motion: 'parallax'},   // heat rippling above a dark roof ridge
  {line: 'L2', id: 'p11', src: 'shorts/short132/fx/fx_11.mp4', kind: 'video', motion: 'video'},   // steam lifting in freezing air
  {line: 'L3', id: 'p12', src: 'shorts/short132/short132_12.png', kind: 'image', motion: 'pushin'},   // a string line lifted to a new position
  {line: 'L3', id: 'p13', src: 'shorts/short132/short132_13.png', kind: 'image', motion: 'parallax'},   // a phone face down, camera cluster catching light
  {line: 'L3', id: 'p14', src: 'shorts/short132/short132_14.png', kind: 'image', motion: 'kenburns'},   // a phone held in the dark
  {line: 'L3', id: 'p15', src: 'shorts/short132/short132_15.png', kind: 'image', motion: 'pushin'},   // a shelf of identical boxed gadgets in a closed store
  {line: 'L3', id: 'p16', src: 'shorts/short132/short132_16.png', kind: 'image', motion: 'parallax'},   // an empty suburban street down its centre line
  {line: 'L4', id: 'p17', src: 'shorts/short132/short132_17.png', kind: 'image', motion: 'kenburns'},   // a front door from inside, chain across it
  {line: 'L4', id: 'p18', src: 'shorts/short132/fx/fx_18.mp4', kind: 'video', motion: 'video'},   // a curtain drawn across a lit window
  {line: 'L4', id: 'p19', src: 'shorts/short132/short132_19.png', kind: 'image', motion: 'parallax'},   // a house hallway receding to one lit doorway
  {line: 'L4', id: 'p20', src: 'shorts/short132/short132_20.png', kind: 'image', motion: 'kenburns'},   // a roofline glowing from above at night
  {line: 'L4', id: 'p21', src: 'shorts/short132/short132_21.png', kind: 'image', motion: 'pushin'},   // the high bench from the floor, empty
  {line: 'L5', id: 'p22', src: 'shorts/short132/short132_22.png', kind: 'image', motion: 'parallax'},   // a quadcopter hovering low over a dark yard
  {line: 'L8', id: 'p23', src: 'shorts/short132/short132_04.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short132/short132_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short132/short132_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to plate 01: a dark house seen through a windscreen
  {line: 'L5', id: 'p26', src: 'shorts/short132/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // an empty road running ahead through a car windscreen at fi
  {line: 'L5', id: 'p27', src: 'shorts/short132/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // sand running steadily through an hourglass on a lit table
  {line: 'L5', id: 'p28', src: 'shorts/short132/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a hand tilting venetian blinds shut across a bright window
  {line: 'L5', id: 'p29', src: 'shorts/short132/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // a steel tape measure winding back into its case on a workb
  {line: 'L5', id: 'p30', src: 'shorts/short132/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // cameras of several sizes standing in a row on a bright tab
  {line: 'L6', id: 'p31', src: 'shorts/short132/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // a small quadcopter resting on cut grass in daylight
  {line: 'L6', id: 'p32', src: 'shorts/short132/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // a tiny camera module soldered to a green circuit board
  {line: 'L6', id: 'p33', src: 'shorts/short132/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // an open carton of small electronic parts on a bright bench
  {line: 'L6', id: 'p34', src: 'shorts/short132/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // a hand holding a small scanner flat against a plaster wall
  {line: 'L6', id: 'p35', src: 'shorts/short132/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // a miniature camera lens resting on a fingertip for scale
  {line: 'L7', id: 'p36', src: 'shorts/short132/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // an empty jury box of wooden seats in a lit courtroom
  {line: 'L7', id: 'p37', src: 'shorts/short132/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // a wooden gavel resting on its round block on a lit desk
  {line: 'L7', id: 'p38', src: 'shorts/short132/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a person seen from behind walking down a bright courthouse
  {line: 'L7', id: 'p39', src: 'shorts/short132/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // tall doors swinging open onto a bright stone plaza
  {line: 'L7', id: 'p40', src: 'shorts/short132/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a heavy gate standing closed across a bright driveway
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT132_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT132: ShortData = {
  shortId: 'short132',
  episodeId: 'PD-2026-025-kyllo',
  durationSec: SHORT132_TOTAL_SEC,
  narrationSrc: 'shorts/short132/audio/short132_final_mix_v002_en_us.mp3',
  captions: SHORT132_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short132/short132_ctathumb.jpg',
  ctaLongTitle: "Can the Police Scan Your Home From the",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
