import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT140_CAPTIONS, SHORT140_TOTAL_SEC} from './short140_timing';

/**
 * short140 — Justice Alito's majority called the Miranda warnings a protective fence around the Fifth Amendment, and everything else followed from that one distinction.
 * Episode PD-2026-044-tekoh.  Type C.
 *
 * AVOIDS: The existing Short states the outcome, that a skipped warning is not something you can sue over; this cut is the single legal move the majority used to get there.
 * LEAVES FOR THE LONG-FORM: If the warning is only a fence, what happens to the earlier ruling that called Miranda a constitutional rule?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-044-tekoh.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short140/short140_01.png', kind: 'image', motion: 'parallax', fast: true},   // a blank card slipped back unread into a pocket
  {line: 'L1', id: 'p02', src: 'shorts/short140/fx/fx_02.mp4', kind: 'video', motion: 'video', fast: true},   // a badge and uniform in close up
  {line: 'L1', id: 'p03', src: 'shorts/short140/fx/fx_03.mp4', kind: 'video', motion: 'video', fast: true},   // a bare table and two chairs under a low lamp
  {line: 'L1', id: 'p04', src: 'shorts/short140/fx/fx_04.mp4', kind: 'video', motion: 'video'},   // courthouse columns from below
  {line: 'L2', id: 'p05', src: 'shorts/short140/short140_05.png', kind: 'image', motion: 'kenburns'},   // a chain link fence raked by one floodlight
  {line: 'L2', id: 'p06', src: 'shorts/short140/short140_06.png', kind: 'image', motion: 'pushin'},   // a low railing around bare ground
  {line: 'L2', id: 'p07', src: 'shorts/short140/fx/fx_07.mp4', kind: 'video', motion: 'video'},   // fence shadows thrown across a wall
  {line: 'L2', id: 'p08', src: 'shorts/short140/short140_08.png', kind: 'image', motion: 'kenburns'},   // a pen pressed to a blank statement sheet
  {line: 'L2', id: 'p09', src: 'shorts/short140/short140_09.png', kind: 'image', motion: 'pushin'},   // a hospital service corridor at night
  {line: 'L2', id: 'p10', src: 'shorts/short140/fx/fx_10.mp4', kind: 'video', motion: 'video'},   // a hospital corridor after dark
  {line: 'L2', id: 'p11', src: 'shorts/short140/short140_11.png', kind: 'image', motion: 'kenburns'},   // the high bench from the floor, empty
  {line: 'L3', id: 'p12', src: 'shorts/short140/short140_12.png', kind: 'image', motion: 'pushin'},   // bare ground seen from inside the fence
  {line: 'L3', id: 'p13', src: 'shorts/short140/short140_13.png', kind: 'image', motion: 'parallax'},   // a foundation block half buried in dark earth
  {line: 'L3', id: 'p14', src: 'shorts/short140/fx/fx_14.mp4', kind: 'video', motion: 'video'},   // dry soil in raking light
  {line: 'L3', id: 'p15', src: 'shorts/short140/short140_15.png', kind: 'image', motion: 'pushin'},   // an open volume with entirely blank pages
  {line: 'L3', id: 'p16', src: 'shorts/short140/short140_16.png', kind: 'image', motion: 'parallax'},   // one empty chair under a hanging lamp
  {line: 'L4', id: 'p17', src: 'shorts/short140/short140_17.png', kind: 'image', motion: 'kenburns'},   // two rows of empty jury seats
  {line: 'L4', id: 'p18', src: 'shorts/short140/short140_18.png', kind: 'image', motion: 'pushin'},   // an empty drawer pulled from a wall of closed ones
  {line: 'L4', id: 'p19', src: 'shorts/short140/short140_19.png', kind: 'image', motion: 'parallax'},   // coins scattered on a dark table
  {line: 'L4', id: 'p20', src: 'shorts/short140/short140_20.png', kind: 'image', motion: 'kenburns'},   // a payout window with its shutter down
  {line: 'L4', id: 'p21', src: 'shorts/short140/short140_21.png', kind: 'image', motion: 'pushin'},   // one blank sheet on a courthouse floor
  {line: 'L5', id: 'p22', src: 'shorts/short140/short140_22.png', kind: 'image', motion: 'parallax'},   // one lamp burning at the end of a dark bench
  {line: 'L8', id: 'p23', src: 'shorts/short140/short140_01.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short140/short140_01.png', kind: 'image', motion: 'parallax'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short140/short140_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to plate 01: a blank card slipped back unread into 
  {line: 'L5', id: 'p26', src: 'shorts/short140/fx/fx_26.mp4', kind: 'video', motion: 'video'},   // a blank white card held between two fingers
  {line: 'L5', id: 'p27', src: 'shorts/short140/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // two hands folded together on a table
  {line: 'L5', id: 'p28', src: 'shorts/short140/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // a heavy wooden door swinging closed
  {line: 'L5', id: 'p29', src: 'shorts/short140/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // a long boardroom table with empty chairs
  {line: 'L5', id: 'p30', src: 'shorts/short140/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // a microphone standing on a bare table
  {line: 'L6', id: 'p31', src: 'shorts/short140/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // a heavy gate swinging shut across a driveway
  {line: 'L6', id: 'p32', src: 'shorts/short140/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // a corridor with a closed door at the end
  {line: 'L6', id: 'p33', src: 'shorts/short140/fx/fx_33.mp4', kind: 'video', motion: 'video'},   // a trolley of stacked boxes in a corridor
  {line: 'L6', id: 'p34', src: 'shorts/short140/fx/fx_34.mp4', kind: 'video', motion: 'video'},   // double doors with a push bar held closed
  {line: 'L6', id: 'p35', src: 'shorts/short140/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // a wall of empty wooden pigeonholes
  {line: 'L7', id: 'p36', src: 'shorts/short140/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // a row of empty chairs behind a wooden rail
  {line: 'L7', id: 'p37', src: 'shorts/short140/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // an empty payment counter window
  {line: 'L7', id: 'p38', src: 'shorts/short140/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a hand turning out an empty pocket
  {line: 'L7', id: 'p39', src: 'shorts/short140/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // a lone figure standing in a wide hall
  {line: 'L7', id: 'p40', src: 'shorts/short140/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // a person walking out through glass doors
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT140_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT140: ShortData = {
  shortId: 'short140',
  episodeId: 'PD-2026-044-tekoh',
  durationSec: SHORT140_TOTAL_SEC,
  narrationSrc: 'shorts/short140/audio/short140_final_mix_v002_en_us.mp3',
  captions: SHORT140_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short140/short140_ctathumb.jpg',
  ctaLongTitle: "Police Skipped His Rights \u2014 Then He",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
};
