// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #18.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT18_TOTAL_SEC = 44.944;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.712
  },
  {
    "id": "L2",
    "start": 7.712,
    "end": 14.214
  },
  {
    "id": "L3",
    "start": 16.214,
    "end": 24.898
  },
  {
    "id": "L4",
    "start": 26.898,
    "end": 38.972
  },
  {
    "id": "L5",
    "start": 40.972,
    "end": 43.944
  }
];

export const SHORT18_CAPTIONS: ShortCaption[] = [
  {
    "word": "In thirty-six minutes, almost a trillion dollars vanished from the U.S.",
    "startSec": 0.0,
    "endSec": 3.976
  },
  {
    "word": "stock market.",
    "startSec": 3.976,
    "endSec": 4.704
  },
  {
    "word": "Then it came back.",
    "startSec": 4.704,
    "endSec": 5.712
  },
  {
    "word": "May 6, 2010.",
    "startSec": 7.712,
    "endSec": 8.421
  },
  {
    "word": "The market fell nearly a thousand points in minutes, and famous shares briefly traded for a penny.",
    "startSec": 8.421,
    "endSec": 14.214
  },
  {
    "word": "Investigators traced part of the imbalance to a trader in a London bedroom, flashing giant orders he meant to cancel.",
    "startSec": 16.214,
    "endSec": 23.319
  },
  {
    "word": "The law calls it spoofing.",
    "startSec": 23.319,
    "endSec": 24.898
  },
  {
    "word": "He pleaded guilty to spoofing and wire fraud, but not to causing the crash.",
    "startSec": 26.898,
    "endSec": 31.819
  },
  {
    "word": "No account blames one man alone: a four-billion-dollar sell order and panicking machines were part of it too.",
    "startSec": 31.819,
    "endSec": 38.972
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 40.972,
    "endSec": 43.03
  },
  {
    "word": "Follow for more.",
    "startSec": 43.03,
    "endSec": 43.944
  }
];
