import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT257_CAPTIONS, SHORT257_TOTAL_SEC} from './short257_timing';

/**
 * short257 — One man signed ten thousand sworn foreclosure documents a month, and a working month contains about ten thousand minutes.
 * Episode PD-2026-059-robosigning.  Type ?.
 *
 * AVOIDS: This Short is only the deposition and what a sworn statement is supposed to mean. It does not tell the Cardoso house story or reach the Georgia factory and the payouts.
 * LEAVES FOR THE LONG-FORM: If nobody was reading the affidavits, how many of the houses taken on them were the wrong houses?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-059-robosigning.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short257/short257_01.png', kind: 'image', motion: 'parallax', fast: true},   // a hand mid-signature over a blank sheet
  {line: 'L1', id: 'p02', src: 'shorts/short257/short257_02.png', kind: 'image', motion: 'kenburns', fast: true},   // an in-tray overflowing with blank forms
  {line: 'L1', id: 'p03', src: 'shorts/short257/short257_03.png', kind: 'image', motion: 'pushin', fast: true},   // a leaning stack of unread folders on a desk
  {line: 'L1', id: 'p04', src: 'shorts/short257/short257_04.png', kind: 'image', motion: 'parallax'},   // a bare lamp burning into camera over a desk
  {line: 'L2', id: 'p05', src: 'shorts/short257/short257_05.png', kind: 'image', motion: 'kenburns'},   // a judge's high bench from the floor, empty
  {line: 'L2', id: 'p06', src: 'shorts/short257/short257_06.png', kind: 'image', motion: 'pushin'},   // rows of empty courtroom gallery benches
  {line: 'L2', id: 'p07', src: 'shorts/short257/short257_07.png', kind: 'image', motion: 'parallax'},   // a gavel caught mid-strike above its block
  {line: 'L2', id: 'p08', src: 'shorts/short257/short257_08.png', kind: 'image', motion: 'kenburns'},   // a rubber stamp resting on an ink pad
  {line: 'L2', id: 'p09', src: 'shorts/short257/short257_09.png', kind: 'image', motion: 'pushin'},   // a single empty chair in a cone of light
  {line: 'L2', id: 'p10', src: 'shorts/short257/short257_10.png', kind: 'image', motion: 'parallax'},   // a blank-faced institutional wall clock
  {line: 'L2', id: 'p11', src: 'shorts/short257/short257_11.png', kind: 'image', motion: 'kenburns'},   // courtroom doors opening onto flat daylight
  {line: 'L3', id: 'p12', src: 'shorts/short257/short257_12.png', kind: 'image', motion: 'pushin'},   // two hands laid flat on a wooden table
  {line: 'L3', id: 'p13', src: 'shorts/short257/short257_13.png', kind: 'image', motion: 'parallax'},   // two plain chairs facing each other in a small room
  {line: 'L3', id: 'p14', src: 'shorts/short257/short257_14.png', kind: 'image', motion: 'kenburns'},   // a shaft of light crossing an empty hearing room
  {line: 'L3', id: 'p15', src: 'shorts/short257/short257_15.png', kind: 'image', motion: 'pushin'},   // a lone silhouette high in a shaft of light
  {line: 'L3', id: 'p16', src: 'shorts/short257/short257_16.png', kind: 'image', motion: 'parallax'},   // a long conference table with chairs pushed in
  {line: 'L4', id: 'p17', src: 'shorts/short257/short257_17.png', kind: 'image', motion: 'kenburns'},   // two silhouettes across a small bare table
  {line: 'L4', id: 'p18', src: 'shorts/short257/short257_18.png', kind: 'image', motion: 'pushin'},   // a bare table and two chairs under a hanging lamp
  {line: 'L4', id: 'p19', src: 'shorts/short257/short257_19.png', kind: 'image', motion: 'parallax'},   // a phone lying face down on a table
  {line: 'L4', id: 'p20', src: 'shorts/short257/short257_20.png', kind: 'image', motion: 'kenburns'},   // documents fanned across a dark desk, figures blank
  {line: 'L4', id: 'p21', src: 'shorts/short257/short257_21.png', kind: 'image', motion: 'pushin'},   // an office window at first light over a stacked desk
  {line: 'L4', id: 'p22', src: 'shorts/short257/short257_22.png', kind: 'image', motion: 'parallax'},   // a wall of grey steel filing shelves
  {line: 'L8', id: 'p23', src: 'shorts/short257/short257_03.png', kind: 'image', motion: 'pushin'},   // return to the hook plate: a hand mid-signature over a blan
  {line: 'L8', id: 'p24', src: 'shorts/short257/short257_02.png', kind: 'image', motion: 'kenburns'},   // replay of the opening framing: a hand mid-signature over a
  {line: 'L8', id: 'p25', src: 'shorts/short257/short257_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to plate 01 a third time: a hand mid-signature over
  {line: 'L5', id: 'p26', src: 'shorts/short257/short257_26.png', kind: 'image', motion: 'kenburns'},   // a clock second hand sweeping across its face
  {line: 'L5', id: 'p27', src: 'shorts/short257/fx/fx_27.mp4', kind: 'video', motion: 'video'},   // a hand moving a stack of paper
  {line: 'L5', id: 'p28', src: 'shorts/short257/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // rows of desks in an open plan office
  {line: 'L5', id: 'p29', src: 'shorts/short257/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // an office hallway lined with glass partitions
  {line: 'L5', id: 'p30', src: 'shorts/short257/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // a desk clock beside a keyboard
  {line: 'L6', id: 'p31', src: 'shorts/short257/fx/fx_31.mp4', kind: 'video', motion: 'video'},   // a person carrying files down a hallway
  {line: 'L6', id: 'p32', src: 'shorts/short257/short257_32.png', kind: 'image', motion: 'kenburns'},   // a pen lying across a closed folder
  {line: 'L6', id: 'p33', src: 'shorts/short257/short257_33.png', kind: 'image', motion: 'pushin'},   // a coat hanging on the back of a chair
  {line: 'L6', id: 'p34', src: 'shorts/short257/short257_34.png', kind: 'image', motion: 'parallax'},   // a drawer of hanging files pulled open
  {line: 'L6', id: 'p35', src: 'shorts/short257/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // an office door swinging slowly closed
  {line: 'L7', id: 'p36', src: 'shorts/short257/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // paper feeding through an office printer
  {line: 'L7', id: 'p37', src: 'shorts/short257/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // shelves of archive boxes in a storeroom
  {line: 'L7', id: 'p38', src: 'shorts/short257/fx/fx_38.mp4', kind: 'video', motion: 'video'},   // a closed cardboard file box on a desk
  {line: 'L7', id: 'p39', src: 'shorts/short257/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // a spilled box of paperclips on a desk
  {line: 'L7', id: 'p40', src: 'shorts/short257/short257_40.png', kind: 'image', motion: 'parallax'},   // a bound transcript closed on a table
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT257_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT257: ShortData = {
  shortId: 'short257',
  episodeId: 'PD-2026-059-robosigning',
  durationSec: SHORT257_TOTAL_SEC,
  narrationSrc: 'shorts/short257/audio/short257_final_mix_v002_en_us.mp3',
  captions: SHORT257_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short257/short257_ctathumb.jpg',
  ctaLongTitle: "He Paid $139,000 Cash. There Was No",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short257.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short257/short257_kin_a.webm', atSec: 22.81, durSec: 2.3, phrase: "10,000 A MONTH"},
    {src: 'shorts/short257/short257_kin_b.webm', atSec: 40.75, durSec: 2.3, phrase: "400 A DAY HE READ NONE"},
  ],
};
