// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #282.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT282_TOTAL_SEC = 32.866;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 1.858
  },
  {
    "id": "L2",
    "start": 2.078,
    "end": 7.279
  },
  {
    "id": "L3",
    "start": 7.499,
    "end": 12.654
  },
  {
    "id": "L4",
    "start": 12.874,
    "end": 18.215
  },
  {
    "id": "L5",
    "start": 18.435,
    "end": 21.314
  },
  {
    "id": "L6",
    "start": 21.534,
    "end": 24.274
  },
  {
    "id": "L7",
    "start": 24.494,
    "end": 28.952
  },
  {
    "id": "L8",
    "start": 29.172,
    "end": 31.866
  }
];

export const SHORT282_CAPTIONS: ShortCaption[] = [
  {
    "word": "No one was ever",
    "startSec": 0.0,
    "endSec": 0.774
  },
  {
    "word": "charged with a crime.",
    "startSec": 0.774,
    "endSec": 1.858
  },
  {
    "word": "In December 1983 the county prosecutor and",
    "startSec": 2.078,
    "endSec": 4.402
  },
  {
    "word": "the United States Attorney announced their decision.",
    "startSec": 4.402,
    "endSec": 7.279
  },
  {
    "word": "Insufficient evidence to convict",
    "startSec": 7.499,
    "endSec": 9.374
  },
  {
    "word": "anyone of criminal negligence.",
    "startSec": 9.374,
    "endSec": 11.131
  },
  {
    "word": "No charges would be filed.",
    "startSec": 11.131,
    "endSec": 12.654
  },
  {
    "word": "By that date",
    "startSec": 12.874,
    "endSec": 13.574
  },
  {
    "word": "insurers had paid out over seventy-eight",
    "startSec": 13.574,
    "endSec": 15.871
  },
  {
    "word": "million dollars to settle civil lawsuits.",
    "startSec": 15.871,
    "endSec": 18.215
  },
  {
    "word": "And no one had yet",
    "startSec": 18.435,
    "endSec": 19.36
  },
  {
    "word": "taken responsibility for the collapse.",
    "startSec": 19.36,
    "endSec": 21.314
  },
  {
    "word": "What happened instead came",
    "startSec": 21.534,
    "endSec": 22.988
  },
  {
    "word": "from a licensing board.",
    "startSec": 22.988,
    "endSec": 24.274
  },
  {
    "word": "In February 1984 the state board for",
    "startSec": 24.494,
    "endSec": 26.525
  },
  {
    "word": "architects and engineers filed a complaint.",
    "startSec": 26.525,
    "endSec": 28.952
  },
  {
    "word": "Not a prosecution.",
    "startSec": 29.172,
    "endSec": 30.182
  },
  {
    "word": "A question about certificates.",
    "startSec": 30.182,
    "endSec": 31.866
  }
];
