import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT191_CAPTIONS, SHORT191_TOTAL_SEC} from './short191_timing';

/**
 * short191 — Three limits on the car-search power that sit on the public road itself: an arrest does not open the car, a rental driver keeps privacy, and the marijuana odor question has never been settled nationwide.
 * Episode PD-2026-032-carsearch.  Type ?.
 *
 * AVOIDS: Short 32 covered Carroll, probable cause and curtilage; this cut stays on the public road and covers Gant, rental-car privacy and the unsettled odor question.
 * LEAVES FOR THE LONG-FORM: Which of these limits an officer actually has to respect at your own window, and where the car-search power finally runs out of road.
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-032-carsearch.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short191/short191_01.png', kind: 'image', motion: 'parallax', fast: true},   // handcuffs closing at a roadside
  {line: 'L1', id: 'p02', src: 'shorts/short191/short191_02.png', kind: 'image', motion: 'kenburns', fast: true},   // the car left shut while the arrest happens
  {line: 'L1', id: 'p03', src: 'shorts/short191/short191_03.png', kind: 'image', motion: 'pushin', fast: true},   // the kerb they sit you on
  {line: 'L1', id: 'p04', src: 'shorts/short191/short191_04.png', kind: 'image', motion: 'parallax'},   // the tray your pockets go into
  {line: 'L2', id: 'p05', src: 'shorts/short191/short191_05.png', kind: 'image', motion: 'kenburns'},   // the bench that narrowed the rule
  {line: 'L2', id: 'p06', src: 'shorts/short191/short191_06.png', kind: 'image', motion: 'pushin'},   // the case the rule came from
  {line: 'L2', id: 'p07', src: 'shorts/short191/short191_07.png', kind: 'image', motion: 'parallax'},   // the lamp over the question
  {line: 'L2', id: 'p08', src: 'shorts/short191/short191_08.png', kind: 'image', motion: 'kenburns'},   // the table where the offense is named
  {line: 'L2', id: 'p09', src: 'shorts/short191/short191_09.png', kind: 'image', motion: 'pushin'},   // how long the car stays shut
  {line: 'L2', id: 'p10', src: 'shorts/short191/short191_10.png', kind: 'image', motion: 'parallax'},   // the sealed envelope nobody opens
  {line: 'L2', id: 'p11', src: 'shorts/short191/short191_11.png', kind: 'image', motion: 'kenburns'},   // a door that stays closed
  {line: 'L3', id: 'p12', src: 'shorts/short191/short191_12.png', kind: 'image', motion: 'pushin'},   // a hand over a blank rental form
  {line: 'L3', id: 'p13', src: 'shorts/short191/short191_13.png', kind: 'image', motion: 'parallax'},   // a phone face down on the passenger seat
  {line: 'L3', id: 'p14', src: 'shorts/short191/short191_14.png', kind: 'image', motion: 'kenburns'},   // a car door closing on a blade of light
  {line: 'L3', id: 'p15', src: 'shorts/short191/short191_15.png', kind: 'image', motion: 'pushin'},   // the counter where the keys change hands
  {line: 'L3', id: 'p16', src: 'shorts/short191/short191_16.png', kind: 'image', motion: 'parallax'},   // hands on a steering wheel
  {line: 'L4', id: 'p17', src: 'shorts/short191/short191_17.png', kind: 'image', motion: 'kenburns'},   // the tray of forms nobody reads
  {line: 'L4', id: 'p18', src: 'shorts/short191/short191_18.png', kind: 'image', motion: 'pushin'},   // the wall of files behind the counter
  {line: 'L4', id: 'p19', src: 'shorts/short191/short191_19.png', kind: 'image', motion: 'parallax'},   // the stamp on the agreement
  {line: 'L4', id: 'p20', src: 'shorts/short191/short191_20.png', kind: 'image', motion: 'kenburns'},   // two seats, one name on the paper
  {line: 'L4', id: 'p21', src: 'shorts/short191/short191_21.png', kind: 'image', motion: 'pushin'},   // one driver among a lot of cars
  {line: 'L4', id: 'p22', src: 'shorts/short191/short191_22.png', kind: 'image', motion: 'parallax'},   // the court that said so
  {line: 'L8', id: 'p23', src: 'shorts/short191/short191_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short191/short191_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short191/short191_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to handcuffs closing at a roadside
  {line: 'L5', id: 'p26', src: 'shorts/short191/short191_26.png', kind: 'image', motion: 'kenburns'},   // the air inside a stopped car
  {line: 'L5', id: 'p27', src: 'shorts/short191/short191_27.png', kind: 'image', motion: 'pushin'},   // the beacon at the window
  {line: 'L5', id: 'p28', src: 'shorts/short191/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // the corridor of a state courthouse
  {line: 'L5', id: 'p29', src: 'shorts/short191/fx/fx_29.mp4', kind: 'video', motion: 'video'},   // the bench where samples are tested
  {line: 'L5', id: 'p30', src: 'shorts/short191/short191_30.png', kind: 'image', motion: 'pushin'},   // a window at first light over a desk
  {line: 'L6', id: 'p31', src: 'shorts/short191/short191_31.png', kind: 'image', motion: 'parallax'},   // one state's own skyline
  {line: 'L6', id: 'p32', src: 'shorts/short191/fx/fx_32.mp4', kind: 'video', motion: 'video'},   // a corridor of identical state offices
  {line: 'L6', id: 'p33', src: 'shorts/short191/short191_33.png', kind: 'image', motion: 'pushin'},   // a state courtroom gallery
  {line: 'L6', id: 'p34', src: 'shorts/short191/short191_34.png', kind: 'image', motion: 'parallax'},   // the chamber where a state writes its rules
  {line: 'L6', id: 'p35', src: 'shorts/short191/fx/fx_35.mp4', kind: 'video', motion: 'video'},   // doors opening onto daylight in one state
  {line: 'L7', id: 'p36', src: 'shorts/short191/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // the decisions stacking up year by year
  {line: 'L7', id: 'p37', src: 'shorts/short191/fx/fx_37.mp4', kind: 'video', motion: 'video'},   // a road at the edge of one state
  {line: 'L7', id: 'p38', src: 'shorts/short191/short191_38.png', kind: 'image', motion: 'kenburns'},   // a driver walking away from the stop
  {line: 'L7', id: 'p39', src: 'shorts/short191/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // an officer at a driver's window
  {line: 'L7', id: 'p40', src: 'shorts/short191/fx/fx_40.mp4', kind: 'video', motion: 'video'},   // the drawer that opens on nothing
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT191_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT191: ShortData = {
  shortId: 'short191',
  episodeId: 'PD-2026-032-carsearch',
  durationSec: SHORT191_TOTAL_SEC,
  narrationSrc: 'shorts/short191/audio/short191_final_mix_v002_en_us.mp3',
  captions: SHORT191_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short191/short191_ctathumb.jpg',
  ctaLongTitle: "Police Can Search Your Car Without a",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short191.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short191/short191_kin_a.webm', atSec: 28.77, durSec: 2.3, phrase: "THE SMELL WAS ENOUGH"},
    {src: 'shorts/short191/short191_kin_b.webm', atSec: 38.89, durSec: 2.3, phrase: "ODOR IS NOT ENOUGH"},
  ],
};
