// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #143.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT143_TOTAL_SEC = 60.125;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 5.851
  },
  {
    "id": "L2",
    "start": 6.071,
    "end": 14.105
  },
  {
    "id": "L3",
    "start": 14.325,
    "end": 22.824
  },
  {
    "id": "L4",
    "start": 23.044,
    "end": 31.728
  },
  {
    "id": "L5",
    "start": 31.948,
    "end": 38.635
  },
  {
    "id": "L6",
    "start": 38.855,
    "end": 45.589
  },
  {
    "id": "L7",
    "start": 45.809,
    "end": 52.171
  },
  {
    "id": "L8",
    "start": 52.391,
    "end": 59.125
  }
];

export const SHORT143_CAPTIONS: ShortCaption[] = [
  {
    "word": "The Supreme Court let a",
    "startSec": 0.0,
    "endSec": 1.258
  },
  {
    "word": "deputy stop a truck without",
    "startSec": 1.258,
    "endSec": 2.734
  },
  {
    "word": "ever looking at the driver.",
    "startSec": 2.734,
    "endSec": 4.211
  },
  {
    "word": "One word in the record is why.",
    "startSec": 4.211,
    "endSec": 5.851
  },
  {
    "word": "Justice Elena Kagan wrote separately",
    "startSec": 6.071,
    "endSec": 8.167
  },
  {
    "word": "joined by Justice Ruth Bader Ginsburg",
    "startSec": 8.167,
    "endSec": 10.321
  },
  {
    "word": "to underline how little it takes",
    "startSec": 10.321,
    "endSec": 12.184
  },
  {
    "word": "to break the officer's inference.",
    "startSec": 12.184,
    "endSec": 14.105
  },
  {
    "word": "What made this stop reasonable she stressed",
    "startSec": 14.325,
    "endSec": 17.052
  },
  {
    "word": "was that the license was revoked.",
    "startSec": 17.052,
    "endSec": 19.145
  },
  {
    "word": "In Kansas that signals a driver",
    "startSec": 19.145,
    "endSec": 21.112
  },
  {
    "word": "who keeps ignoring the law.",
    "startSec": 21.112,
    "endSec": 22.824
  },
  {
    "word": "If the license had merely been suspended",
    "startSec": 23.044,
    "endSec": 25.456
  },
  {
    "word": "over something like an unpaid fee",
    "startSec": 25.456,
    "endSec": 27.446
  },
  {
    "word": "the case for assuming he was still",
    "startSec": 27.446,
    "endSec": 29.497
  },
  {
    "word": "behind the wheel would be far weaker.",
    "startSec": 29.497,
    "endSec": 31.728
  },
  {
    "word": "A deputy typed the truck's",
    "startSec": 31.948,
    "endSec": 33.62
  },
  {
    "word": "plate into his dashboard laptop",
    "startSec": 33.62,
    "endSec": 35.613
  },
  {
    "word": "and the screen came back",
    "startSec": 35.613,
    "endSec": 37.156
  },
  {
    "word": "with a revoked license.",
    "startSec": 37.156,
    "endSec": 38.635
  },
  {
    "word": "A revoked license in Kansas follows",
    "startSec": 38.855,
    "endSec": 40.978
  },
  {
    "word": "a serious or repeated pattern.",
    "startSec": 40.978,
    "endSec": 42.798
  },
  {
    "word": "It is the state saying",
    "startSec": 42.798,
    "endSec": 44.133
  },
  {
    "word": "you cannot drive at all.",
    "startSec": 44.133,
    "endSec": 45.589
  },
  {
    "word": "Kansas argued the likeliest",
    "startSec": 45.809,
    "endSec": 47.399
  },
  {
    "word": "driver is the owner.",
    "startSec": 47.399,
    "endSec": 48.578
  },
  {
    "word": "Glover's side called that a",
    "startSec": 48.578,
    "endSec": 50.168
  },
  {
    "word": "stereotype about a name",
    "startSec": 50.168,
    "endSec": 51.523
  },
  {
    "word": "not a fact.",
    "startSec": 51.523,
    "endSec": 52.171
  },
  {
    "word": "Revoked.",
    "startSec": 52.391,
    "endSec": 53.091
  },
  {
    "word": "That was the word.",
    "startSec": 53.091,
    "endSec": 54.127
  },
  {
    "word": "And a single glance showing the",
    "startSec": 54.127,
    "endSec": 55.911
  },
  {
    "word": "driver is not the owner is",
    "startSec": 55.911,
    "endSec": 57.408
  },
  {
    "word": "enough to wipe the suspicion away.",
    "startSec": 57.408,
    "endSec": 59.125
  }
];
