// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #36.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT36_TOTAL_SEC = 34.298;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.827
  },
  {
    "id": "L2",
    "start": 7.547,
    "end": 14.745
  },
  {
    "id": "L3",
    "start": 15.465,
    "end": 21.874
  },
  {
    "id": "L4",
    "start": 22.594,
    "end": 29.792
  },
  {
    "id": "L5",
    "start": 30.512,
    "end": 33.298
  }
];

export const SHORT36_CAPTIONS: ShortCaption[] = [
  {
    "word": "Police pull you over for expired tags. Hours later",
    "startSec": 0.0,
    "endSec": 2.943
  },
  {
    "word": "they're scrolling through everything on your phone",
    "startSec": 2.943,
    "endSec": 5.885
  },
  {
    "word": "with no warrant.",
    "startSec": 5.885,
    "endSec": 6.827
  },
  {
    "word": "Your photos your messages",
    "startSec": 7.547,
    "endSec": 9.047
  },
  {
    "word": "your location history",
    "startSec": 9.047,
    "endSec": 10.306
  },
  {
    "word": "more private than a search of your entire house",
    "startSec": 10.306,
    "endSec": 13.125
  },
  {
    "word": "all sitting in your pocket.",
    "startSec": 13.125,
    "endSec": 14.745
  },
  {
    "word": "After David Riley was arrested",
    "startSec": 15.465,
    "endSec": 17.182
  },
  {
    "word": "a detective went through his phone and",
    "startSec": 17.182,
    "endSec": 19.356
  },
  {
    "word": "used what was on it to tie",
    "startSec": 19.356,
    "endSec": 20.844
  },
  {
    "word": "him to a shooting.",
    "startSec": 20.844,
    "endSec": 21.874
  },
  {
    "word": "In twenty-fourteen",
    "startSec": 22.594,
    "endSec": 23.674
  },
  {
    "word": "the Supreme Court said no unanimously.",
    "startSec": 23.674,
    "endSec": 25.953
  },
  {
    "word": "A phone is not just another pocket.",
    "startSec": 25.953,
    "endSec": 28.052
  },
  {
    "word": "Searching it needs a warrant.",
    "startSec": 28.052,
    "endSec": 29.792
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 30.512,
    "endSec": 32.441
  },
  {
    "word": "Follow for more.",
    "startSec": 32.441,
    "endSec": 33.298
  }
];
