import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT260_CAPTIONS, SHORT260_TOTAL_SEC} from './short260_timing';

/**
 * short260 — Kentucky's procedure treated one unanswered visit as enough to post immediately, even though one missed knock proved little.
 * Episode PD-2026-062-greene.  Type ?.
 *
 * AVOIDS: No composite people, invented aftermath, guessed vote, or claim that removal occurred in these tenants' cases.
 * LEAVES FOR THE LONG-FORM: Why was the sheriff's name on a case about a housing authority's paper?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-062-greene.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short260/short260_01.png', kind: 'image', motion: 'parallax', fast: true},   // G055 approved episode plate
  {line: 'L1', id: 'p02', src: 'shorts/short260/short260_02.png', kind: 'image', motion: 'kenburns', fast: true},   // G063 approved episode plate
  {line: 'L1', id: 'p03', src: 'shorts/short260/short260_03.png', kind: 'image', motion: 'pushin', fast: true},   // G013 approved episode plate
  {line: 'L2', id: 'p04', src: 'shorts/short260/short260_04.png', kind: 'image', motion: 'parallax'},   // G057 approved episode plate
  {line: 'L2', id: 'p05', src: 'shorts/short260/short260_05.png', kind: 'image', motion: 'kenburns'},   // G175 approved episode plate
  {line: 'L2', id: 'p06', src: 'shorts/short260/short260_06.png', kind: 'image', motion: 'pushin'},   // G062 approved episode plate
  {line: 'L3', id: 'p07', src: 'shorts/short260/short260_07.png', kind: 'image', motion: 'parallax'},   // G047 approved episode plate
  {line: 'L3', id: 'p08', src: 'shorts/short260/short260_08.png', kind: 'image', motion: 'kenburns'},   // G040 approved episode plate
  {line: 'L3', id: 'p09', src: 'shorts/short260/short260_09.png', kind: 'image', motion: 'pushin'},   // G069 approved episode plate
  {line: 'L4', id: 'p10', src: 'shorts/short260/short260_10.png', kind: 'image', motion: 'parallax'},   // G070 approved episode plate
  {line: 'L4', id: 'p11', src: 'shorts/short260/short260_11.png', kind: 'image', motion: 'kenburns'},   // G072 approved episode plate
  {line: 'L4', id: 'p12', src: 'shorts/short260/short260_12.png', kind: 'image', motion: 'pushin'},   // G039 approved episode plate
  {line: 'L5', id: 'p13', src: 'shorts/short260/short260_13.png', kind: 'image', motion: 'parallax'},   // G038 approved episode plate
  {line: 'L5', id: 'p14', src: 'shorts/short260/short260_14.png', kind: 'image', motion: 'kenburns'},   // G026 approved episode plate
  {line: 'L5', id: 'p15', src: 'shorts/short260/short260_15.png', kind: 'image', motion: 'pushin'},   // G058 approved episode plate
  {line: 'L6', id: 'p16', src: 'shorts/short260/short260_16.png', kind: 'image', motion: 'parallax'},   // G117 approved episode plate
  {line: 'L6', id: 'p17', src: 'shorts/short260/short260_17.png', kind: 'image', motion: 'kenburns'},   // G020 approved episode plate
  {line: 'L6', id: 'p18', src: 'shorts/short260/short260_18.png', kind: 'image', motion: 'pushin'},   // G188 approved episode plate
  {line: 'L7', id: 'p19', src: 'shorts/short260/short260_19.png', kind: 'image', motion: 'parallax'},   // G190 approved episode plate
  {line: 'L7', id: 'p20', src: 'shorts/short260/short260_20.png', kind: 'image', motion: 'kenburns'},   // G189 approved episode plate
  {line: 'L8', id: 'p21', src: 'shorts/short260/short260_03.png', kind: 'image', motion: 'pushin'},   // loop return 1
  {line: 'L8', id: 'p22', src: 'shorts/short260/short260_02.png', kind: 'image', motion: 'kenburns'},   // loop return 2
  {line: 'L8', id: 'p23', src: 'shorts/short260/short260_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // loop return 3
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT260_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT260: ShortData = {
  shortId: 'short260',
  episodeId: 'PD-2026-062-greene',
  durationSec: SHORT260_TOTAL_SEC,
  narrationSrc: 'shorts/short260/audio/short260_final_mix_v002_en_us.mp3',
  captions: SHORT260_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short260/short260_ctathumb.jpg',
  ctaLongTitle: "A Paper on the Door",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short260.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short260/short260_kin_one_attempt.webm', atSec: 0.05, durSec: 2.2, phrase: "ONE ATTEMPT"},
  ],
};
