import type {ShortBeat, ShortData} from '../compositions/Short';
import {LINE_WINDOWS, SHORT187_CAPTIONS, SHORT187_TOTAL_SEC} from './short187_timing';

/**
 * short187 — Texas built a commission to ask whether the science was reliable, and the meeting where its expert's findings would have been discussed was stopped two days beforehand.
 * Episode PD-2026-051-willingham.  Type C - a quotation and what followed it.
 *
 * AVOIDS: Short 55 ended on the experts' conclusions; this cut is the machinery around them, the commission, the replaced members, the canceled meeting and the conviction that still stands.
 * LEAVES FOR THE LONG-FORM: What had the state's own expert found in the fire evidence that made a scheduled public meeting worth stopping?
 *
 * GENERATED BY scripts/assemble_short.py from the design at
 * episodes/_planning/short_designs/PD-2026-051-willingham.design.v001.json — edit the design, not this file.
 *
 * The funnel card is the last thing on screen and holds to the final frame: Shorts loops on its
 * own, and conversion is the measured bottleneck (0.77 subs/1000 views on Shorts against 3.67 on
 * long-form), so the destination is worth more than a seamless loop seam.
 */

type Cut = {line: string; id: string; src: string; kind: 'image' | 'video';
  motion: ShortBeat['motion']; fast?: boolean; isCta?: boolean; rewind?: boolean};

const r3 = (n: number) => Math.round(n * 1000) / 1000;

const CUTS: Cut[] = [
  {line: 'L1', id: 'p01', src: 'shorts/short187/short187_01.png', kind: 'image', motion: 'parallax', fast: true},   // the chamber the meeting was set for
  {line: 'L1', id: 'p02', src: 'shorts/short187/short187_02.png', kind: 'image', motion: 'kenburns', fast: true},   // the chairman's seat, vacated
  {line: 'L1', id: 'p03', src: 'shorts/short187/short187_03.png', kind: 'image', motion: 'pushin', fast: true},   // the table set for a meeting that did not happen
  {line: 'L1', id: 'p04', src: 'shorts/short187/short187_04.png', kind: 'image', motion: 'parallax'},   // two days before
  {line: 'L2', id: 'p05', src: 'shorts/short187/short187_05.png', kind: 'image', motion: 'kenburns'},   // the science the commission existed to test
  {line: 'L2', id: 'p06', src: 'shorts/short187/short187_06.png', kind: 'image', motion: 'pushin'},   // the review, in folders
  {line: 'L2', id: 'p07', src: 'shorts/short187/short187_07.png', kind: 'image', motion: 'parallax'},   // the work that arrives at a commission
  {line: 'L2', id: 'p08', src: 'shorts/short187/short187_08.png', kind: 'image', motion: 'kenburns'},   // the office before the hearing
  {line: 'L2', id: 'p09', src: 'shorts/short187/short187_09.png', kind: 'image', motion: 'pushin'},   // the original investigation, stored
  {line: 'L2', id: 'p10', src: 'shorts/short187/short187_10.png', kind: 'image', motion: 'parallax'},   // the corridor to the hearing room
  {line: 'L2', id: 'p11', src: 'shorts/short187/short187_11.png', kind: 'image', motion: 'kenburns'},   // the offices along that corridor
  {line: 'L3', id: 'p12', src: 'shorts/short187/short187_12.png', kind: 'image', motion: 'pushin'},   // the report, written out
  {line: 'L3', id: 'p13', src: 'shorts/short187/short187_13.png', kind: 'image', motion: 'parallax'},   // one page of the finding
  {line: 'L3', id: 'p14', src: 'shorts/short187/short187_14.png', kind: 'image', motion: 'kenburns'},   // hands on the table where it was read
  {line: 'L3', id: 'p15', src: 'shorts/short187/short187_15.png', kind: 'image', motion: 'pushin'},   // the state's own paper on the case
  {line: 'L3', id: 'p16', src: 'shorts/short187/short187_16.png', kind: 'image', motion: 'parallax'},   // the report, bound and closed
  {line: 'L4', id: 'p17', src: 'shorts/short187/short187_17.png', kind: 'image', motion: 'kenburns'},   // the lamp left burning in the chamber
  {line: 'L4', id: 'p18', src: 'shorts/short187/short187_18.png', kind: 'image', motion: 'pushin'},   // the room after the meeting was called off
  {line: 'L4', id: 'p19', src: 'shorts/short187/short187_19.png', kind: 'image', motion: 'parallax'},   // the courts that never reopened it
  {line: 'L4', id: 'p20', src: 'shorts/short187/short187_20.png', kind: 'image', motion: 'kenburns'},   // the bench that has not ruled
  {line: 'L4', id: 'p21', src: 'shorts/short187/short187_21.png', kind: 'image', motion: 'pushin'},   // the conviction, still stamped
  {line: 'L4', id: 'p22', src: 'shorts/short187/short187_22.png', kind: 'image', motion: 'parallax'},   // one state, one unanswered question
  {line: 'L8', id: 'p23', src: 'shorts/short187/short187_03.png', kind: 'image', motion: 'pushin'},   // return to the hook - replay of the opening framing (1)
  {line: 'L8', id: 'p24', src: 'shorts/short187/short187_02.png', kind: 'image', motion: 'kenburns'},   // return to the hook - replay of the opening framing (2)
  {line: 'L8', id: 'p25', src: 'shorts/short187/short187_01.png', kind: 'image', motion: 'parallax', isCta: true, rewind: true, fast: true},   // return to the hook - replay of the opening framing (3)
  {line: 'L5', id: 'p26', src: 'shorts/short187/short187_26.png', kind: 'image', motion: 'kenburns'},   // the room booked for the review
  {line: 'L5', id: 'p27', src: 'shorts/short187/short187_27.png', kind: 'image', motion: 'pushin'},   // seats nobody sat in
  {line: 'L5', id: 'p28', src: 'shorts/short187/fx/fx_28.mp4', kind: 'video', motion: 'video'},   // the microphone nobody spoke into
  {line: 'L5', id: 'p29', src: 'shorts/short187/short187_29.png', kind: 'image', motion: 'kenburns'},   // the meeting, closed
  {line: 'L5', id: 'p30', src: 'shorts/short187/fx/fx_30.mp4', kind: 'video', motion: 'video'},   // the offices that carried on
  {line: 'L6', id: 'p31', src: 'shorts/short187/short187_31.png', kind: 'image', motion: 'parallax'},   // the building the decision came from
  {line: 'L6', id: 'p32', src: 'shorts/short187/short187_32.png', kind: 'image', motion: 'kenburns'},   // the place a finding is read aloud
  {line: 'L6', id: 'p33', src: 'shorts/short187/short187_33.png', kind: 'image', motion: 'pushin'},   // the public who came to hear it
  {line: 'L6', id: 'p34', src: 'shorts/short187/short187_34.png', kind: 'image', motion: 'parallax'},   // the desk the report sat on
  {line: 'L6', id: 'p35', src: 'shorts/short187/short187_35.png', kind: 'image', motion: 'kenburns'},   // leaving the building afterward
  {line: 'L7', id: 'p36', src: 'shorts/short187/fx/fx_36.mp4', kind: 'video', motion: 'video'},   // the courthouse that stayed shut to it
  {line: 'L7', id: 'p37', src: 'shorts/short187/short187_37.png', kind: 'image', motion: 'parallax'},   // the file, closed again
  {line: 'L7', id: 'p38', src: 'shorts/short187/short187_38.png', kind: 'image', motion: 'kenburns'},   // the bench that never revisited it
  {line: 'L7', id: 'p39', src: 'shorts/short187/fx/fx_39.mp4', kind: 'video', motion: 'video'},   // the counter where records live
  {line: 'L7', id: 'p40', src: 'shorts/short187/short187_40.png', kind: 'image', motion: 'parallax'},   // where the case is kept now
];

const buildBeats = (): ShortBeat[] => {
  const beats: ShortBeat[] = [];
  LINE_WINDOWS.forEach((win, i) => {
    const start = win.start;
    const end = i + 1 < LINE_WINDOWS.length ? LINE_WINDOWS[i + 1].start : SHORT187_TOTAL_SEC;
    const cuts = CUTS.filter((c) => c.line === win.id);
    // The card needs ~2.5 s to be read, but METHOD rule 6 caps any held frame at 2 s and a
    // weight-based share breaks that whenever a line carries few cuts: at weight 1.9 the card
    // ran 3.20 s on short94 and 2.63 s on short90, while short93 sat at 0.83 s. Give it a fixed
    // 1.9 s and let the other cuts of that line share what is left, so the ceiling holds
    // whatever the cut count is.
    // Capping the card at a fixed 1.9 s left 7.8 s of L5 with NO beat at all on short87 - the
    // screen went black under the captions. A line window must always be covered end to end.
    // So: the card takes at most 1.9 s of MOTION, then holds the same beat to the end of the
    // line rather than handing the remainder to nobody. Every second of every window is owned.
    const span = end - start;
    const nCta = cuts.filter((c) => c.isCta).length;
    const others = cuts.length - nCta;
    // when the card is the only cut in its line it simply takes the whole window
    const ctaDur = others === 0 ? span : Math.min(1.9, span / cuts.length * 2);
    const rest = others > 0 ? (span - ctaDur * nCta) / others : 0;
    let cursor = start;
    cuts.forEach((c) => {
      const dur = c.isCta ? ctaDur : rest;
      const {line: _l, isCta, ...keep} = c;
      beats.push({...keep, id: isCta ? 'cta' : c.id, startSec: r3(cursor), durSec: r3(dur)});
      cursor += dur;
    });
  });
  return beats;
};

export const SHORT187: ShortData = {
  shortId: 'short187',
  episodeId: 'PD-2026-051-willingham',
  durationSec: SHORT187_TOTAL_SEC,
  narrationSrc: 'shorts/short187/audio/short187_final_mix_v002_en_us.mp3',
  captions: SHORT187_CAPTIONS,
  bgmSrc: null,
  ctaTextYT: 'Watch the full case on the channel',
  ctaTextTT: 'Full case on our profile',
  ctaLongThumbSrc: 'shorts/short187/short187_ctathumb.jpg',
  ctaLongTitle: "Texas Executed Him for an Arson. The",
  ctaHeadline: 'FULL CASE',
  captionTop: 1210,
  ctaFadeOutSec: 0.8,
  beats: buildBeats(),
  // Mid-roll kinetic type, built in After Effects (runs/ae_jobs/short187.json) and installed
  // into this Short's public directory by scripts/ae/render_beats.sh. Words are taken
  // verbatim from the narration line each beat sits on.
  kineticBeats: [
    {src: 'shorts/short187/short187_kin_a.webm', atSec: 19.08, durSec: 2.3, phrase: "MYSTICS OR PSYCHICS"},
    {src: 'shorts/short187/short187_kin_b.webm', atSec: 44.7, durSec: 2.3, phrase: "STILL NOT OVERTURNED"},
  ],
};
