// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #26.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT26_TOTAL_SEC = 58.835;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 6.92
  },
  {
    "id": "L2",
    "start": 8.12,
    "end": 20.427
  },
  {
    "id": "L3",
    "start": 21.627,
    "end": 32.773
  },
  {
    "id": "L4",
    "start": 33.973,
    "end": 53.524
  },
  {
    "id": "L5",
    "start": 54.724,
    "end": 57.835
  }
];

export const SHORT26_CAPTIONS: ShortCaption[] = [
  {
    "word": "The FBI recorded every word he said — and never opened the door.",
    "startSec": 0.0,
    "endSec": 4.101
  },
  {
    "word": "The Court still called it an illegal search.",
    "startSec": 4.101,
    "endSec": 6.92
  },
  {
    "word": "Los Angeles, 1965.",
    "startSec": 8.12,
    "endSec": 9.244
  },
  {
    "word": "Charles Katz stepped into a glass phone booth to place illegal betting calls.",
    "startSec": 9.244,
    "endSec": 14.055
  },
  {
    "word": "To catch him, agents taped a hidden microphone to the outside of the glass, and never set foot inside.",
    "startSec": 14.055,
    "endSec": 20.427
  },
  {
    "word": "For nearly forty years, the rule was simple: no physical trespass, no search.",
    "startSec": 21.627,
    "endSec": 26.86
  },
  {
    "word": "But Katz had shut the door and paid the toll — to keep his words private, not his face.",
    "startSec": 26.86,
    "endSec": 32.773
  },
  {
    "word": "December eighteenth, 1967 — seven to one.",
    "startSec": 33.973,
    "endSec": 36.518
  },
  {
    "word": "The Fourth Amendment protects people, not places.",
    "startSec": 36.518,
    "endSec": 39.559
  },
  {
    "word": "Recording him without a warrant was unconstitutional — not a ban on wiretaps, just a judge's permission first.",
    "startSec": 39.559,
    "endSec": 46.386
  },
  {
    "word": "Justice Harlan's concurrence gave the reasonable-expectation-of-privacy test that still governs surveillance today.",
    "startSec": 46.386,
    "endSec": 53.524
  },
  {
    "word": "Watch the full story on the channel.",
    "startSec": 54.724,
    "endSec": 56.878
  },
  {
    "word": "Follow for more.",
    "startSec": 56.878,
    "endSec": 57.835
  }
];
