// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #174.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT174_TOTAL_SEC = 57.804;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 3.669
  },
  {
    "id": "L2",
    "start": 3.889,
    "end": 13.409
  },
  {
    "id": "L3",
    "start": 13.629,
    "end": 22.035
  },
  {
    "id": "L4",
    "start": 22.255,
    "end": 32.332
  },
  {
    "id": "L5",
    "start": 32.552,
    "end": 38.496
  },
  {
    "id": "L6",
    "start": 38.716,
    "end": 44.475
  },
  {
    "id": "L7",
    "start": 44.695,
    "end": 50.5
  },
  {
    "id": "L8",
    "start": 50.72,
    "end": 56.804
  }
];

export const SHORT174_CAPTIONS: ShortCaption[] = [
  {
    "word": "A court can erase a child's record.",
    "startSec": 0.0,
    "endSec": 1.976
  },
  {
    "word": "It cannot give back the years.",
    "startSec": 1.976,
    "endSec": 3.669
  },
  {
    "word": "Pennsylvania's Supreme Court reached back into",
    "startSec": 3.889,
    "endSec": 6.363
  },
  {
    "word": "that courtroom and unmade it",
    "startSec": 6.363,
    "endSec": 7.869
  },
  {
    "word": "throwing out thousands of adjudications and",
    "startSec": 7.869,
    "endSec": 10.182
  },
  {
    "word": "clearing the records of as many",
    "startSec": 10.182,
    "endSec": 11.849
  },
  {
    "word": "as several thousand children.",
    "startSec": 11.849,
    "endSec": 13.409
  },
  {
    "word": "Behind each of those",
    "startSec": 13.629,
    "endSec": 14.912
  },
  {
    "word": "cases was a year or two",
    "startSec": 14.912,
    "endSec": 16.388
  },
  {
    "word": "or three that the",
    "startSec": 16.388,
    "endSec": 17.479
  },
  {
    "word": "county had already spent.",
    "startSec": 17.479,
    "endSec": 19.083
  },
  {
    "word": "Nights in a cell that",
    "startSec": 19.083,
    "endSec": 20.431
  },
  {
    "word": "no order could give back.",
    "startSec": 20.431,
    "endSec": 22.035
  },
  {
    "word": "The judges are named and gone.",
    "startSec": 22.255,
    "endSec": 23.944
  },
  {
    "word": "One spent years in prison.",
    "startSec": 23.944,
    "endSec": 25.408
  },
  {
    "word": "The other was quietly",
    "startSec": 25.408,
    "endSec": 26.59
  },
  {
    "word": "granted an early release",
    "startSec": 26.59,
    "endSec": 27.941
  },
  {
    "word": "and walked back out while the children",
    "startSec": 27.941,
    "endSec": 30.08
  },
  {
    "word": "he sentenced were still carrying theirs.",
    "startSec": 30.08,
    "endSec": 32.332
  },
  {
    "word": "The record followed them onto every",
    "startSec": 32.552,
    "endSec": 34.478
  },
  {
    "word": "job form and every college application",
    "startSec": 34.478,
    "endSec": 36.57
  },
  {
    "word": "closing doors they never saw close.",
    "startSec": 36.57,
    "endSec": 38.496
  },
  {
    "word": "Some came out and",
    "startSec": 38.716,
    "endSec": 39.623
  },
  {
    "word": "never found their footing. Grown now",
    "startSec": 39.623,
    "endSec": 41.542
  },
  {
    "word": "some of them still cannot",
    "startSec": 41.542,
    "endSec": 42.875
  },
  {
    "word": "put that courtroom into words.",
    "startSec": 42.875,
    "endSec": 44.475
  },
  {
    "word": "Money is supposed to",
    "startSec": 44.695,
    "endSec": 45.833
  },
  {
    "word": "stay outside a courtroom.",
    "startSec": 45.833,
    "endSec": 47.256
  },
  {
    "word": "Here that line had a price:",
    "startSec": 47.256,
    "endSec": 48.793
  },
  {
    "word": "a few thousand dollars a head.",
    "startSec": 48.793,
    "endSec": 50.5
  },
  {
    "word": "The men could be punished.",
    "startSec": 50.72,
    "endSec": 52.286
  },
  {
    "word": "The years still do not come back.",
    "startSec": 52.286,
    "endSec": 54.274
  },
  {
    "word": "That is what a",
    "startSec": 54.274,
    "endSec": 55.117
  },
  {
    "word": "cleared record cannot reach.",
    "startSec": 55.117,
    "endSec": 56.804
  }
];
