// AUTO-GENERATED by scripts/build_short_mix.py — narration-driven timing for SHORT #171.
import type {ShortCaption} from '../compositions/Short';

export type LineWindow = {id: string; start: number; end: number};

export const SHORT171_TOTAL_SEC = 37.778;

export const LINE_WINDOWS: LineWindow[] = [
  {
    "id": "L1",
    "start": 0.0,
    "end": 8.034
  },
  {
    "id": "L2",
    "start": 8.254,
    "end": 15.034
  },
  {
    "id": "L3",
    "start": 15.254,
    "end": 21.802
  },
  {
    "id": "L4",
    "start": 22.022,
    "end": 31.96
  },
  {
    "id": "L5",
    "start": 32.18,
    "end": 36.778
  }
];

export const SHORT171_CAPTIONS: ShortCaption[] = [
  {
    "word": "There was no warning and no hearing.",
    "startSec": 0.0,
    "endSec": 2.037
  },
  {
    "word": "Just a knock at the door",
    "startSec": 2.037,
    "endSec": 3.395
  },
  {
    "word": "and an instruction:",
    "startSec": 3.395,
    "endSec": 4.47
  },
  {
    "word": "pack a bag",
    "startSec": 4.47,
    "endSec": 5.17
  },
  {
    "word": "and get out.",
    "startSec": 5.17,
    "endSec": 5.87
  },
  {
    "word": "The family had been charged with nothing.",
    "startSec": 5.87,
    "endSec": 8.034
  },
  {
    "word": "For about a week they",
    "startSec": 8.254,
    "endSec": 9.375
  },
  {
    "word": "slept on a relative's couch",
    "startSec": 9.375,
    "endSec": 10.817
  },
  {
    "word": "made homeless in their own city",
    "startSec": 10.817,
    "endSec": 12.471
  },
  {
    "word": "while the government held the",
    "startSec": 12.471,
    "endSec": 14.02
  },
  {
    "word": "deed to their home.",
    "startSec": 14.02,
    "endSec": 15.034
  },
  {
    "word": "Then the city let them back in",
    "startSec": 15.254,
    "endSec": 16.933
  },
  {
    "word": "on one condition.",
    "startSec": 16.933,
    "endSec": 17.884
  },
  {
    "word": "The father had to sign an agreement",
    "startSec": 17.884,
    "endSec": 19.843
  },
  {
    "word": "barring his own son from the house.",
    "startSec": 19.843,
    "endSec": 21.802
  },
  {
    "word": "To get their home back",
    "startSec": 22.022,
    "endSec": 23.204
  },
  {
    "word": "these parents had to give up",
    "startSec": 23.204,
    "endSec": 24.708
  },
  {
    "word": "their son at the door.",
    "startSec": 24.708,
    "endSec": 25.89
  },
  {
    "word": "It could just as easily",
    "startSec": 25.89,
    "endSec": 27.125
  },
  {
    "word": "have been your address",
    "startSec": 27.125,
    "endSec": 28.307
  },
  {
    "word": "not because you did anything",
    "startSec": 28.307,
    "endSec": 29.811
  },
  {
    "word": "but because someone under your roof did.",
    "startSec": 29.811,
    "endSec": 31.96
  },
  {
    "word": "They kept the house.",
    "startSec": 32.18,
    "endSec": 33.191
  },
  {
    "word": "They did not drop the class action",
    "startSec": 33.191,
    "endSec": 34.908
  },
  {
    "word": "for everyone still facing that knock.",
    "startSec": 34.908,
    "endSec": 36.778
  }
];
