#!/usr/bin/env python3
"""Build or validate EP39 Frazier After Effects card specs.

The first responsibility is a hard safety gate: unresolved script slots must
stop the pipeline instead of being guessed.
"""
from __future__ import annotations

import argparse
import json
import re
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EP = "PD-2026-039-frazier"
EPDIR = ROOT / "episodes" / EP
DEFAULT_SPEC = EPDIR / "04_scenes" / "ae_cards.spec.v001.json"
DEFAULT_JSX = EPDIR / "08_edit" / "ae_hero" / "frazier_ae.jsx"
DEFAULT_DERIVED = EPDIR / "08_edit" / "ae_hero" / "frazier_ae.resolved.v001.json"
DEFAULT_CARDS = EPDIR / "08_edit" / "ae_hero" / "cards.json"
CARD_ID = re.compile(r"^(hb|at|ex|tl|mp|iw)[0-9]{2}$")
FAMILIES = {"HERO_DATA", "ACT_TITLE", "EXHIBIT_DOC", "TIMELINE_TRACK", "MAP_DIAGRAM", "INTERSTITIAL_WIPE"}


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise SystemExit(f"FAIL frazier_ae: missing required spec {path}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"FAIL frazier_ae: malformed json {path}: {exc}") from exc


def validate_spec(spec: dict) -> list[dict]:
    if spec.get("episode_id") != EP:
        raise SystemExit(f"FAIL frazier_ae: episode_id must be {EP}")
    cards = spec.get("cards")
    if not isinstance(cards, list) or not cards:
        raise SystemExit("FAIL frazier_ae: cards[] is required")

    seen: set[str] = set()
    unresolved: list[str] = []
    missing_families = set(FAMILIES)
    for i, card in enumerate(cards):
        cid = str(card.get("id") or "")
        if not CARD_ID.match(cid):
            raise SystemExit(f"FAIL frazier_ae: cards[{i}].id '{cid}' must match ^(hb|at|ex|tl|mp|iw)[0-9]{{2}}$")
        if cid in seen:
            raise SystemExit(f"FAIL frazier_ae: duplicate card id {cid}")
        seen.add(cid)

        family = card.get("family")
        if family not in FAMILIES:
            raise SystemExit(f"FAIL frazier_ae: {cid}.family must be one of {sorted(FAMILIES)}")
        missing_families.discard(family)

        if card.get("claim_id") is None:
            raise SystemExit(f"FAIL frazier_ae: {cid}.claim_id is null")
        if family != "INTERSTITIAL_WIPE" and card.get("still") is None:
            raise SystemExit(f"FAIL frazier_ae: {cid}.still is required for {family}")
        if "value" in card and card.get("value") is None:
            unresolved.append(f"{cid}.value")
        if "anchor_phrase" in card and card.get("anchor_phrase") in (None, ""):
            unresolved.append(f"{cid}.anchor_phrase")
    if unresolved:
        raise SystemExit("FAIL frazier_ae: unresolved script slot(s): " + ", ".join(unresolved))
    if missing_families:
        raise SystemExit("FAIL frazier_ae: missing card families: " + ", ".join(sorted(missing_families)))
    return cards


def write_jsx(cards: list[dict], out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    render_dir = out.parent / "render"
    render_dir.mkdir(parents=True, exist_ok=True)
    comps = ",\n".join(
        f"  {{id: '{c['id']}', family: '{c['family']}', start: {float(c.get('start') or 0):.3f}, dur: {float(c.get('dur') or c.get('duration_sec') or 3):.3f}}}"
        for c in cards
    )
    jsx = f"""// Auto-generated by scripts/ae/build_frazier_ae_jsx.py
// EP39 AE card smoke project. No real evidence text is embedded here.
(function () {{
  var FPS = 30;
  var W = 1920;
  var H = 1080;
  var cards = [
{comps}
  ];
  var outFolder = new Folder('{str((EPDIR / '08_edit' / 'ae_hero').as_posix())}');
  var renderFolder = new Folder('{str(render_dir.as_posix())}');
  if (!outFolder.exists) outFolder.create();
  if (!renderFolder.exists) renderFolder.create();
  var errorFile = new File(renderFolder.fsName + '/_build_error.txt');
  try {{
  app.beginUndoGroup('EP39 Frazier AE cards');
  var project = app.project;
  if (!project) throw new Error('After Effects project unavailable');
  try {{ project.gpuAccelType = GpuAccelType.SOFTWARE; }} catch (e) {{}}
  try {{ project.bitsPerChannel = 8; }} catch (e) {{}}
  for (var oldIndex = project.numItems; oldIndex >= 1; oldIndex--) {{
    var oldItem = project.item(oldIndex);
    if (oldItem instanceof CompItem && oldItem.name.indexOf('FRZ_') === 0) oldItem.remove();
  }}
  function addText(comp, text, size, color, y) {{
    var layer = comp.layers.addText(text);
    var doc = layer.property('ADBE Text Properties').property('ADBE Text Document').value;
    doc.fontSize = size;
    doc.fillColor = color;
    doc.applyFill = true;
    doc.justification = ParagraphJustification.CENTER_JUSTIFY;
    layer.property('ADBE Text Properties').property('ADBE Text Document').setValue(doc);
    layer.property('ADBE Transform Group').property('ADBE Position').setValue([W/2, y]);
    return layer;
  }}
  for (var i = 0; i < cards.length; i++) {{
    var c = cards[i];
    var comp = project.items.addComp('FRZ_' + c.id + '_' + c.family, W, H, 1, c.dur, FPS);
    comp.motionBlur = true;
    var bg = comp.layers.addSolid([0.015, 0.03, 0.06], 'midnight', W, H, 1, c.dur);
    var grade = comp.layers.addSolid([0.04, 0.07, 0.13], 'cool_grade', W, H, 1, c.dur);
    grade.blendingMode = BlendingMode.MULTIPLY;
    grade.property('ADBE Transform Group').property('ADBE Opacity').setValue(c.family === 'ACT_TITLE' ? 46 : (c.family === 'EXHIBIT_DOC' ? 52 : 38));
    var line = comp.layers.addSolid([0.12, 0.42, 1.0], 'electric_blue_bar', W, c.family === 'INTERSTITIAL_WIPE' ? 180 : 12, 1, c.dur);
    line.property('ADBE Transform Group').property('ADBE Position').setValue([W/2, c.family === 'INTERSTITIAL_WIPE' ? H/2 : H*0.72]);
    line.motionBlur = true;
    var goldWidth = c.family === 'TIMELINE_TRACK' ? W*0.78 : (c.family === 'MAP_DIAGRAM' ? W*0.46 : W*0.62);
    var goldHeight = c.family === 'EXHIBIT_DOC' ? H*0.56 : H*0.24;
    var gold = comp.layers.addSolid([0.9, 0.71, 0.23], 'muted_gold_panel', Math.round(goldWidth), Math.round(goldHeight), 1, c.dur);
    gold.property('ADBE Transform Group').property('ADBE Position').setValue([W/2, H*0.5]);
    gold.property('ADBE Transform Group').property('ADBE Opacity').setValue(c.family === 'EXHIBIT_DOC' ? 28 : 72);
    gold.motionBlur = true;
    if (c.family === 'HERO_DATA') addText(comp, '48', 260, [0.961,0.969,0.980], H*0.49);
    if (c.family === 'ACT_TITLE') addText(comp, 'ACT', 220, [0.961,0.969,0.980], H*0.52);
    if (c.family === 'EXHIBIT_DOC') addText(comp, 'EXHIBIT', 110, [0.043,0.102,0.169], H*0.50);
    if (c.family === 'TIMELINE_TRACK') addText(comp, 'TIMELINE', 100, [0.961,0.969,0.980], H*0.38);
    if (c.family === 'MAP_DIAGRAM') addText(comp, 'MAP', 140, [0.961,0.969,0.980], H*0.50);
    if (c.family === 'INTERSTITIAL_WIPE') addText(comp, 'PRIME DOCUMENTARY', 72, [0.961,0.969,0.980], H*0.52);
    var rq = project.renderQueue.items.add(comp);
    try {{ rq.applyTemplate('最良設定'); }} catch (e1) {{ try {{ rq.applyTemplate('Best Settings'); }} catch (e2) {{}} }}
    var om = rq.outputModule(1);
    try {{ om.applyTemplate('H.264 - レンダリング設定を一致 - 15 Mbps'); }} catch (e3) {{ try {{ om.applyTemplate('H.264 - Match Render Settings - 15 Mbps'); }} catch (e4) {{}} }}
    om.file = new File(renderFolder.fsName + '/' + c.id + '.mp4');
  }}
  project.save(new File(outFolder.fsName + '/frazier_ae.aep'));
  var ok = new File(renderFolder.fsName + '/_build_ok.txt');
  ok.open('w');
  ok.write('ok');
  ok.close();
  app.endUndoGroup();
  app.quit();
  }} catch (error) {{
    errorFile.open('w');
    errorFile.write(error.toString() + '\\nline=' + error.line);
    errorFile.close();
    try {{ app.endUndoGroup(); }} catch (undoError) {{}}
    app.quit();
  }}
}}());
"""
    out.write_text(jsx, encoding="utf-8")


def selftest_null() -> int:
    spec = {
        "episode_id": EP,
        "cards": [
            {"id": "hb01", "family": "HERO_DATA", "still": "S01", "value": None, "claim_id": "C-039-001", "start": 10, "dur": 5}
        ],
    }
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "ae_cards.null.json"
        p.write_text(json.dumps(spec), encoding="utf-8")
        try:
            validate_spec(load_json(p))
        except SystemExit as exc:
            print(str(exc))
            return 1
    print("FAIL frazier_ae: null selftest unexpectedly passed")
    return 2


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", type=Path, default=DEFAULT_SPEC)
    ap.add_argument("--out", type=Path, default=DEFAULT_JSX)
    ap.add_argument("--derived", type=Path, default=DEFAULT_DERIVED)
    ap.add_argument("--validate", action="store_true")
    ap.add_argument("--selftest-null", action="store_true")
    args = ap.parse_args()
    if args.selftest_null:
        return selftest_null()
    spec = load_json(args.spec)
    cards = validate_spec(spec)
    args.derived.parent.mkdir(parents=True, exist_ok=True)
    resolved = {"episode_id": EP, "cards": [{**card, "end": float(card.get("start") or 0) + float(card.get("dur") or card.get("duration_sec") or 3)} for card in cards]}
    args.derived.write_text(json.dumps(resolved, ensure_ascii=False, indent=2), encoding="utf-8")
    DEFAULT_CARDS.write_text(json.dumps(resolved, ensure_ascii=False, indent=2), encoding="utf-8")
    if not args.validate:
        write_jsx(cards, args.out)
    print(json.dumps({"ok": True, "cards": len(cards), "spec": str(args.spec), "jsx": str(args.out)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
