#!/usr/bin/env python3
"""Decide the retention gate on the SCRIPT, where fixing it is free.

WHY THIS EXISTS
---------------
`retention_cadence` is the single most-failed check on the channel: **18 of 34** finished
episodes shipped red on it. It is measured after the render, from `<slug>_film.json captions[]`,
which means the answer arrives three GPU-hours after the moment it became true -- and by then
the only options are ship-it-anyway or burn another three hours. Every episode took the first.

But the thing it measures is already fully determined by the script. Measured 2026-08-23:

    ramirez      10 questions, 26.7 min, biggest question-free gap 10.7 min -> RED
    centralpark  11 questions, 60.7 min, biggest gap 11.6 min               -> RED
    greene        8 questions, 30.7 min, biggest gap  6.6 min               -> GREEN
    marmet        7 questions, 31.4 min, biggest gap  6.4 min               -> GREEN
    wronghouse    3 questions, 39.8 min, biggest gap 28.2 min               -> RED

**It is not the number of questions. It is the spacing.** ramirez asked ten and still failed,
because they clustered in the first six minutes. greene asked eight, spread them, and passed.

So this reads the script, places each `?` by cumulative word count, converts to minutes at the
channel's measured narration pace, and reports the largest question-free gap -- the same number
the post-render gate will compute, available while the script is still a text file.

HOW THE ESTIMATE IS MADE, AND WHERE IT IS SOFT
---------------------------------------------
Position in minutes = words-so-far / NARRATION_WPM. `docs/PD_CANON.md` §7 25 measured the real
pace at **159.5-169.7 wpm** and warns that the 176 in older docs is optimistic and that the
`measured wpm` in narration logs excludes the silence between chunks. 160 is used here, the
conservative end, which makes this estimate slightly PESSIMISTIC about gaps -- it will call a
borderline script red a little before the film would. That is the right direction to be wrong in
at a stage where the fix costs a sentence.

Non-narrated sections (`OP`, and anything after `ENDING` such as the writer's notes) are
excluded from the word count, because they are not spoken.

Usage:
    py -3.11 scripts/check_script_retention_plan.py --script <path.md>
    py -3.11 scripts/check_script_retention_plan.py --slug hyatt
    py -3.11 scripts/check_script_retention_plan.py --slug hyatt --json

Exit codes: 0 the script will pass the retention gate, 1 it will not, 2 no script found.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

NARRATION_WPM = 160.0          # conservative end of the measured 159.5-169.7 (PD_CANON §7 25)
MAX_QUESTION_GAP_S = 420.0     # the literal-question floor check_retention_cadence enforces
NOT_SPOKEN = {"OP"}            # section names that carry no narration
STOP_AFTER = re.compile(r"^(WHAT I WANTED TO SAY|NOTES?|APPENDIX|SOURCES?)\b", re.I)

RE_SECTION = re.compile(r"^##\s+(?P<name>[A-Z_0-9]+)(?:\s|$)")


def staleness(slug: str, script_questions: int) -> str | None:
    """Does the script still describe the narration that was actually spoken?

    `03_script/script.en.v001.md` carries its own warning -- "Do not edit this file. Edit the
    planning script and regenerate." Measured 2026-08-23, five episodes were never regenerated:

        greene   script 5 questions, actually spoken 9
        memphis  script 0, spoken 7
        marmet   script 1, spoken 7
        hyatt    0 / 0   (consistent)
        ramirez  11 / 11 (consistent)

    So on EP62-66 the file describes a different film from the one that exists, and any tool
    that reads it -- including this one -- reports on a draft nobody shipped. EP67 onward, the
    format the channel uses now, matches exactly. When the narration index exists it is the
    authority; say so rather than quietly disagreeing with reality.
    """
    hits = sorted(ROOT.glob(f"episodes/PD-2026-*-{slug}/06_audio/narration_index.v001.json"))
    if not hits:
        return None
    try:
        d = json.loads(hits[-1].read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    chunks = d.get("chunks") or d.get("items") or []
    spoken_q = sum((c.get("spoken_text") or c.get("text") or "").count("?") for c in chunks)
    if spoken_q == script_questions:
        return None
    return (f"the script says {script_questions} question(s) but the narration that was actually "
            f"recorded has {spoken_q} -- 03_script was never regenerated from the planning "
            f"script. Trust the narration index; this reading describes a draft.")


def find_script(slug: str) -> Path | None:
    """The script the pipeline actually reads, then the planning copy."""
    for pat in (f"episodes/PD-2026-*-{slug}/03_script/script.en.v*.md",
                f"episodes/_planning/EP*_{slug}_script.en.v*.md"):
        hits = sorted(ROOT.glob(pat))
        if hits:
            return hits[-1]
    return None


RE_VO = re.compile(r"^\s*\[VO:\]\s*(?P<line>.*)$")


def vo_lines(text: str) -> list[str] | None:
    """The canonical narration is the `[VO:]` form in 03_script/script.en.v001.md.

    Learned by measuring, 2026-08-23: EVERY episode from EP62 to EP76 has `[VO:]` lines there
    (162-542 of them), but only EP62-66 also carry `## ACT_*` headings -- EP67 onward have none.
    A parser that keys on the headings reads 0 spoken words on nine of fourteen episodes and
    then cheerfully reports PASS. It did exactly that on hyatt, ramirez and wronghouse before
    this function existed. `[VO:]` is what the narrator actually says; parse that.
    """
    out = [m.group("line").strip() for line in text.splitlines()
           if (m := RE_VO.match(line))]
    return out or None


def parse(text: str) -> list[dict]:
    """Sections in order, each with its spoken words and the word offsets of its questions."""
    out: list[dict] = []
    cur: dict | None = None
    stopped = False
    for line in text.splitlines():
        m = RE_SECTION.match(line.strip())
        if m:
            name = m.group("name")
            if STOP_AFTER.match(line.strip().lstrip("# ")):
                stopped = True
            cur = {"name": name, "lines": [], "spoken": name not in NOT_SPOKEN and not stopped}
            out.append(cur)
            continue
        if line.strip().startswith("## "):          # a heading we do not recognise: stop counting
            cur = {"name": line.strip("# ").strip()[:24], "lines": [], "spoken": False}
            out.append(cur)
            continue
        if cur is not None:
            cur["lines"].append(line)
    return out


def analyse_vo(lines: list[str]) -> dict:
    """The canonical path: cumulative words over the spoken lines, questions placed by position."""
    words_seen = 0
    q_positions: list[float] = []
    for line in lines:
        body = re.sub(r"\((?:SFX|MUSIC|AMB)[^)]*\)", " ", line)   # direction, never spoken
        for tok in body.split():
            words_seen += 1
            if "?" in tok:
                q_positions.append(words_seen / NARRATION_WPM)
    total_min = words_seen / NARRATION_WPM
    points = [0.0] + q_positions + [total_min]
    gaps = [(points[i + 1] - points[i], points[i]) for i in range(len(points) - 1)]
    worst_gap, worst_at = max(gaps) if gaps else (0.0, 0.0)
    return {
        "check": "script_retention_plan", "source": "[VO:] lines (canonical narration)",
        "ok": worst_gap * 60 <= MAX_QUESTION_GAP_S,
        "narration_wpm_assumed": NARRATION_WPM,
        "spoken_words": words_seen, "projected_minutes": round(total_min, 1),
        "questions": len(q_positions),
        "worst_question_gap_min": round(worst_gap, 1),
        "worst_gap_starts_at_min": round(worst_at, 1),
        "gap_ceiling_min": MAX_QUESTION_GAP_S / 60,
        "question_positions_min": [round(q, 1) for q in q_positions],
        "sections": [],
    }


def analyse(text: str) -> dict:
    vo = vo_lines(text)
    if vo:
        return analyse_vo(vo)
    sections = parse(text)
    words_seen = 0
    q_positions: list[float] = []          # minutes
    per_section = []
    for s in sections:
        body = "\n".join(s["lines"])
        # strip markdown citation comments and bracketed direction, neither is spoken
        body = re.sub(r"<!--.*?-->", " ", body, flags=re.S)
        body = re.sub(r"^\s*[\[(].*?[\])]\s*$", " ", body, flags=re.M)
        if not s["spoken"]:
            per_section.append({"section": s["name"], "spoken": False, "words": 0, "questions": 0})
            continue
        n_q = 0
        for tok in body.split():
            words_seen += 1
            if "?" in tok:
                q_positions.append(words_seen / NARRATION_WPM)
                n_q += 1
        words = len(body.split())
        per_section.append({"section": s["name"], "spoken": True, "words": words, "questions": n_q})

    total_min = words_seen / NARRATION_WPM
    points = [0.0] + q_positions + [total_min]
    gaps = [(points[i + 1] - points[i], points[i]) for i in range(len(points) - 1)]
    worst_gap, worst_at = max(gaps) if gaps else (0.0, 0.0)

    spoken = [p for p in per_section if p["spoken"]]
    silent_sections = [p["section"] for p in spoken if p["questions"] == 0]
    ok = worst_gap * 60 <= MAX_QUESTION_GAP_S

    return {
        "check": "script_retention_plan",
        "ok": ok,
        "narration_wpm_assumed": NARRATION_WPM,
        "spoken_words": words_seen,
        "projected_minutes": round(total_min, 1),
        "questions": len(q_positions),
        "worst_question_gap_min": round(worst_gap, 1),
        "worst_gap_starts_at_min": round(worst_at, 1),
        "gap_ceiling_min": MAX_QUESTION_GAP_S / 60,
        "sections_without_a_question": silent_sections,
        "sections": per_section,
    }


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    ap = argparse.ArgumentParser()
    ap.add_argument("--script", type=Path)
    ap.add_argument("--slug")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    path = a.script or (find_script(a.slug) if a.slug else None)
    if path is None or not path.is_file():
        print(f"no script found for {a.slug or a.script!r}", file=sys.stderr)
        return 2

    r = analyse(path.read_text(encoding="utf-8", errors="replace"))
    r["script"] = str(path.relative_to(ROOT))
    r["stale_warning"] = staleness(a.slug, r["questions"]) if a.slug else None
    if a.json:
        print(json.dumps(r, ensure_ascii=False, indent=1))
        return 0 if r["ok"] else 1

    print(f"{'PASS' if r['ok'] else 'FAIL'}  {path.name}")
    if r.get("stale_warning"):
        print(f"  STALE  {r['stale_warning']}")
    print(f"  {r['spoken_words']:,} spoken words -> ~{r['projected_minutes']} min at "
          f"{r['narration_wpm_assumed']:.0f} wpm")
    print(f"  {r['questions']} question(s); biggest question-free gap "
          f"{r['worst_question_gap_min']} min starting at {r['worst_gap_starts_at_min']} min "
          f"(ceiling {r['gap_ceiling_min']:.0f} min)")
    for s in r["sections"]:
        if not s["spoken"]:
            continue
        mark = " <-- no question" if s["questions"] == 0 else ""
        print(f"    {s['section']:<10} {s['words']:>5} words  {s['questions']} question(s){mark}")
    if not r["ok"]:
        print(f"\n  Put a question in each act. Not more questions -- better spaced ones: "
              f"ramirez asked ten and still failed because they clustered in the first six "
              f"minutes; greene asked eight, spread them, and passed.")
    return 0 if r["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
